### ISSUE TITLE
Singularity library not working (sylabs domain expired?)

### ISSUE THREAD

**Issue by Davte** [sylabs/singularity#1055]
### Version of Singularity:

```
$ singularity --version
singularity version 3.8.7

```

### Expected behavior

Being able to pull from library, visit sylabs.io and its subdomains
```
$ singularity exec library://alpine cat /etc/alpine-release
3.9.2
```

### Actual behavior
Website is down (probably domain expired as it says [here](http://sylabs.io/)).

```
$ singularity exec library://alpine cat /etc/alpine-release
FATAL:   Unable to handle library://alpine uri: error making request to server:
	Get "https://library.sylabs.io/v1/images/alpine:latest?arch=amd64": EOF
```

### Steps to reproduce this behavior
Install singularity and try to run `singularity exec library://alpine cat /etc/alpine-release` or just try to visit any sylabs page (e.g. `curl --verbose https://sylabs.io`)

### What OS/distro are you running
Not relevant I guess.
```
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### How did you install Singularity
Source

**Comment by tri-adam** [comment]
Hi @Davte. We're working on resolving an issue with the `sylabs.io` domain.

In the meantime, Singularity services can be accessed at: https://cloud.sycloud.io/. To configure the CLI to work with this, do:

```
singularity remote add sycloud cloud.sycloud.io
singularity use sycloud
```

Thanks for your patience.
