### ISSUE TITLE
cant build image.

### ISSUE THREAD

**Issue by Hyuuri** [sylabs/singularity#1065]
Today, I  try to build a image from my def file.
Then, this error happen.
 
error message 
~~~
FATAL : Unable to get key server client configuration: error making request to server: Get "https://cloud.sylabs.io/assets/config/config.prod.json"
~~~

Now, I dont know  whether sylab server is running.
What do I for this problem?

**Comment by musan6363** [comment]
This problem seems to have already been solved.

Please check this Issue(#1055).

**Comment by Hyuuri** [comment]
thank you! 
I cant find this closed issue. sry
