### ISSUE TITLE
--writable-tmpfs for %test in singularity build

### ISSUE THREAD

**Issue by maressyl** [sylabs/singularity#109]
Hi,

Some of the software I want to embed in my image writes systematically in `/var/log/$dedicated_directory` when starting, even if just to display the version as I use in the `%test` section of my recipe. It is not a problem when using the image itself with a `--writable` flag or similar, but I can't find a way to test my software is properly installed at build time as I always get errors related to attempts to write on a read-only file system.

The ability to use `--writable-tmpfs` in `singularity build` for the test section as available for `singularity shell` or `singularity exec` would solve my problem and allow more flexibility in image testing.

I also considered to use `--bind`, but the directory used by the problematic software writes to a subdirectory of `/var/log` which do not exist at the moment the binding is done, so my only option is to bind the whole `/var/log` which I feel to be inadequate. 

I am using singularity 3.8.0 with a docker debian:buster bootstrap.

Best regards,
Sylvain

**Comment by dtrudg** [comment]
Understood. This is definitely something that should be possible in some manner.

**Comment by dtrudg** [comment]
@maressyl - I've drafted this functionality at: https://github.com/sylabs/singularity/pull/136

If you are able to check it out and confirm it satisfies your need that would be great.

**Comment by dtrudg** [comment]
This has been merged to the master branch, for the future SingularityCE 3.9 release. Let us know if you find any issues with it.
