### ISSUE TITLE
Add SINGULARITY_INSTANCE env variable containing the instance name

### ISSUE THREAD

**Issue by dmachi** [sylabs/singularity#1132]
Our setup has a container instance write some information about itself during %startscript on a --bind mount point that makes it easier to interact with the instance subsequently.    This information includes the image file (SINGULARITY_CONTAINER) and the bind paths used to start the instance (SINGULARITY_BIND).  However, the declared instance name is not an available ENV variable and I haven't been able to figure out any other way of knowing the instance name from within a container.

It would be a great enhancement (for me anyway) if the instance name could be exported via environment variable just like the other key properties are.  Perhaps SINGULARITY_INSTANCE.

As a work around for the time being, I am passing an additional argument to %startscript when I create the instance:

singularity instance start --bind /some/path:/config /path/to/image.sif instance_name instance_name

As you can see, this command passes instance_name twice.  The first is used by singularity of course and the second ends up as $1 in %startscript.  Of course this can be brittle because people forget to put the second parameter on (or think it is a typo) or don't take care that the match.

**Comment by dtrudg** [comment]
This sounds reasonable to me. It should be an easy thing to include in 3.11.

**Comment by dtrudg** [comment]
Hi @dmachi - this has been implements in the `main` branch, and will be part of the 3.11 release, which should take place in the next month or so.
