### ISSUE TITLE
Revocation Checks for X.509 Certificates

### ISSUE THREAD

**Issue by tri-adam** [sylabs/singularity#1152]
As discussed in https://github.com/sylabs/singularity/issues/1095, the `singularity verify` command should support optional revocation checks via the Online Certificate Status Protocol (OCSP) and/or Certificate Revocation List (CRL).

@fnikolai, I know you've already taken a look at OCSP... if you want to jump in here, we'd be very grateful for the contribution.

**Comment by fnikolai** [comment]
@tri-adam Sure. I 'll try to integrate it in the next couple of days. 

However, "end-to-end testing" can be an issue, in the sense that we need a properly signed certificate, with root and intermediate certificates. 

Since I do not have such a certificate, I 've tested the OCSP code by verifying Google's certificate chain.

To download the certificate chain:
```
openssl s_client -connect google.com:443 -showcerts
```

**Comment by tri-adam** [comment]
Awesome. Sounds good on the approach of using Google's certificate chain... that appears to be the approach taken in the `golang.org/x/crypto/ocsp` unit tests ([ref](https://cs.opensource.google/go/x/crypto/+/refs/tags/v0.3.0:ocsp/ocsp_test.go)).

In terms of end-to-end testing, yeah, it'd be pretty tough. We could probably hack something by implementing a local OCSP responder, and then generating a certificate that references it on the fly using code similar to what's in [gen_certs.go](https://github.com/sylabs/singularity/pull/1139/files#diff-15c61b1546f46db34a8b5b19ce7ca26aea8a2ed4b37528642c06221837f429ea). Alternatively, we could test the unhappy path... generate a certificate that references an OCSP responder that _won't_ say it's valid, and just make sure that the command errors out as expected.

**Comment by fnikolai** [comment]
@tri-adam
Good news ... and bad news!

The PR is ready.
https://github.com/sylabs/singularity/pull/1160

However, I had used your verify-certificates branch as a reference, which now seems to be deleted ... and that carried some other commits :S (I admit my poor git skills).

In any case, the only files that were changed are:

    cmd/internal/cli/{verify,x509}.go
    internal/app/singularity/verify.go {required the x509.ExtKeyUsageClientAuth}

**Comment by tri-adam** [comment]
Hmm, the branch hasn't been deleted... it's available here: https://github.com/tri-adam/singularity/tree/verify-certificate. You should be able to `rebase` onto it I think?

**Comment by fnikolai** [comment]
In that case, should I make a PR for singularity/main or tri-adam/verify-certificate ?

**Comment by tri-adam** [comment]
Apologies for the slow reply. Against `singularity/main` is good, looks like you're already headed in that direction with #1160. Thanks!

**Comment by fnikolai** [comment]
Continuing the discussion on https://github.com/sylabs/singularity/pull/1139, the OCSP responder keeps failing if any of the certificates involve Ed25519. 

https://github.com/fnikolai/singularity-x509/commit/458f46188746e4bee8b89da51809d91c7cea8b43

If we want to put it into action, we can document that it works only with RSA, and let the user drive the key selection. 

Otherwise, we can postpone the PR until we resolve the issue.

**Comment by fnikolai** [comment]
@tri-adam, @dtrudg 

Following the discussion on https://github.com/sylabs/singularity/pull/1139#issuecomment-1343472842, the erratic behavior of OCSP is attributed to [this line of crypto library](https://cs.opensource.google/go/go/+/refs/tags/go1.19.4:src/crypto/x509/x509.go;l=830,832).

In fact, the issue is irrelevant to the OCSP. You can also face it if you apply signature validation when you generate the certificates on `gen_certs.go`
```go
func createLeaf(...) {
....
	fmt.Printf("ParentSignature %s\n", parent.SignatureAlgorithm)

	if err := tmpl.CheckSignatureFrom(parent); err != nil {
		return nil, err
	}

	return createCertificate(tmpl, parent, key.(crypto.Signer).Public(), parentKey)
}
```

I 'm still not sure why they have decided to exclude ED25519, but we don't have many options with that constraint in place. We could:
- fail early with an explanation message (the default message is not very helpful)
- ignore the expected failure and continue with the other certificates

**Comment by tri-adam** [comment]
> @tri-adam, @dtrudg
> 
> Following the discussion on [#1139 (comment)](https://github.com/sylabs/singularity/pull/1139#issuecomment-1343472842), the erratic behavior of OCSP is attributed to [this line of crypto library](https://cs.opensource.google/go/go/+/refs/tags/go1.19.4:src/crypto/x509/x509.go;l=830,832).

The logic in that portion of the crypto library returns an error only when the hash is `crypto.Hash(0)` and `pubKeyAlgo != Ed25519`. This logic appears valid to me, as the Ed25519 implementation requires the caller pass `crypto.Hash(0)` to indicate the message is not pre-hashed ([ref](https://pkg.go.dev/crypto/ed25519#PrivateKey.Sign)).

It's worth noting that the `crypto/x509` package documentation explicitly mentions Ed25519 support, for example in [CreateCertificate](https://pkg.go.dev/crypto/x509#CreateCertificate). On that basis, I don't agree that a lack of support within OCSP is due to a lack of support in the `crypto/x509` package. 

> In fact, the issue is irrelevant to the OCSP. You can also face it if you apply signature validation when you generate the certificates on `gen_certs.go`
> 
> ```go
> func createLeaf(...) {
> ....
> 	fmt.Printf("ParentSignature %s\n", parent.SignatureAlgorithm)
> 
> 	if err := tmpl.CheckSignatureFrom(parent); err != nil {
> 		return nil, err
> 	}
> 
> 	return createCertificate(tmpl, parent, key.(crypto.Signer).Public(), parentKey)
> }
> ```

That code snippet is attempting to verify `tmpl`, which is the _template_ rather than the generated certificate. If you instead call `CheckSignatureFrom` on the certificate returned by `createCertificate`, it will validate as expected:

```diff
$ git diff ./gen_certs.go
diff --git a/test/certs/gen_certs.go b/test/certs/gen_certs.go
index 62df0fa77..367c1f037 100644
--- a/test/certs/gen_certs.go
+++ b/test/certs/gen_certs.go
@@ -128,7 +128,13 @@ func createLeaf(start time.Time, parentKey crypto.PrivateKey, parent *x509.Certi
                MaxPathLenZero: true,
        }
 
-       return createCertificate(tmpl, parent, key.(crypto.Signer).Public(), parentKey)
+       c, err := createCertificate(tmpl, parent, key.(crypto.Signer).Public(), parentKey)
+
+       if err := c.CheckSignatureFrom(parent); err != nil {
+               return nil, err
+       }
+
+       return c, err
 }
 
 // writeCerts generates certificates and writes them to disk.
```

> I 'm still not sure why they have decided to exclude ED25519, but we don't have many options with that constraint in place. We could:
> 
> * fail early with an explanation message (the default message is not very helpful)
> * ignore the expected failure and continue with the other certificates

Having said all the above, it's perfectly plausible that the `https://pkg.go.dev/golang.org/x/crypto/ocsp` package does not have Ed25519 support. In particular, it looks to me that [ocsp.ParseResponseForCert](https://pkg.go.dev/golang.org/x/crypto/ocsp#ParseResponseForCert) calls `getSignatureAlgorithmFromOID`, and `signatureAlgorithmDetails` lacks Ed25519 bindings. _Interestingly_, the code there mentions:

```
// TODO(rlb): This is also from crypto/x509, so same comment as AGL's below
```

In fact, there are several `SignatureAlgorithm` defined in `crypto/x509` that do not have a corresponding entry in `signatureAlgorithmDetails`, including `PureEd25519`.

Having said all of this, I propose:

- Use [ocsp.CreateRequest](https://pkg.go.dev/golang.org/x/crypto/ocsp#CreateRequest) to create the request, send it to the OCSP server. I don't believe this involves any signing/verifying, just hashing details from the cert. Should work regardless of the algorithm used in the certificate.
- Use [ocsp.ParseResponse](https://pkg.go.dev/golang.org/x/crypto/ocsp#ParseResponse) (or `ParseResponseForCert`) to parse the response from the OCSP server. Under the assumption that this fails with Ed25519, I think that's fine, as long as the error message makes it clear that parsing the OCSP response failed.

Finally, it may be worth searching to see if there is an issue open against `golang.org/x/crypto/ocsp` for Ed25519 support? If one does not seem to exist, it may be worth opening. Who knows, perhaps others are getting bit by this too!

Thanks @fnikolai. And, happy holidays!

**Comment by fnikolai** [comment]
@tri-adam 
Happy holidays as well!

The PR is ready. Apologies for the delay -- just found some time to finalize it. 

Let me know what you think -- especially on the e2e testing.
