### ISSUE TITLE
Broken Link in Documentation

### ISSUE THREAD

**Issue by jjacobson95** [sylabs/singularity#1159]
The link for mac installation leads to a 404 error.
Documentation page:
https://docs.sylabs.io/guides/3.5/admin-guide/installation.html#mac

Link
"Download a Mac installer package [here](https://www.sylabs.io/singularity-desktop-macos/)."

**Comment by dtrudg** [comment]
From the URL pasted, you are looking at the documentation for version 3.5, which is no longer supported. There should be a banner visible at the top of each documentation page alerting readers about this.

I'm afraid Singularity Desktop for Mac was retired and is no longer available.

We don't update old documentation, but it is left unchanged for reference.
