### ISSUE TITLE
Is the Slurm plugin still maintained?

### ISSUE THREAD

**Issue by elgalu** [sylabs/singularity#116]
I noticed https://github.com/sylabs/singularity/blob/master/docs/2.x-slurm/singularity.c hasn't been touched in the last 3 years, while https://github.com/NVIDIA/pyxis is now an active project with a similar objective.

Would you recommend using Slurm+Singularity plugin in 2021 or is this something rather deprecated? Also Singularity version is >=3 while the plugin might only work for version 2?

**Comment by dtrudg** [comment]
The Slurm plugin was not continued for the 3.x version of Singularity. It was not widely used and Singularity is generally straightforward to call directly from batch scripts.

We'd be interested in knowing how features similar to the pyxis plugin for enroot would be useful to you vs calling Singularity directly in a batch script.

**Comment by elgalu** [comment]
The main use case we have is to __only__ allow users to run containerized Slurm jobs, so is easier/faster to move this workloads to production as they were already containerized in the first place. If the user is free to add the singularity commands from the batch scripts they may or may not use it.

Also, with pyxis, one can configure it to centrally cache container images on-demand, but this is not the main requirement.

**Comment by dtrudg** [comment]
Understood. I think at this point unless there is broad demand we aren't likely to create a plugin again in the short term, but we'd be very happy to assist any community effort to maintain one as a separate project.
