### ISSUE TITLE
Build maximum time limit exceeded

### ISSUE THREAD

**Issue by neel04** [sylabs/singularity#1172]
- Version of Singularity 3.10

---

Hi, I'm using `--remote` build w/ Singularity. However, I'm constantly exceeding the max duration of `1hour` that is pre-set when trying to build a container. Its seems generating the `SBOM` takes too much time.

Thus, does anyone know:
- How we can disable the SBOM generation
- extend the max time limit to `2h` allowing it to complete

my work has been stalled for a couple of days due to this SBOM update. help would be greatly appreciated.

**Comment by dtrudg** [comment]
Note also that for issues relating to cloud.sylabs.io rather than the SingularityCE project itself, support contacts are as at the link below: https://cloud.sylabs.io/support

**Comment by EmmEff** [comment]
@neel04 assuming you've been able to build this container previously, what size is it? Approximately how many tiles are contained within? We've received no reports of the SBOM generation causing build times to balloon.

**Comment by neel04** [comment]
Heya, here's the entire def file
```py
Bootstrap: docker
From: nvcr.io/nvidia/pytorch:22.07-py3

%post
    apt-get -y update
    apt-get -y install nano vim libfreetype6-dev
    pip3 uninstall pil
    pip3 install s3fs opencv-python-headless scipy tensorflow_datasets Ipython matplotlib wandb
    pip3 install -U tensorflow_io nvitop tensorflow_datasets timm torchinfo
    pip3 install -U --no-cache-dir tensorflow~=2.9.1 torchmetrics Pillow Image
    pip3 install git+https://github.com/huggingface/accelerate
    # Turning above requirements to pip3 install
    pip3 install einops hydra-core omegaconf tensorboard tensorboard-plugin-wit torchvision tqdm comet-ml easy-to-hard-data icecream matplotlib numpy pandas Pillow scipy seaborn svglib 
```

Its a relatively simple set of packages; note that most of them are already pre-installed from the bootstrapped image, but are present to gurantee their existence. 

I'd say the SIF file is generated in about ~25-30 mins, but SBOM exceeds the hour mark. The above `.def` file should reproduce it.

Do let me know in case of further queries.

Cheers,
Neel

**Comment by EmmEff** [comment]
Yes. SBOM generation has been temporarily disabled in SCS, so this should no longer be an issue.

**Comment by MartinPernus** [comment]
I am having the exact same problem when building the following def file:

```bash
BootStrap: docker
From: nvidia/cuda:10.1-devel-ubuntu18.04
 
%environment
export PATH=/bin:/usr/bin:/usr/local/bin:/usr/local/cuda/bin
export LC_ALL=C

%post
apt-get -y update
export DEBIAN_FRONTEND=noninteractive
apt-get install -y --no-install-recommends libhdf5-dev graphviz locales python3-dev python3-pip vim ninja-build python3.8 python3.8-dev python3.8-venv git-all ffmpeg

# update python pip
python3.8 -m pip --no-cache-dir install --upgrade pip
python3.8 -m pip --no-cache-dir install setuptools --upgrade

# install required libraries
python3.8 -m pip install wheel cython numpy matplotlib pandas tqdm imageio legacy imageio-ffmpeg tqdm scikit-learn scikit-image click
python3.8 -m pip install torch==1.7.1+cu101 torchvision==0.8.2+cu101 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by EmmEff** [comment]
Thank you for the feedback, @MartinPernus. We have disabled SBOM generation for the time being. Your remote build should proceed as normal now.
