### ISSUE TITLE
trying to build container from dockerhub

### ISSUE THREAD

**Issue by amandalucasp** [sylabs/singularity#1178]
**Version of Singularity**
v3.10.4

I have a docker container uploaded dockerhub, and I am trying to build a container using Singularity as in the docs:
https://docs.sylabs.io/guides/3.10/user-guide/build_a_container.html#downloading-an-existing-container-from-docker-hub
The build command works fine. But when I try running the container, I get the following output:

```
/usr/bin/rm: cannot remove '/usr/local/cuda/compat/lib': Read-only file system
rm: cannot remove '/usr/local/cuda/compat/lib': Read-only file system
rm: cannot remove '/usr/local/cuda/compat/lib': Read-only file system

=============
== PyTorch ==
=============

NVIDIA Release 20.12 (build 17950526)
PyTorch Version 1.8.0a0+1606899

Container image Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.

Copyright (c) 2014-2020 Facebook Inc.
Copyright (c) 2011-2014 Idiap Research Institute (Ronan Collobert)
Copyright (c) 2012-2014 Deepmind Technologies    (Koray Kavukcuoglu)
Copyright (c) 2011-2012 NEC Laboratories America (Koray Kavukcuoglu)
Copyright (c) 2011-2013 NYU                      (Clement Farabet)
Copyright (c) 2006-2010 NEC Laboratories America (Ronan Collobert, Leon Bottou, Iain Melvin, Jason Weston)
Copyright (c) 2006      Idiap Research Institute (Samy Bengio)
Copyright (c) 2001-2004 Idiap Research Institute (Ronan Collobert, Samy Bengio, Johnny Mariethoz)
Copyright (c) 2015      Google Inc.
Copyright (c) 2015      Yangqing Jia
Copyright (c) 2013-2016 The Caffe contributors
All rights reserved.

NVIDIA Deep Learning Profiler (dlprof) Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.
NVIDIA modifications are covered by the license terms that apply to the underlying project or file.
rm: cannot remove '/usr/local/cuda/compat/lib': Read-only file system
ERROR: No supported GPU(s) detected to run this container

/usr/local/bin/nvidia_entrypoint.sh: line 90: /run_pytorch_apex.sh: Permission denied
```

**OS / Linux Distribution**
Ubuntu 18.04 installed on a VirtualBox VM.

**Installation Method**
From source, following the [install instructions](https://github.com/sylabs/singularity/blob/main/INSTALL.md).

If it helps, as on the output message, the container I'm trying to use is based on one of the official [NVIDIA Pytorch containers](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch). I have installed a few extra packages and uploaded it to my dockerhub user.

Any help would be much appreciated. Thanks!

**Comment by amandalucasp** [comment]
Should I use such flags during build the container, to execute or both?

**Comment by dtrudg** [comment]
The flags should be used when executing the container. Try `--writable-tmpfs` to being with, if `--compat` isn't available to you.

**Comment by amandalucasp** [comment]
I ran with --containall --writable-tmpfs and --cleanenv and the read-only errors are gone, but I still get the last one
```
/usr/local/bin/nvidia_entrypoint.sh: line 90: /run_pytorch_apex.sh: Permission denied
```
