### ISSUE TITLE
Version is git hash for release?

### ISSUE THREAD

**Issue by vsoch** [sylabs/singularity#1180]
Hiya! Am I building incorrectly if the release version is outputting what looks like a partial git hash?

```
make: Leaving directory '/home/runner/work/singularity-cli/singularity-cli/singularity-ce-3.10.4/builddir'
Run singularity version
  singularity version
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
2d1c176
```

That's from a github action - so the output of `singularity version` is  2d1c176. I'll test other versions and see if they have similar behavior. Thanks!

**Comment by dtrudg** [comment]
I'm not sure what you are getting there...

For the 3.8.4 release tarball I get....

```
$ singularity version
3.8.4
```

For an unreleased git checkout, it should be a version plus a suffix, e.g.

```
$ singularity version
3.10.0+346-g8fbd83543
```

**Comment by dtrudg** [comment]
Doh... somehow I read 3.8.4 somewhere instead of 3.10.4. However, 3.10.4 installed from the release tarball here still works as I'd expect:

```
$ singularity version
3.10.4
```

**Comment by vsoch** [comment]
I must be doing something silly then! Could you be an extra pair of eyes? Here are the steps: https://github.com/singularityhub/install-singularity/blob/main/action.yaml

And the output:  https://github.com/singularityhub/install-singularity/actions/runs/3645364755/jobs/6155447743

![image](https://user-images.githubusercontent.com/814322/206454172-cda1ed96-9f04-47e5-a945-e0e78313fd6b.png)

**Comment by dtrudg** [comment]
Oh ... are you building the source inside another git repo? The `scripts/get-version` looks for a git repo to pull version info from. If you use the release tarball then there is no singularity-ce repo... but if you extract it inside another git repo then it'll find the git info from the repo further up.

I guess this is what is happening. You could wget and build singularity under a temp dir instead?

**Comment by vsoch** [comment]
oh that's it! And that's exactly what I'll do - doh! Thanks @dtrudg !

**Comment by vsoch** [comment]
There we gooooo!! haha I feel... silly. 
![image](https://user-images.githubusercontent.com/814322/206458843-1eae0588-301b-470a-9366-8c37ef6ea7d4.png)

All is well <3 thank you again!
