### ISSUE TITLE
Consider cherry-pick of hpcng #6042

### ISSUE THREAD

**Issue by dtrudg** [sylabs/singularity#119]
**Type of issue**
HPCng cherry-pick

**Description of issue**
Consider cherry-pick of https://github.com/hpcng/singularity/pull/6042

**Comment by dtrudg** [comment]
The linked PR is to add the CLI argument for the image name into the list of things passed to the engine, so that it can be logged from a log plugin that runs at engine startup time. This allows e.g. the nice `library://ubuntu` name to be recorded for `singularity run library://ubuntu`, rather than the cryptic name of the SIF file in the cache.

I'm not convinced this is necessary, as engine startup does not seem like the best place for logging. Logging in the engine does not capture operations on keys, remotes etc. that do not invoke the engine. It also doesn't log e.g. attempted but failing attempts to run images. I anticipate these being generally important for anyone needing audit functionality, rather than just successful executions that make it to `PostStartProcess`.

Would appreciate your thoughts @tri-adam  - maybe we want to cherry-pick for compatibility?

**Comment by tri-adam** [comment]
> I'm not convinced this is necessary, as engine startup does not seem like the best place for logging. Logging in the engine does not capture operations on keys, remotes etc. that do not invoke the engine. It also doesn't log e.g. attempted but failing attempts to run images. I anticipate these being generally important for anyone needing audit functionality, rather than just successful executions that make it to `PostStartProcess`.
> 
> Would appreciate your thoughts @tri-adam - maybe we want to cherry-pick for compatibility?

I agree that there's probably a better place to log this. Also, the semantics of semver technically dictate that this type of addition to `type JSONConfig struct` be introduced in a minor release. Given that, my vote would be to exclude this from 3.8.x, and target a full solution for 3.9.
