### ISSUE TITLE
Installation instructions: paths and go compiler

### ISSUE THREAD

**Issue by renedominik** [sylabs/singularity#1200]
Hi, the download paths in the installation instructions are outdated. I think they are missing a '-ce' and should be e.g.:
wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-ce-${VERSION}.tar.gz

Then, although I have go 1.17 installed under /usr/local/go/bin and having this included in PATH, './mconfig' returns:
" checking: host Go compiler (at least version 1.17)... not found!"

(Ubuntu 18.04 server)

**Comment by dtrudg** [comment]
Please could you provide a link to the instructions you are following. The following are correct:

* https://github.com/sylabs/singularity/blob/main/INSTALL.md
* https://docs.sylabs.io/guides/latest/user-guide/quick_start.html#download-singularityce-from-a-release
* https://docs.sylabs.io/guides/latest/admin-guide/admin_quickstart.html#download-singularityce-from-a-github-release

It's possible you are arriving at docs for an older version, from a search engine or similar.

We do have banners on the old user guides and admin guides warning about this:

<img width="738" alt="image" src="https://user-images.githubusercontent.com/4522799/208079716-e3736ab4-2754-4454-ba1a-265c908f1ca6.png">

Regarding the go issue, please could you provide some more information about how you have installed go in that location. Did you follow the instructions in the guide, or install separately?

I have replicated the install on an Ubuntu 18.04 without any issue, so something is different between our machines.

Thanks.

**Comment by dtrudg** [comment]
Closing this, as there hasn't been any follow-up. Please don't hesitate to re-open it if there's an issue with the current documentation.
