### ISSUE TITLE
Support `--sif-fuse` in the `oci mount` / `oci unmount` flow.

### ISSUE THREAD

**Issue by dtrudg** [sylabs/singularity#1209]
`oci mount` and `oci unmount` should be able to be run unprivileged, using `--sif-fuse`, in which case they will use squashfuse to mount the SIF to a directory, before continuing to create the bundle.

**Comment by dtrudg** [comment]
On second thought..... this doesn't really make sense in 3.11, or probably at all. The `oci mount` command is always creating a writable bundle, with a writable overlay on top of the read-only rootfs mounted from the SIF.

We have to be in a userns to be able to perform the bind mount and overlay mount required to get a writable bundle, unprivileged.

We could re-exec inside a userns to do this (like `--oci run`), but then when we drop out after the bundle is mounted, the user will be back into a shell that *is not* part of the userns and mount namespace where the bundle lives. We'd have to keep a process in the userns to keep it alive, and anything subsequent has to know to join the ns to use the bundle.

I think the only sensible thing we can do here, unprivileged, is to create a read-only bundle with a fuse rootfs mount but no overlay... and defer to whatever runtime is going to run the bundle to setup its own overlay before executing? I don't really think this is something worth pursuing. Especially given the lack of use of `oci mount`. Better to spend time on the `--oci` runtime mode.

Tagging @tri-adam for any thoughts he might have :-)

**Comment by tri-adam** [comment]
Yeah, agreed. At the user level, can't really see much utility in having a read-only `oci mount`, and the alternative seems cumbersome.

**Comment by dtrudg** [comment]
As part of the `--oci` mode work, `squashfuse` will always be used for `oci mount` of a native SIF image  in 4.0.

The primary use of the `ocibundle`s is now providing container bundles for `--oci` mode.

See: #1897
