### ISSUE TITLE
slurm with singularity out of mem

### ISSUE THREAD

**Issue by zhaohongqiangsoliva** [sylabs/singularity#1214]
**Version of Singularity**
What version of Singularity are you using? Run:

```
$ singularity --version
3.7.3
```

**Describe the bug**

Out of memory 
I am running singularity with slurm on HPC with version 3.7.3, but it always shown out of mem 
I  run this code without slurm this error doesn't appear, how do I fix it?
I tried to increase the memory, I increased to 100G also the same

```
[M::bwa_idx_load_from_disk] read 3171 ALT contigs
[W::main_mem] when '-p' is in use, the second query file is ignored.
[M::process] read 662252 sequences (100000052 bp)...
[M::process] 0 single-end sequences; 662252 paired-end sequences
[kseq2bseq1] Failed to allocate 151 bytes at bwa.c line 37: Out of memory
[kb_putp_chn] Failed to allocate 444 bytes at bwamem.c line 187: Out of memory
```

```
#!/bin/bash
#SBATCH -p wzhcexclu06
#SBATCH -N 1
#SBATCH --ntasks-per-node=16
#SBATCH --mem 36000
#module add apps/singularity/3.7.3
source /work/share/ac7m4df1o5/bin/cromwell/set_singularity_cachedir.sh
SINGULARITY_CACHEDIR=/work/share/ac7m4df1o5/bin/cromwell/docker_download/Germline_singularity/singularity-cache
source /work/share/ac7m4df1o5/bin/cromwell/4_plugin/translate_docker/docker_trans.sh solivehong/samtools-picard-bwa@sha256:68eae459869592a095b75598039a65e02dede4f6e89cb1452a6a9e673cc10fa9
#source  /work/share/ac7m4df1o5/bin/singularity/env.sh
singularity exec --cleanenv --containall --bind /work/share/ac7m4df1o5/bin/cromwell/test/cromwell-executions/ExomeGermlineSingleSample/7588d6e9-6f32-40c9-9e6c-719318f3adf2/call-UnmappedBamToAlignedBam/UnmappedBamToAlignedBam/ad3e4ffa-9491-4da6-8d4e-36ec5de66404/call-SamToFastqAndBwaMemAndMba/shard-1:/cromwell-executions/ExomeGermlineSingleSample/7588d6e9-6f32-40c9-9e6c-719318f3adf2/call-UnmappedBamToAlignedBam/UnmappedBamToAlignedBam/ad3e4ffa-9491-4da6-8d4e-36ec5de66404/call-SamToFastqAndBwaMemAndMba/shard-1 $IMAGE /bin/bash /cromwell-executions/ExomeGermlineSingleSample/7588d6e9-6f32-40c9-9e6c-719318f3adf2/call-UnmappedBamToAlignedBam/UnmappedBamToAlignedBam/ad3e4ffa-9491-4da6-8d4e-36ec5de66404/call-SamToFastqAndBwaMemAndMba/shard-1/execution/script

```

**To Reproduce**

**Expected behavior**

**OS / Linux Distribution**
Which Linux distribution are you using?
centos7
```
$ cat /etc/os-release
```

**Comment by dtrudg** [comment]
Hello. This is unlikely to be a bug in Singularity, if the same code and singularity command runs okay outside of Slurm.

If you run without Slurm, and the command finishes without error, then do you know how much memory it uses without Slurm applying a limit? Is there any report in the output of the program / workflow.

It's likely that the google group or Slack channel are a better place to ask about this, as those are seen by more users. GitHub issues are not seen by large numbers of people familiar with specific software.

Links to the Slack channels and Google Group can be found at: https://sylabs.io/singularity/

**Comment by zhaohongqiangsoliva** [comment]
Thanks, I'll go to google group ask
