### ISSUE TITLE
Migrate to gopkg.in/yaml.v3

### ISSUE THREAD

**Issue by dtrudg** [sylabs/singularity#1217]
We should migrate to yaml.v3 to be assured that our dependency is maintained going forward.

See: https://github.com/go-yaml/yaml

There is limited use in the code base, but some minor changes are likely to be required.

```
internal/pkg/remote/remote_test.go
18:	yaml "gopkg.in/yaml.v2"

internal/pkg/remote/remote.go
22:	yaml "gopkg.in/yaml.v2"

internal/app/singularity/remote_add_test.go
15:	"gopkg.in/yaml.v2"
```

**Comment by sizhanx** [comment]
I am a student from the Virtualization class at the University of Texas at Austin, and participating open source development is part of the course requirement. We are willing to fix this if y'all want. Thanks!

**Comment by dtrudg** [comment]
Hi @sizhanx - yes, you can take this one if you wish.

**Comment by sizhanx** [comment]
Got it. I have already asked my instructor for approval to work of this issue. I'll let you know as soon as possible.

**Comment by sizhanx** [comment]
@dtrudg sorry for the late reply. We are confident to have it completed by a week from today.
