### ISSUE TITLE
Singularity integration with Kubernetes failing. Kubelet service didn't come due to 'Node not found' Error

### ISSUE THREAD

**Issue by uppadass** [sylabs/singularity#1218]
I'm trying to install singularity 3.10 on RHEL9 and singularity installation was successful. while integrating with kubernetes, master node initialization always failin. kubelet service didn't come up and it is throwing error message like 'Node not found"

**Comment by dtrudg** [comment]
Are you trying to use singularity-cri - https://github.com/sylabs/singularity-cri ?

I'm afraid the Singularity Kubernetes CRI integration there was archived in 2020 and is not maintained.

There is a fork by someone who is working on it recently - https://github.com/Nienkeeijsvogel/singularity-cri

You can also see the mailing list post here: https://groups.google.com/g/singularity-ce/c/sGc8KVwhhHo
