### ISSUE TITLE
`./mconfig` (during installation) says I don't have Go compiler, when clearly there exists one.

### ISSUE THREAD

**Issue by dyhan316** [sylabs/singularity#1236]
Hello, I am trying to install singularity on our server. (Ubuntu 22.04)

After installing go,  we tried to run `./mconfig` as the installation tutorial says, but it gives and error stating that the Go complier is not found, which is false since `go version` shows that go is installed. 
```
(base) dyhan316@node1:~/singularity$ ./mconfig
Configuring for project `singularity-ce' with languages: C, Golang
=> running pre-basechecks project specific checks ...
=> running base system checks ...
 checking: host C compiler... cc
 checking: host C++ compiler... c++
 checking: host Go compiler (at least version 1.17)... not found!
mconfig: could not complete configuration
(base) dyhan316@node1:~/singularity$ go version
go version go1.19.4 linux/amd64
```

Is there something that could be done here?

Thank you in advance for your answers!

**Comment by dtrudg** [comment]
It looks like you are using some kind of conda environment or other virtual environment. How was go installed?

Also note that if you installed go by un-tarring the release file, that when you upgrade you *must* remove the go directory and start again. Extracting a new version of go over an old version can cause various confusing issues.

**Comment by dyhan316** [comment]
It works now! Thank you:)
