### ISSUE TITLE
Unable to pull docker image

### ISSUE THREAD

**Issue by cosmicbeams** [sylabs/singularity#1334]
Hello all,

Here is whatI receive when trying to pull this image. 

```
singularity pull docker://geodynamics/aspect:v2.1.0
INFO:    Converting OCI blobs to SIF format
FATAL:   While making image from oci registry: error fetching image to cache: while building SIF from layers: unable to create new build: while searching for mksquashfs: exec: "mksquashfs": executable file not found in $PATH
```

Apparently the image is not being downloaded.
Any chance to have more verbosity ?
Is there a way to set a proxy ?

Thanks

**Comment by dtrudg** [comment]
At this point, the download has happened. The error message shows the issue:

```
while searching for mksquashfs: exec: "mksquashfs": executable file not found in $PATH
```

SingularityCE converts Docker images to its own SIF format. This needs the `mksquashfs` program to be available on your system. You will need to install `mksquashfs` on the system that you are using singularity on.

**Comment by cosmicbeams** [comment]
it's working now!
Thanks for the help!
