### ISSUE TITLE
nvidia-container-cli: read-only file system

### ISSUE THREAD

**Issue by xqms** [sylabs/singularity#1351]
**Version of Singularity**
singularity-ce version 3.11.0-jammy

**Describe the bug**
Running singularity with `--nv --nvccli` (or just `--nvccli`) results in the error message:

```
INFO:    Using cached image
INFO:    Setting 'NVIDIA_VISIBLE_DEVICES=all' to emulate legacy GPU binding.
INFO:    Setting --writable-tmpfs (required by nvidia-container-cli)
FATAL:   container creation failed: nvidia-container-cli failed with exit status 1: nvidia-container-cli: mount error: file creation failed: /var/lib/singularity/mnt/session/final/usr/bin/nvidia-smi: read-only file system
```

This looks strange to me since `--writable-tmpfs` is automatically enabled and seems to correctly mount an overlayfs (see attached log file with `-d`). I don't really know how to debug this further. Is there a way to stop during the container creation process and drop into a shell?

**To Reproduce**
`singularity run --nv --nvccli library://ubuntu:20.04`

**Expected behavior**
The container starts and allows me to use my nvidia gpu (RTX 3090).

**OS / Linux Distribution**
KDE Neon 5.27 (which really is Ubuntu 22.04 except for Qt+KDE packages)

**Installation Method**
Debian package from GitHub releases.

**Additional context**
Kernel version: 5.19.0-32-generic
nvidia driver version: 525.78.01
nvidia-container-cli version: 1.12.0

[singularity_debug_log.txt](https://github.com/sylabs/singularity/files/10805450/singularity_debug_log.txt)

**Comment by dtrudg** [comment]
Thank you for the report. I'm afraid there isn't an easy way to get extra debug info at this point.

If you run `singularity run --writable-tmpfs library://ubuntu:20.04` and then inside the container try to create a file, do you have a working writable-tmpfs overlay?

I'll look into the issue further soon.

**Comment by xqms** [comment]
Wow, that was quick :D

> If you run singularity run --writable-tmpfs library://ubuntu:20.04 and then inside the container try to create a file, do you have a working writable-tmpfs overlay?

That seems to work without problems (using sudo to write into the container's /usr/bin):
```
max@xq:~$ sudo singularity run --writable-tmpfs library://ubuntu:20.04
INFO:    Using cached image
Singularity> touch /usr/bin/test
Singularity> ls -la /usr/bin/test
-rwxr-xr-x. 1 root root 55640 Feb 22 16:39 /usr/bin/test
Singularity> exit
max@xq:~$ ls -la /usr/bin/test
ls: cannot access '/usr/bin/test': No such file or directory
```

**Comment by dtrudg** [comment]
@xqms - sorry about this issue. It's an unfortunate (but simple) regression due to handling the --writable-tmpfs flag in the wrong place, relative to the --nvccli flag, after a large refactor 😞 

As a workaround, you should find that if you specify `--writable-tmpfs` manually, then it works...

```
$ singularity run --nv --nvccli library://ubuntu:20.04
INFO:    Setting 'NVIDIA_VISIBLE_DEVICES=all' to emulate legacy GPU binding.
INFO:    Setting --writable-tmpfs (required by nvidia-container-cli)
FATAL:   container creation failed: nvidia-container-cli failed with exit status 1: nvidia-container-cli: mount error: file creation failed: /usr/local/var/singularity/mnt/session/final/usr/bin/nvidia-smi: read-only file system

$ singularity run --writable-tmpfs --nv --nvccli library://ubuntu:20.04
INFO:    Using cached image
INFO:    Setting 'NVIDIA_VISIBLE_DEVICES=all' to emulate legacy GPU binding.
Singularity> nvidia-smi
Wed Feb 22 16:10:07 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.142.00   Driver Version: 450.142.00   CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:1E.0 Off |                    0 |
| N/A   22C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

I'll likely get a patch into the `main` branch this week to fix it, and it'll be in the next patch release.

**Comment by xqms** [comment]
Ah, could have thought of trying that myself. Thanks for the quick diagnosis :)
