### ISSUE TITLE
"ERROR:   Network fakeroot is not permitted for unprivileged users." when using network with --fakeroot, but command succeeds

### ISSUE THREAD

**Issue by arozenfe** [sylabs/singularity#1352]
**Version of Singularity**
```
$ /usr/bin/singularity --version
singularity-ce version 3.11.0-1
```

**Describe the bug**

When trying to run singularity in new network namespace with fakeroot, the command succeeds, but it outputs an error:

```
ERROR:   Network fakeroot is not permitted for unprivileged users.
```

**To Reproduce**

```
$ singularity -s exec --fakeroot --net --network=fakeroot sles12sp5.sif ip -o -4 addr show scope global
ERROR:   Network fakeroot is not permitted for unprivileged users.
2: eth0    inet 10.23.0.4/16 brd 10.23.255.255 scope global eth0\       valid_lft forever preferred_lft forever
```

Without `--fakeroot` the command fails (as expected) and says that `network requires root or --fakeroot`.
```
$ singularity -s exec --net --network=fakeroot sles12sp5.sif ip -o -4 addr show scope global
ERROR:   Network fakeroot is not permitted for unprivileged users.
FATAL:   container creation failed: network requires root or --fakeroot, non-root users can only use --network=none unless permitted by the administrator
```

If in `/etc/singularity/singularity.conf` I configure `allow net networks = fakeroot`, the error is not shown.

```
$ grep 'allow net' /etc/singularity/singularity.conf
#allow net users = gmk, singularity
#allow net groups = group1, singularity
# groups listed in the allow net users / allow net groups directives. Thus feature
allow net networks = fakeroot

$ singularity -s exec --fakeroot --net --network=fakeroot sles12sp5.sif ip -o -4 addr show scope global
2: eth0    inet 10.23.0.9/16 brd 10.23.255.255 scope global eth0\       valid_lft forever preferred_lft forever
```

**Expected behavior**

- If network fakeroot should **not** be allowed for unprivileged users (even if running under `fakeroot`), then the command above should fail.
- If network fakeroot **should** be allowed for unprivileged users (when running under `fakeroot`), then we should not see this error.

**Additional context**
It could also be nice if the behavior is described in the documentation.

**Comment by dtrudg** [comment]
Thanks for the report.

This is an incorrect error message introduced in the code handling of `allow net networks`. The `fakeroot` network is explicitly allowed, and is the only network allowed, with `--fakeroot`.

https://github.com/sylabs/singularity/blob/202e98aab2ee55cafc7ec29665259bf8400965d0/internal/pkg/runtime/engine/singularity/container_linux.go#L2344

When you add it to `allow net networks` it's just bypassing the error message in the code path that is being followed in error.

This will be fixed for the next patch release.
