### ISSUE TITLE
Cannot change build environment

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [sylabs/singularity#137]
The command:
singularity pull /home/user/containers library://example

Does not change the build location

The page:
https://sylabs.io/guides/3.3/user-guide/build_env.html

Is missing the example under:
You would need to set and export the SINGULARITY_CACHEDIR environment variable before pulling the image, like so:

**Comment by dtrudg** [comment]
Hello. The linked version of the documents is for Singularity 3.3 which is not supported. Please see the docs for the current SingularityCE 3.8 at this location: https://sylabs.io/guides/3.8/user-guide/build_env.html

Any issues with documentation can be filed at https://github.com/sylabs/singularity-userdocs

When using `singularity pull` you would need to specify a full filename, not a directory. e.g. `singularity pull /home/user/containers/example.sif library://example`

If you wish to redirect the cache location then use e.g. `export SINGULARITY_CACHEDIR=/home/user/mycachedir` before running your commands.
