### ISSUE TITLE
Improve discussion of LICENSE_DEPENDENCIES.md in CONTRIBUTING.md

### ISSUE THREAD

**Issue by preminger** [sylabs/singularity#1392]
**Type of issue**
Documentation problem in `CONTRIBUTING.md`

**Description of issue**
The discussion of `LICENSE_DEPENDENCIES.md` (currently, the second half of bullet-point 13) has two problems:

- It uses the term "Any new dependency" where "Any new or updated dependency" would be clearer. (The former may be misinterpreted to mean "only wholly new dependencies" excluding, e.g., version bumps, and that would be incorrect.)
- The name of the update script has a typo: its extension should be `.sh`, not `.md` as currently given.

**Comment by dtrudg** [comment]
Closed in #1393
