### ISSUE TITLE
Unprevilged proot builds error

### ISSUE THREAD

**Issue by wjnadia** [sylabs/singularity#1443]
*Note*: We encourage questions about usage of SingularityCE to be made via the Google Group or Slack channels. Other users frequent these communities, and may already have the answer to your question!

See: https://sylabs.io/singularity#community for links.

**Type of issue**
New feature in singularity 3.11.0

**Description of issue**
Give a concise, but complete description of the issue here, with any information that might be needed to investigate, or act on it.

Hi, I attempted to build a singularity container with a definition file using unprevilged proot 5.2.0 on singularity 3.11.0, but I received an error when trying to install a package using apt package manager in the $post section. If I run conda to install a package in the $post section, the build was successful.
According to an error log, I suspect it doesn't have permission to run package manager.
On this issue, I ask for assistance.

1138% [wjnadia@glogin02 singularity_guide]$ singularity build ubuntu.sif ubuntu.def
```
INFO:    Using proot to build unprivileged. Not all builds are supported. If build fails, use --remote or --fakeroot.
INFO:    Starting build...
2023/03/09 11:55:51  info unpack layer: sha256:58289280d3c7925e901df9362a9787a557d2fdee0680e1e4251f9ae50b36cf30
INFO:    Running post scriptlet
+ apt-get update
Reading package lists... Done
E: Method gave invalid 400 URI Failure message: Could not switch saved set-user-ID
E: Method gave invalid 400 URI Failure message: Could not switch saved set-user-ID
E: Method http has died unexpectedly!
E: Sub-process http returned an error code (112)
FATAL:   While performing build: while running engine: exit status 100
```

1139% [wjnadia@glogin02 singularity_guide]$ cat ubuntu.def
```
Bootstrap: docker
From: ubuntu:18.04

%post
 apt-get update
 apt-get install -y wget git bash gcc gfortran g++ make file

%runscript
 echo "hello world from ubuntu container!"
```

**Comment by dtrudg** [comment]
Hi @wjnadia - Running `singularity build ubuntu.def` on Fedora with proot 5.3.1 I don't see the issue you have - in my case,  the `apt-get update` completes successfully. 

You might want to try adding `-o APT::Sandbox::User=root` to the `apt-get` lines, e.g....

```
apt-get -o APT::Sandbox::User=root update
```

If this works, let me know and we'll put it in the documentation.

**Comment by dtrudg** [comment]
Unfortunately it appears that there is not a trivial way around this issue. Unpriviled builds that are not able to make user of the user namespace and subuid/subgids will always have limitations.

When `openssh-client` is pulled in as a dependency you can either...

* Build as root, with `--fakeroot`, or the cloud.sylabs.io remote build service.

* Build with proot, but 'hold' the `openssh-client` package so that it is not installed as a dependency. However, this will mean any functionality dependent on it does not work.

```
From: ubuntu:20.04
 
%post
 echo 'APT::Sandbox::User "root";' > /etc/apt/apt.conf.d/no-sandbox
 apt-get update
 apt-mark hold openssh-client 
 apt-get install -y wget git bash gcc gfortran g++ make file

%runscript
 echo "hello world from ubuntu container!"
```
