### ISSUE TITLE
Add Docker labels to Singularity labels

### ISSUE THREAD

**Issue by psavery** [sylabs/singularity#146]
Hi there,

I noticed that if you build a singularity image from a docker image, the docker labels do not get added to the singularity labels.

Could these be added? We are storing some important metadata in them.

Example
=======

Dockerfile:
```Dockerfile
FROM ubuntu:20.04

LABEL label=3 \
  nested.label=True
```

Script:
```bash
docker build -t local/test .
singularity build test.simg docker-daemon://local/test:latest

docker inspect --format='{{json .Config.Labels}}' local/test
# {"label":"3","nested.label":"True"}

singularity inspect test.simg 
# org.label-schema.build-arch: amd64
# org.label-schema.build-date: Tuesday_13_July_2021_15:48:8_CDT
# org.label-schema.schema-version: 1.0
# org.label-schema.usage.singularity.deffile.bootstrap: docker-daemon
# org.label-schema.usage.singularity.deffile.from: local/test:latest
# org.label-schema.usage.singularity.version: 3.8.0
```

**Comment by dtrudg** [comment]
This is definitely reasonable, and has been requested on the hpcng side of the fork some time ago (https://github.com/hpcng/singularity/issues/3984)

We'll look into what's required here.

**Comment by dtrudg** [comment]
Working on this - will be straightforward to add for 3.9.0.

It won't be added to a 3.8.x release, as bringing in the docker labels could, in theory, alter the output of build if labels with the same names are defined in the Def file, and not forced to override the existing label.

**Comment by dtrudg** [comment]
@psavery - if you are able to give https://github.com/sylabs/singularity/pull/152 a try that would be great. It should do what you need here.

**Comment by psavery** [comment]
@dtrudg I gave the master branch a try, and it worked! Thank you very much.
