### ISSUE TITLE
"conmon source not found" during the process of building singularityCE(v3.11.1)

### ISSUE THREAD

**Issue by luwd401** [sylabs/singularity#1462]
Dear singularityCE maintainer:
I met an error during the process of building singularityCE(v3.11.1)

my system: ubuntu 22.04LTS 
`go` software has been installed (at /home/lu/software rather than at /usr/local/go) and tested successfully.
`$ sudo apt-get update`
`$ sudo apt-get install -y \`
    `build-essential` \
   ` libseccomp-dev` \
    `libglib2.0-dev` \
    `pkg-config` \
   ` squashfs-tools` \
    `cryptsetup` \
    `crun` \
    `uidmap`

`$ git clone https://github.com/sylabs/singularity.git`
`$ cd singularity`
`$ ./mconfig`

Configuring for project `singularity-ce' with languages: C, Golang
=> running pre-basechecks project specific checks ...
=> running base system checks ...
 checking: host C compiler... cc
 checking: host C++ compiler... c++
 checking: host Go compiler (at least version 1.17)... /home/lu/howard/go/bin/go
 checking: host C compiler option -Wall... yes
 checking: host C compiler option -Werror... yes
 checking: host C compiler option -Wfatal-errors... yes
 checking: host C compiler option -Wno-unknown-warning-option... yes
 checking: host C compiler option -Wstrict-prototypes... yes
 checking: host C compiler option -Wpointer-arith... yes
 checking: host C compiler option -Wbad-function-cast... yes
 checking: host C compiler option -Woverlength-strings... yes
 checking: host C compiler option -Wframe-larger-than=2047... yes
 checking: host C compiler option -Wno-sign-compare... yes
 checking: host C compiler option -Wclobbered... yes
 checking: host C compiler option -Wempty-body... yes
 checking: host C compiler option -Wmissing-parameter-type... yes
 checking: host C compiler option -Wtype-limits... yes
 checking: host C compiler option -Wunused-parameter... yes
 checking: host C compiler option -Wunused-but-set-parameter... yes
 checking: host C compiler option -Wno-discarded-qualifiers... yes
 checking: host C compiler option -Wno-incompatible-pointer-types... yes
 checking: host C compiler option -pipe... yes
 checking: host C compiler option -fmessage-length=0... yes
 checking: host C compiler option -fPIC... yes
 checking: host `ar' path... ar
 checking: host `ld' path... ld
 checking: host `ranlib' path... ranlib
 checking: host `objcopy' path... objcopy
 checking: target C compiler... cc
 checking: target C++ compiler... c++
 checking: target `ar' path... ar
 checking: target `ld' path... ld
 checking: target `ranlib' path... ranlib
 checking: target `objcopy' path... objcopy
 checking: host compiles static binaries... yes
 checking: target compiles static binaries... yes
 checking: host os type... unix
 checking: host architecture... x86_64
 checking: target architecture... x86_64
 checking: host architecture word size... 64
 checking: target architecture word size... 64
 checking: project version... 3.11.0+121-ge888f0ec5
 checking: project short version... 3.11.0+121-ge888f0ec5
=> running post-basechecks project specific checks ...
./mconfig: 16: [: 0: unexpected operator
 checking: namespace: CLONE_NEWPID... yes
 checking: namespace: CLONE_FS... yes
 checking: namespace: CLONE_NEWNS... yes
 checking: namespace: CLONE_NEWUSER... yes
 checking: namespace: CLONE_NEWIPC... yes
 checking: namespace: CLONE_NEWNET... yes
 checking: namespace: CLONE_NEWUTS... yes
 checking: namespace: CLONE_NEWCGROUP... yes
 checking: feature: NO_NEW_PRIVS... yes
 checking: feature: MS_SLAVE... yes
 checking: feature: MS_REC... yes
 checking: feature: MS_PRIVATE... yes
 checking: user capabilities... yes
 checking: header linux/securebits.h... yes
 checking: header linux/capability.h... yes
 checking: libseccomp+headers... yes
 checking: conmon source... no

conmon source not found
Unless you are building --without-conmon you must 'git clone --recurse-submodules'
or 'git submodule update --init'.

`$ git clone --recurse-submodules`
fatal: 您必须指定一个仓库来克隆。

用法：git clone [<选项>] [--] <仓库> [<路径>]

    -v, --verbose         更加详细
    -q, --quiet           更加安静
    --progress            强制显示进度报告
    --reject-shallow      不克隆浅仓库
    -n, --no-checkout     不创建一个检出
    --bare                创建一个纯仓库
    --mirror              创建一个镜像仓库（也是纯仓库）
    -l, --local           从本地仓库克隆
    --no-hardlinks        不使用本地硬链接，始终复制
    -s, --shared          设置为共享仓库
    --recurse-submodules[=<路径规格>]
                          在克隆时初始化子模组
    --recursive ...       --recurse-submodules 的别名
    -j, --jobs <n>        并发克隆的子模组的数量
    --template <模板目录>
                          模板目录将被使用
    --reference <仓库>    参考仓库
    --reference-if-able <仓库>
                          参考仓库
    --dissociate          仅在克隆时参考 --reference 指向的本地仓库
    -o, --origin <名称>   使用 <名称> 而不是 'origin' 去跟踪上游
    -b, --branch <分支>   检出 <分支> 而不是远程 HEAD
    -u, --upload-pack <路径>
                          远程 git-upload-pack 路径
    --depth <深度>        创建一个指定深度的浅克隆
    --shallow-since <时间>
                          从一个特定时间创建一个浅克隆
    --shallow-exclude <版本>
                          深化浅克隆的历史，除了特定版本
    --single-branch       只克隆一个分支、HEAD 或 --branch
    --no-tags             不要克隆任何标签，并且后续获取操作也不下载它们
    --shallow-submodules  子模组将以浅下载模式克隆
    --separate-git-dir <git目录>
                          git目录和工作区分离
    -c, --config <key=value>
                          在新仓库中设置配置信息
    --server-option <server-specific>
                          传输选项
    -4, --ipv4            只使用 IPv4 地址
    -6, --ipv6            只使用 IPv6 地址
    --filter <参数>       对象过滤
    --remote-submodules   任何克隆的子模组将使用它们的远程跟踪分支
    --sparse              初始化稀疏检出文件，只包含根目录文件

``$ make -C builddir``
make: 进入目录“/home/lu/howard/singularity/builddir”
make: *** 没有指明目标并且找不到 makefile。 停止。
make: 离开目录“/home/lu/howard/singularity/builddir”

git checkout v3.11.1
注意：正在切换到 'v3.11.1'。

您正处于分离头指针状态。您可以查看、做试验性的修改及提交，并且您可以在切换
回一个分支时，丢弃在此状态下所做的提交而不对分支造成影响。

如果您想要通过创建分支来保留在此状态下所做的提交，您可以通过在 switch 命令
中添加参数 -c 来实现（现在或稍后）。例如：

  git switch -c <新分支名>

或者撤销此操作：

  git switch -

通过将配置变量 advice.detachedHead 设置为 false 来关闭此建议

HEAD 目前位于 c3885a5b2 Merge pull request #1451 from dtrudg/prep-3.11.1

Could you give me some advice to solve the above problems? Looking forward to your reply! Good luck!

**Comment by dtrudg** [comment]
The `git clone --recurse submodules` is for a new clone. If you already have a git clone, use `git submodule update --init`
