### ISSUE TITLE
"tcp 142.251.42.241:443: i/o timeout" during the process of building singularityCE (v3.11.1)

### ISSUE THREAD

**Issue by luwd401** [sylabs/singularity#1463]
Dear singularity maintainer:
An error occurred during the process of building singularityCE:

......
cd /home/XXX/singularity/builddir
make

 GEN GO DEP /home/XXX/singularity/builddir/starter.d
go: downloading github.com/opencontainers/runtime-spec v1.1.0-rc.1
go: downloading github.com/google/uuid v1.3.0
go: downloading github.com/pkg/errors v0.9.1
go: downloading golang.org/x/sys v0.6.0
go: downloading github.com/ProtonMail/go-crypto v0.0.0-20230217124315-7d5c6f04bbb8
go: downloading github.com/sylabs/sif/v2 v2.11.0
go: downloading golang.org/x/term v0.6.0
go: downloading mvdan.cc/sh/v3 v3.6.0
go: downloading github.com/blang/semver/v4 v4.0.0
go: downloading github.com/containers/common v0.51.0
go: downloading github.com/seccomp/libseccomp-golang v0.10.0
go: downloading github.com/opencontainers/runc v1.1.4
go: downloading github.com/pelletier/go-toml/v2 v2.0.7
go: downloading github.com/containernetworking/cni v1.1.2
go: downloading github.com/containernetworking/plugins v1.2.0
go: downloading github.com/sylabs/scs-key-client v0.7.2
go: downloading github.com/opencontainers/selinux v1.11.0
../internal/pkg/runtime/engine/fakeroot/engine_linux.go:15:2: github.com/opencontainers/runtime-spec@v1.1.0-rc.1: Get "https://proxy.golang.org/github.com/opencontainers/runtime-spec/@v/v1.1.0-rc.1.zip": dial tcp 142.251.42.241:443: i/o timeout
../pkg/util/fs/lock/lock.go:13:2: golang.org/x/sys@v0.6.0: Get "https://proxy.golang.org/golang.org/x/sys/@v/v0.6.0.zip": dial tcp 142.251.42.241:443: i/o timeout
../internal/pkg/plugin/module.go:16:2: github.com/blang/semver/v4@v4.0.0: Get "https://proxy.golang.org/github.com/blang/semver/v4/@v/v4.0.0.zip": dial tcp 142.251.42.241:443: i/o timeout
../internal/pkg/plugin/sif.go:13:2: github.com/sylabs/sif/v2@v2.11.0: Get "https://proxy.golang.org/github.com/sylabs/sif/v2/@v/v2.11.0.zip": dial tcp 142.251.42.241:443: i/o timeout
../internal/pkg/util/bin/bin.go:15:2: github.com/pkg/errors@v0.9.1: Get "https://proxy.golang.org/github.com/pkg/errors/@v/v0.9.1.zip": dial tcp 142.251.42.241:443: i/o timeout
../internal/pkg/security/seccomp/seccomp_supported.go:17:2: github.com/containers/common@v0.51.0: Get "https://proxy.golang.org/github.com/containers/common/@v/v0.51.0.zip": dial tcp 142.251.42.241:443: i/o timeout
../internal/pkg/security/seccomp/seccomp_supported.go:19:2: github.com/seccomp/libseccomp-golang@v0.10.0: Get "https://proxy.golang.org/github.com/seccomp/libseccomp-golang/@v/v0.10.0.zip": dial tcp 142.251.42.241:443: i/o timeout
../internal/pkg/runtime/engine/singularity/prepare_linux.go:21:2: github.com/ProtonMail/go-crypto@v0.0.0-20230217124315-7d5c6f04bbb8: Get "https://proxy.golang.org/github.com/%21proton%21mail/go-crypto/@v/v0.0.0-20230217124315-7d5c6f04bbb8.zip": dial tcp 142.251.42.241:443: i/o timeout
../internal/pkg/runtime/engine/singularity/cleanup_host_linux.go:13:2: github.com/sylabs/sif/v2@v2.11.0: Get "https://proxy.golang.org/github.com/sylabs/sif/v2/@v/v2.11.0.zip": dial tcp 142.251.42.241:443: i/o timeout
../internal/pkg/cgroups/manager_linux.go:15:2: github.com/opencontainers/runc@v1.1.4: Get "https://proxy.golang.org/github.com/opencontainers/runc/@v/v1.1.4.zip": dial tcp 142.251.42.241:443: i/o timeout
../internal/pkg/cgroups/manager_linux.go:17:2: github.com/opencontainers/runc@v1.1.4: Get "https://proxy.golang.org/github.com/opencontainers/runc/@v/v1.1.4.zip": dial tcp 142.251.42.241:443: i/o timeout
../internal/pkg/cgroups/manager_linux.go:18:2: github.com/opencontainers/runc@v1.1.4: Get "https://proxy.golang.org/github.com/opencontainers/runc/@v/v1.1.4.zip": dial tcp 142.251.42.241:443: i/o timeout
../internal/pkg/cgroups/manager_linux.go:19:2: github.com/opencontainers/runc@v1.1.4: Get "https://proxy.golang.org/github.com/opencontainers/runc/@v/v1.1.4.zip": dial tcp 142.251.42.241:443: i/o timeout
../internal/pkg/cgroups/config_linux.go:14:2: github.com/pelletier/go-toml/v2@v2.0.7: Get "https://proxy.golang.org/github.com/pelletier/go-toml/v2/@v/v2.0.7.zip": dial tcp 142.251.42.241:443: i/o timeout
../internal/pkg/util/crypt/crypt_dev.go:18:2: github.com/google/uuid@v1.3.0: Get "https://proxy.golang.org/github.com/google/uuid/@v/v1.3.0.zip": dial tcp 142.251.42.241:443: i/o timeout
../internal/pkg/security/selinux/selinux_supported.go:10:8: github.com/opencontainers/selinux@v1.11.0: Get "https://proxy.golang.org/github.com/opencontainers/selinux/@v/v1.11.0.zip": dial tcp 142.251.42.241:443: i/o timeout
../internal/pkg/syecl/syecl.go:24:2: github.com/sylabs/sif/v2@v2.11.0: Get "https://proxy.golang.org/github.com/sylabs/sif/v2/@v/v2.11.0.zip": dial tcp 142.251.42.241:443: i/o timeout
../internal/pkg/util/shell/interpreter/interpreter.go:21:2: mvdan.cc/sh/v3@v3.6.0: Get "https://proxy.golang.org/mvdan.cc/sh/v3/@v/v3.6.0.zip": dial tcp 142.251.42.241:443: i/o timeout
../internal/pkg/util/shell/interpreter/interpreter.go:22:2: mvdan.cc/sh/v3@v3.6.0: Get "https://proxy.golang.org/mvdan.cc/sh/v3/@v/v3.6.0.zip": dial tcp 142.251.42.241:443: i/o timeout
../internal/pkg/util/shell/interpreter/interpreter.go:23:2: mvdan.cc/sh/v3@v3.6.0: Get "https://proxy.golang.org/mvdan.cc/sh/v3/@v/v3.6.0.zip": dial tcp 142.251.42.241:443: i/o timeout
../pkg/network/network_linux.go:20:2: github.com/containernetworking/cni@v1.1.2: Get "https://proxy.golang.org/github.com/containernetworking/cni/@v/v1.1.2.zip": dial tcp 142.251.42.241:443: i/o timeout
../pkg/network/network_linux.go:21:2: github.com/containernetworking/cni@v1.1.2: Get "https://proxy.golang.org/github.com/containernetworking/cni/@v/v1.1.2.zip": dial tcp 142.251.42.241:443: i/o timeout
../pkg/network/network_linux.go:22:2: github.com/containernetworking/cni@v1.1.2: Get "https://proxy.golang.org/github.com/containernetworking/cni/@v/v1.1.2.zip": dial tcp 142.251.42.241:443: i/o timeout
../pkg/network/network_linux.go:23:2: github.com/containernetworking/plugins@v1.2.0: Get "https://proxy.golang.org/github.com/containernetworking/plugins/@v/v1.2.0.zip": dial tcp 142.251.42.241:443: i/o timeout
../pkg/sypgp/sypgp.go:32:2: github.com/ProtonMail/go-crypto@v0.0.0-20230217124315-7d5c6f04bbb8: Get "https://proxy.golang.org/github.com/%21proton%21mail/go-crypto/@v/v0.0.0-20230217124315-7d5c6f04bbb8.zip": dial tcp 142.251.42.241:443: i/o timeout
../pkg/sypgp/sypgp.go:33:2: github.com/ProtonMail/go-crypto@v0.0.0-20230217124315-7d5c6f04bbb8: Get "https://proxy.golang.org/github.com/%21proton%21mail/go-crypto/@v/v0.0.0-20230217124315-7d5c6f04bbb8.zip": dial tcp 142.251.42.241:443: i/o timeout
../pkg/sypgp/keyring.go:17:2: github.com/sylabs/scs-key-client@v0.7.2: Get "https://proxy.golang.org/github.com/sylabs/scs-key-client/@v/v0.7.2.zip": dial tcp 142.251.42.241:443: i/o timeout
../internal/pkg/util/interactive/interactive.go:19:2: golang.org/x/term@v0.6.0: Get "https://proxy.golang.org/golang.org/x/term/@v/v0.6.0.zip": dial tcp 142.251.42.241:443: i/o timeout
.....
make: *** [Makefile:181：singularity] 错误 1

Due to the known reasons, all the users in China can not access the website"https://proxy.golang.org/", but can access to the website "https://goproxy.io/zh/". Could you give me the guidance on how to modify the files in the folders of singularity that I had downloaded so that I can finish the building step.

Best wishes!

**Comment by dtrudg** [comment]
Did you clone the git repository, or use a release tarball here? The release tarball vendors the dependencies, and shouldn't need to download anything - if it's incomplete, that'd be a bug.

Otherwise, at present you can modify a line in the following file, before running `./mconfig`:

```
mlocal/frags/go_common_opts.mk
21:GOPROXY := https://proxy.golang.org
```

**Comment by luwd401** [comment]
Thank you for your quick reply!

Yes, I cloned the git repository using the following command:
`git clone https://github.com/sylabs/singularity.git`

Do you mean that I modify the line of "GOPROXY := https://proxy.golang.org" to " "GOPROXY := https://goproxy.io/zh/"" in mlocal/frags/go_common_opts.mk?

**Comment by dtrudg** [comment]
> Thank you for your quick reply!
> 
> Yes, I cloned the git repository using the following command: `git clone https://github.com/sylabs/singularity.git`
> 
> Do you mean that I can modify the line of "GOPROXY := https://proxy.golang.org" to " "GOPROXY := https://goproxy.io/zh/"" in mlocal/frags/go_common_opts.mk?

Yes - you can do that, then run `./mconfig`. You might need to `rm -r builddir` if you've already run mconfig.

**Comment by luwd401** [comment]
`rm -r builddir`
modify the line of "GOPROXY := https://proxy.golang.org/" to " "GOPROXY := https://goproxy.io/"" in mlocal/frags/go_common_opts.mk, 
`./mcofig`
`cd /home/XXX/singularity/builddir`
`make`

More unexpected problems appeared:

 GEN GO DEP /home/lu/howard/singularity/builddir/starter.d
go: downloading github.com/ProtonMail/go-crypto v0.0.0-20230217124315-7d5c6f04bbb8
go: downloading github.com/opencontainers/runtime-spec v1.1.0-rc.1
go: downloading github.com/sylabs/sif/v2 v2.11.0
go: downloading golang.org/x/sys v0.6.0
go: downloading golang.org/x/term v0.6.0
go: downloading mvdan.cc/sh/v3 v3.6.0
go: downloading github.com/google/uuid v1.3.0
go: downloading github.com/opencontainers/runc v1.1.4
go: downloading github.com/pelletier/go-toml/v2 v2.0.7
go: downloading github.com/blang/semver/v4 v4.0.0
go: downloading github.com/containers/common v0.51.0
go: downloading github.com/seccomp/libseccomp-golang v0.10.0
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/containernetworking/cni v1.1.2
go: downloading github.com/containernetworking/plugins v1.2.0
go: downloading github.com/sylabs/scs-key-client v0.7.2
go: downloading golang.org/x/sync v0.1.0
go: downloading golang.org/x/crypto v0.7.0
go: downloading github.com/cyphar/filepath-securejoin v0.2.3
go: downloading github.com/moby/sys/mountinfo v0.6.2
go: downloading github.com/sirupsen/logrus v1.9.0
go: downloading github.com/coreos/go-systemd/v22 v22.5.0
go: downloading github.com/godbus/dbus/v5 v5.1.0
go: downloading github.com/opencontainers/selinux v1.11.0
go: downloading github.com/cloudflare/circl v1.1.0
go: downloading github.com/sylabs/json-resp v0.8.2
go: downloading github.com/secure-systems-lab/go-securesystemslib v0.5.0
go: downloading github.com/sigstore/sigstore v1.6.0
go: downloading github.com/coreos/go-iptables v0.6.0
go: downloading github.com/safchain/ethtool v0.2.0
go: downloading github.com/vishvananda/netlink v1.2.1-beta.2
go: downloading github.com/cilium/ebpf v0.9.1
verifying github.com/safchain/ethtool@v0.2.0: checksum mismatch
	downloaded: h1:tjsEsesUSlGdnUAAiIaEvk/YEycwk0k3Q6/q77qGpBI=
	go.sum:     h1:dILxMBqDnQfX192cCAPjZr9v2IgVXeElHPy435Z/IdE=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
 GEN GO DEP /home/lu/howard/singularity/builddir/singularity.d
go: downloading golang.org/x/text v0.8.0
go: downloading github.com/containers/image/v5 v5.24.2
go: downloading github.com/docker/go-units v0.5.0
go: downloading github.com/shopspring/decimal v1.3.1
go: downloading github.com/fatih/color v1.15.0
go: downloading github.com/spf13/cobra v1.6.1
go: downloading github.com/sylabs/scs-library-client v1.4.4
go: downloading github.com/letsencrypt/boulder v0.0.0-20221109233200-85aa52084eaf
go: downloading github.com/theupdateframework/go-tuf v0.5.2
go: downloading github.com/google/go-containerregistry v0.13.0
go: downloading github.com/mattn/go-colorable v0.1.13
go: downloading github.com/mattn/go-isatty v0.0.17
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/go-log/log v0.2.0
go: downloading github.com/sylabs/scs-build-client v0.7.7
go: downloading github.com/buger/goterm v1.0.4
go: downloading github.com/vbauerster/mpb/v8 v8.3.0
go: downloading github.com/containerd/containerd v1.7.0
go: downloading github.com/opencontainers/go-digest v1.0.0
go: downloading github.com/opencontainers/image-spec v1.1.0-rc2.0.20221005185240-3a7f492d3f1b
go: downloading oras.land/oras-go v1.2.3-0.20230221065300-6cd929aff421
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading github.com/gosimple/slug v1.13.1
go: downloading github.com/moby/term v0.0.0-20221205130635-1aeaba878587
go: downloading github.com/cloudflare/circl v1.1.0
go: downloading github.com/apex/log v1.9.0
go: downloading github.com/opencontainers/umoci v0.4.7
go: downloading github.com/acarl005/stripansi v0.0.0-20180116102854-5a71ef0e047d
go: downloading github.com/mattn/go-runewidth v0.0.14
go: downloading github.com/VividCortex/ewma v1.2.0
go: downloading github.com/gorilla/websocket v1.5.0
go: downloading github.com/titanous/rocacheck v0.0.0-20171023193734-afe73141d399
go: downloading google.golang.org/grpc v1.53.0
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading github.com/docker/cli v23.0.1+incompatible
go: downloading github.com/docker/distribution v2.8.1+incompatible
go: downloading github.com/docker/docker v23.0.1+incompatible
go: downloading github.com/docker/go-connections v0.4.0
go: downloading github.com/BurntSushi/toml v1.2.1
go: downloading github.com/container-orchestrated-devices/container-device-interface v0.5.4
go: downloading github.com/containers/storage v1.45.3
go: downloading github.com/moby/locker v1.0.1
go: downloading github.com/containers/ocicrypt v1.1.7
go: downloading github.com/vbauerster/mpb/v7 v7.5.3
go: downloading github.com/ghodss/yaml v1.0.0
go: downloading github.com/sigstore/fulcio v1.0.0
go: downloading github.com/gosimple/unidecode v1.0.1
go: downloading gopkg.in/square/go-jose.v2 v2.6.0
go: downloading google.golang.org/protobuf v1.28.1
go: downloading github.com/urfave/cli v1.22.12
go: downloading github.com/vbatts/go-mtree v0.5.0
go: downloading github.com/golang/protobuf v1.5.2
go: downloading github.com/klauspost/pgzip v1.2.6-0.20220930104621-17e8dac29df8
go: downloading github.com/rootless-containers/proto v0.1.0
go: downloading github.com/rivo/uniseg v0.4.4
go: downloading golang.org/x/net v0.8.0
go: downloading github.com/syndtr/gocapability v0.0.0-20200815063812-42c35b437635
go: downloading github.com/docker/docker-credential-helpers v0.7.0
go: downloading github.com/klauspost/compress v1.16.0
go: downloading go.opentelemetry.io/otel v1.14.0
go: downloading go.opentelemetry.io/otel/trace v1.14.0
go: downloading github.com/fsnotify/fsnotify v1.6.0
go: downloading github.com/opencontainers/runtime-tools v0.9.1-0.20221107090550-2e043c6bd626
go: downloading golang.org/x/mod v0.8.0
go: downloading sigs.k8s.io/yaml v1.3.0
go: downloading github.com/ulikunitz/xz v0.5.11
go: downloading github.com/containers/libtrust v0.0.0-20230121012942-c1716e8a8d01
go: downloading github.com/moby/patternmatcher v0.5.0
go: downloading github.com/moby/sys/sequential v0.5.0
go: downloading github.com/hashicorp/go-multierror v1.1.1
go: downloading github.com/gorilla/mux v1.8.0
go: downloading github.com/cyberphone/json-canonicalization v0.0.0-20220623050100-57a0ce2678a7
go: downloading github.com/sigstore/rekor v1.0.1
go: downloading github.com/cilium/ebpf v0.9.1
go: downloading google.golang.org/genproto v0.0.0-20230306155012-7f2fa6fef1f4
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.2
go: downloading github.com/go-logr/logr v1.2.3
go: downloading go.etcd.io/bbolt v1.3.7
go: downloading github.com/vbatts/tar-split v0.11.2
go: downloading github.com/morikuni/aec v1.0.0
go: downloading github.com/hashicorp/errwrap v1.1.0
go: downloading go.mozilla.org/pkcs7 v0.0.0-20210826202110-33d05740a352
go: downloading github.com/miekg/pkcs11 v1.1.1
go: downloading github.com/stefanberger/go-pkcs11uri v0.0.0-20201008174630-78d3cae3a980
go: downloading github.com/go-openapi/errors v0.20.3
go: downloading github.com/go-openapi/runtime v0.24.1
go: downloading github.com/go-openapi/strfmt v0.21.3
go: downloading github.com/go-openapi/swag v0.22.3
go: downloading github.com/go-openapi/validate v0.22.0
go: downloading github.com/go-logr/stdr v1.2.2
go: downloading github.com/gogo/protobuf v1.3.2
go: downloading github.com/json-iterator/go v1.1.12
go: downloading github.com/russross/blackfriday/v2 v2.1.0
go: downloading github.com/docker/go-metrics v0.0.1
go: downloading github.com/mailru/easyjson v0.7.7
go: downloading github.com/asaskevich/govalidator v0.0.0-20210307081110-f21760c49a8d
go: downloading github.com/mitchellh/mapstructure v1.5.0
go: downloading github.com/oklog/ulid v1.3.1
go: downloading go.mongodb.org/mongo-driver v1.11.1
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/modern-go/reflect2 v1.0.2
go: downloading github.com/prometheus/client_golang v1.14.0
go: downloading github.com/josharian/intern v1.0.0
go: downloading github.com/go-openapi/analysis v0.21.4
go: downloading github.com/go-openapi/jsonpointer v0.19.5
go: downloading github.com/go-openapi/loads v0.21.2
go: downloading github.com/go-openapi/spec v0.20.7
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/cespare/xxhash/v2 v2.2.0
go: downloading github.com/prometheus/client_model v0.3.0
go: downloading github.com/prometheus/common v0.37.0
go: downloading github.com/prometheus/procfs v0.8.0
go: downloading github.com/go-openapi/jsonreference v0.20.0
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.4
 GEN GO DEP /home/lu/howard/singularity/builddir/starter.d
go: downloading github.com/safchain/ethtool v0.2.0
go: downloading github.com/vishvananda/netlink v1.2.1-beta.2
/root/go/pkg/mod/github.com/containernetworking/plugins@v1.2.0/pkg/ip/link_linux.go:24:2: github.com/safchain/ethtool@v0.2.0: Get "https://goproxy.io/github.com/safchain/ethtool/@v/v0.2.0.zip": net/http: TLS handshake timeout
/root/go/pkg/mod/github.com/containernetworking/plugins@v1.2.0/pkg/ip/addr_linux.go:22:2: github.com/vishvananda/netlink@v1.2.1-beta.2: Get "https://goproxy.io/github.com/vishvananda/netlink/@v/v1.2.1-beta.2.zip": net/http: TLS handshake timeout
 GO singularity
    [+] GO_TAGS "containers_image_openpgp exclude_graphdriver_btrfs exclude_graphdriver_devicemapper sylog singularity_engine fakeroot_engine apparmor selinux seccomp"

#interrupted by me at this stage


"checksum mismatch
	downloaded: h1:tjsEsesUSlGdnUAAiIaEvk/YEycwk0k3Q6/q77qGpBI=
	go.sum:     h1:dILxMBqDnQfX192cCAPjZr9v2IgVXeElHPy435Z/IdE=" might due to the change of file "go_common_opts.mk"?

In addition, I can manually dowload ethtool v0.2.0 and netlink v1.2.1-beta.2 from the websites: https://goproxy.io/github.com/safchain/ethtool/@v/v0.2.0.zip and https://goproxy.io/github.com/vishvananda/netlink/@v/v1.2.1-beta.2.zip. Network problems can be ruled out.
So I decided to download  the singularity-ce_3.11.1-jammy_amd64.deb file, and it works well so far. The git respository may has a bug. Thank you for your help.

**Comment by dtrudg** [comment]
The checksum errors show that what is being retrieved from `goproxy.io` doesn't match what we retrieved from `proxy.golang.org` when `go mod` last created the `go.sum` file.

We can compare the gosum for the respective services...

```
09:38 am $ curl https://gosum.io/lookup/github.com/safchain/ethtool@v0.2.0
38407
github.com/safchain/ethtool v0.2.0 h1:tjsEsesUSlGdnUAAiIaEvk/YEycwk0k3Q6/q77qGpBI=
github.com/safchain/ethtool v0.2.0/go.mod h1:WkKB1DnNtvsMlDmQ50sgwowDJV/hGbJSOvJoEXs1AJQ=

09:38 am $ curl https://sum.golang.org/lookup/github.com/safchain/ethtool@v0.2.0
9572370
github.com/safchain/ethtool v0.2.0 h1:dILxMBqDnQfX192cCAPjZr9v2IgVXeElHPy435Z/IdE=
github.com/safchain/ethtool v0.2.0/go.mod h1:WkKB1DnNtvsMlDmQ50sgwowDJV/hGbJSOvJoEXs1AJQ=
```

Note that that `gosum.io`, associated with `goproxy.io` is showing a _different_ h1 hash than `sum.golang.org`, associated with `proxy.golang.org`.

This isn't something that we can fix on our side, I'm afraid. Our `go.mod / go.sum` files will always be generated against the `golang.org` services. You would have to modify the `go.mod / go.sum` files if you felt there wasn't a security issue here.

The underlying cause seems to be that the developer might have deleted/re-applied a tag on GitHub, after `proxy.golang.org` retrieved the code, but before `goproxy.io` retrieved it:

https://github.com/safchain/ethtool/issues/57
