### ISSUE TITLE
Pull hashingListSubtract() out of cdi_linux_test.go and into a pkg in util/

### ISSUE THREAD

**Issue by preminger** [sylabs/singularity#1485]
**Type of issue**
Technical debt

**Description of issue**
In the course of addressing #1394 (PR https://github.com/sylabs/singularity/pull/1459), we added a utility function `hashingListSubtract()` in internal/pkg/runtime/launcher/oci/cdi_linux_test.go:253, which subtracts the contents of one array from another, building on capacities in https://github.com/samber/lo/ but capitalizing on the hashability of the array values to do so more efficiently than the prepackaged `lo` functions do.

This is a fairly general function, though, and so in principle, it doesn't belong buried in the particular unit-test for a particular pkg, and instead should be pulled out to a Singularity-wide location (e.g. under `util`).

What's currently blocking this, however, is that the function (as well as the `lo` code it depends on) uses generics, which in turn require Go 1.18 or later, and we're currently holding off on introducing Go 1.18+ dependencies outside of the testing suites.

**Comment by dtrudg** [comment]
Free to do this now - looking through the major distributions we are focused on (EL / SUSE / Ubuntu, everyone is at least at 1.18 now via a main or community repo package).
