### ISSUE TITLE
Unable to install: cannot query module due to -mod=vendor

### ISSUE THREAD

**Issue by olgais93** [sylabs/singularity#1557]
Tried to install singularity: 
```
$ wget https://github.com/singularityware/singularity/releases/download/v3.5.3/singularity-3.5.3.tar.gz
$ tar -xzvf singularity-3.5.3.tar.gz
$ cd singularity
$ ./mconfig
$ cd builddir
$ make

```
Got this error: 
```
../internal/app/singularity/verify_ocsp.go:21:2: cannot query module due to -mod=vendor
../internal/pkg/remote/credential/login_handler.go:19:2: cannot query module due to -mod=vendor
make: *** [Makefile:162: singularity] Error 1
```
How can I overcome this?

**Comment by dtrudg** [comment]
Something very strange is happening here. You are using a URL to wget a very old version of singularity, that is not supported. In addition, it is a URL for  `singularityware/apptainer` that now redirects to `apptainer/singularity`, which is not the same as this `sylabs/singularity` project. There was a fork approximately 2 years ago.

However, the error you are seeing includes filenames from a much newer version of singularity.

To install SingularityCE, please start again, following the INSTALL.md guide, https://github.com/sylabs/singularity/blob/main/INSTALL.md

If you are genuinely trying to install a `singularityware/singularity` / `apptainer/singularity` version, then you would need to raise any issues with the apptainer project.
