### ISSUE TITLE
copying symbolic link with absolute target path from previous stage fails

### ISSUE THREAD

**Issue by jrobbin** [sylabs/singularity#159]
**Version of Singularity**
singularity-ce version 3.8.0

**Describe the bug**
In a definition file with two stages, copying a symbolic link from the first stage into the second stage fails with:
`FATAL:   While performing build: unable to copy files from stage to container fs: while copying [/tmp/build-temp-263510501/rootfs/opt/view] to /tmp/build-temp-776597343/rootfs/opt: exit status 1: /bin/cp: cannot stat '/tmp/build-temp-263510501/rootfs/opt/view': No such file or directory`

**To Reproduce**
`sudo singularity build image.sif image.def`

where image.def contains:
```shell
Bootstrap: docker
From: spack/ubuntu-bionic:latest
Stage: build

%post
  # Create the manifest file for the installation in /opt/spack-environment
  mkdir /opt/spack-environment && cd /opt/spack-environment
  cat << EOF > spack.yaml
spack:
  specs:
  - tcl
  view: /opt/view
  concretization: together
  config:
    install_tree: /opt/software
EOF

  # Install all the required software
  . /opt/spack/share/spack/setup-env.sh
  spack env activate .
  spack install --fail-fast
  spack gc -y
  spack env deactivate
  spack env activate --sh -d . >> /opt/spack-environment/environment_modifications.sh

  # Strip the binaries to reduce the size of the image
  find -L /opt/view/* -type f -exec readlink -f '{}' \; | \
    xargs file -i | \
    grep 'charset=binary' | \
    grep 'x-executable\|x-archive\|x-sharedlib' | \
    awk -F: '{print $1}' | xargs strip -s

Bootstrap: docker
From: ubuntu:18.04
Stage: final

%files from build
  /opt/spack-environment /opt
  /opt/software /opt
  /opt/view /opt
  /opt/spack-environment/environment_modifications.sh /opt/spack-environment/environment_modifications.sh

%post
  # Modify the environment without relying on sourcing shell specific files at startup
  cat /opt/spack-environment/environment_modifications.sh >> $SINGULARITY_ENVIRONMENT
```

**Expected behavior**
The image file, image.sif, should be created successfully.

**OS / Linux Distribution**
```
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Installation Method**
Followed the instructions at https://sylabs.io/guides/3.8/user-guide/quick_start.html#quick-installation-steps

**Comment by dtrudg** [comment]
Hello, a bit of history on this issue....

- Up to 3.5.3 we would follow all symlinks (cp -L behavior)
- At 3.5.3 we stopped doing that, and copied the symlink itself.
- This broke NVIDIA container maker builds, and was noted as being different to Docker, so in 3.6.0 we adopted the behavior in https://github.com/hpcng/singularity/pull/5063

Note in the Changelog for 3.6.0 as...
https://github.com/sylabs/singularity/blob/master/CHANGELOG.md#changed-defaults--behaviours-3
> %files from ... will now follow symlinks for sources that are directly specified, or directly resolved from a glob pattern. It will not follow symlinks found through directory traversal. This mirrors Docker multi-stage COPY behaviour.

What does the link you are trying to copy (`/opt/view`?) point to in this case?

If it is a link to a location that does not exist then in Singularity the error is expected, as is also the behavior from docker illustrated in this post from another project: https://github.com/GoogleContainerTools/kaniko/issues/1111#issuecomment-596015015

**Comment by jrobbin** [comment]
Hello @dtrudg , thanks for your quick response.  /opt/view points to a location that exists in the first stage:

/opt/view -> /opt/._view/xrivq7nkwrduxpzbuy663v2hfhpbsp3q

I don't know what's meant by "It will not follow symlinks found through directory traversal."  Should my case above work?

Thanks,
Josh

**Comment by dtrudg** [comment]
Hi @jrobbin, thanks for the further information.

I've reproduced just the first stage build and see the link that does resolve, so I'll look further into what's happening with the failed copy here.

**Comment by dtrudg** [comment]
This is a bug, that is the same as has hit in other runtimes, e.g. https://github.com/containers/buildah/issues/1610

**Comment by dtrudg** [comment]
@jrobbin - if you are able to take a look at https://github.com/sylabs/singularity/pull/162 , I think it should fix the issue for you.
