### ISSUE TITLE
"allow kernel squashfs = no" not blocking mount of encrypted squashfs

### ISSUE THREAD

**Issue by DrDaveD** [sylabs/singularity#1614]
In the new singularity-ce 3.12.2, I haven't tried it, but it looks like from the pull request that "allow kernel squashfs = no" will not prevent mounting an encrypted squashfs partition in a SIF file.

**Comment by dtrudg** [comment]
Hmmm, okay... this does indeed appear to be the case. Thanks.

Agreed it should block it at the point of the squashfs mount. `allow container encrypted` offers a workaround for now.
