### ISSUE TITLE
When using   singularity exec --sif-fuse -u ,why there is still a /tmp/rootfs-xxxxx dir extracted?

### ISSUE THREAD

**Issue by iamchating** [sylabs/singularity#1739]
*Note*: We encourage questions about usage of SingularityCE to be made via the Google Group or Slack channels. Other users frequent these communities, and may already have the answer to your question!

See: https://sylabs.io/singularity#community for links.

**Type of issue**
Feature Problem

**Description of issue**
I am using  singularity  3.10.5, and  try to use the new sif-fuse feature
I found that after  singularity exec --sif-fuse -u   there is still a temp dir under  /tmp/rootfs-xxxxx 
my /tmp is limited and I would like to the sif-fuse feature act just like the setuid does,  is it possible?

I am using  centos 7 with kernel 3.10.0-1160.el7.x86_64  and  singularity 3.10.5

@dtrudg  can you please to look into this problem?  Thanks

<img width="678" alt="image" src="https://github.com/sylabs/singularity/assets/7088153/35ed4e6b-5f29-4c99-8af5-35e2dbaed32b">

**Comment by dtrudg** [comment]
Hi @iamchating - first, please could I ask that you don't `@` individual people on the project in an initial issue report unless you've been in contact with them elsewhere - particularly if it is a usage question. We review issues periodically and the appropriate / available person will pick them up.

With regard to your observation:

When you use `--sif-fuse` the image is _not_ extracted into the `$TMPDIR`. However, we have to have a place on which we can mount it using squashfuse. We create an empty directory in `$TMPDIR`, which will hold the mounted SIF rootfs with squashfuse. We then run the container from there.

The container rootfs does not consume `/tmp` space.

In future we may 'hide' this from the host by performing it inside a mount namespace. However, there is no impact on disk usage.
