### ISSUE TITLE
./mconfig mlocal/checks/project-post.chk bad operator

### ISSUE THREAD

**Issue by AxVE** [sylabs/singularity#1797]
Hello !

In the v3.11.3 release .tar.gz and apparently last commit from main.

I encounter a small error while running `./mconfig`:

```
 checking: host architecture word size... 64
 checking: target architecture word size... 64
 checking: project version... 3.11.3
 checking: project short version... 3.11.3
=> running post-basechecks project specific checks ...
./mconfig: 16: [: 0: unexpected operator
 checking: namespace: CLONE_NEWPID... yes
 checking: namespace: CLONE_FS... yes
```

It seems there is a small mistake in the mlocal/checks/project-post.chk.
A small change `-eq` instead of `==` at line 16 does the trick:
```shell
if [ "$reproducible" -eq "1" ]; then
```

I can do a MR if you want.

--- 

By the way (maybe another topic/issue to do).
I'm not sure calling /bin/sh is a good practice, it can link to other shells depending of the linux installation.

On this hpc, /bin/sh links to dash of version 0.5.10.2-6 :

```bash
averdier@sandbox:~/test/singularity/singularity-ce-3.11.3$ ll /bin/sh
lrwxrwxrwx 1 root root 4 Jul 18  2019 /bin/sh -> dash
averdier@sandbox:~/test/singularity/singularity-ce-3.11.3$ dpkg -s dash
Package: dash
Essential: yes
Status: install ok installed
Priority: required
Section: shells
Installed-Size: 212
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Multi-Arch: foreign
Version: 0.5.10.2-6
Depends: debianutils (>= 2.15), dpkg (>= 1.19.1), debconf (>= 0.5) | debconf-2.0
Pre-Depends: libc6 (>= 2.14)
Description: POSIX-compliant shell
 The Debian Almquist Shell (dash) is a POSIX-compliant shell derived
 from ash.
 .
 Since it executes scripts faster than bash, and has fewer library
 dependencies (making it more robust against software or hardware
 failures), it is used as the default system shell on Debian systems.
Original-Maintainer: Andrej Shadura <andrewsh@debian.org>
Homepage: http://gondor.apana.org.au/~herbert/dash/
```

A better practice would be to call the right shell you use
`/usr/bin/bash` ?

**Comment by dtrudg** [comment]
Thanks for the report. This is definitely an error. The intention is that `mconfig` should work under a POSIX sh - not just bash.... so `#!/bin/sh` is as intended. 

If you'd like to open a PR I'd be happy to merge it, otherwise I can make the change.

**Comment by AxVE** [comment]
> [...] The intention is that `mconfig` should work under a POSIX sh - not just bash.... so `#!/bin/sh` is as intended.

That's fair :)
