### ISSUE TITLE
Revamped passwd utility interferes with groupadd and installing packages

### ISSUE THREAD

**Issue by DrDaveD** [sylabs/singularity#1812]
**Version of Singularity**

main branch, in particular pr #1597

**Describe the bug**

When attempting to import #1597 into Apptainer, we found that an e2e test that does `apt-get update && apt-get install openssh-client` in an Ubuntu 22.04 fakeroot writable-tmpfs container was failing with an error
```
groupadd: failure while writing changes to /etc/group
addgroup: `/sbin/groupadd -g 101 _ssh' returned error code 10. Exiting.
```
I reproduced it interactively and found that the groupadd function was creating a new temporary file and attempting to rename it to `/etc/group`.  That was failing with a `Device or resource busy` error, because /etc/group is a tmpfs mount after that PR.

**To Reproduce**

```
singularity shell -f --writable-tmpfs docker://ubuntu:22.04
groupadd -g 101 ssh
```

**Expected behavior**

Successful addition of a group

**Actual behavior**

Error message:
```
groupadd: failure while writing changes to /etc/group
```

**OS / Linux Distribution**

I don't think it matters, but I was using Centos 7.

**Comment by DrDaveD** [comment]
I'm sorry, I hadn't actually tried it in singularity-ce until now.  singularity-ce doesn't support --writable-tmpfs with --fakeroot. Instead, the problem can be demonstrated with
```
singularity build --sandbox ubuntu-22.04.sandbox docker://ubuntu:22.04
singularity shell -f --writable ubuntu-22.04.sandbox
groupadd -g 101 ssh
```
This pretty much parallels what happens when doing a build with --fakeroot.

**Comment by dtrudg** [comment]
Thanks for the report. We'll look into this is due course.

**Comment by dtrudg** [comment]
Also reported by a user in the SingularityCE Slack channel.
