### ISSUE TITLE
Unable to install vim on a container running on loginnode that has internet. 

### ISSUE THREAD

**Issue by Atulsingh92** [sylabs/singularity#1867]
Similar link [here](https://github.com/apptainer/singularity/issues/6380). 
I am facing the exact same problem and was hoping I could get some pointers on this, for a different version.

```
singularity --version
apptainer version 1.1.3+194-gb1761673d
```

**Comment by preminger** [comment]
Based on the output pasted above, it appears you are not running Singularity CE - the software whose repo this is - but rather, Apptainer. Issues concerning Apptainer should be reported on their repository, at: https://github.com/apptainer/apptainer
