### ISSUE TITLE
Overlay image locking after running installing some softwares through singularity run

### ISSUE THREAD

**Issue by crotoc** [sylabs/singularity#1868]
**Version of Singularity**
What version of Singularity are you using? Run:
singularity version 3.8.7-1.el7 

**Describe the bug**
I am trying to create a virtual env for my work:
1.  I create a sif that is based on ubuntu 22.04 with conda installed at /mylib/opt/miniconda3/.
2.  Then I created am overlay image named "Env.img". This image is writable.
3.  I will install many softwares in /mylib/opt/miniconda3/ using "conda install"

The problem is that if I run：

```
singularity run -e --bind /home,/nobackup --overlay Env.img BASE.sif mamba install -y -c conda-forge r-amelia
```

It successfully installed the package.

However, when I try to install another package or use "singularity shell" to get into the image using:
```
singularity shell -e  --bind /home,/nobackup --overlay SCENIC.img BASE.sif 
```

 it throws:

FATAL:   while loading overlay images: failed to open overlay image /home/chenr6/chenr6/sif_new/SCENIC.img: while locking ext3 partition from /panfs/accrepfs.vampire/nobackup/cgg/chenr6/sif_new/SCENIC.img: can't open /panfs/accrepfs.vampire/nobackup/cgg/chenr6/sif_new/SCENIC.img for writing, currently in use by another process

But if I use read-only mode to get into the image, it works:
```
singularity shell -e  --bind /home,/nobackup --overlay SCENIC.img:ro BASE.sif 
```

It seems like the installation of a software doesn't correctly cleanup the overlay image when exiting. I tried 
```
e2fsck -f SCENIC.img
```
I shows no error.

Can I have a way to cleanup the overlay after installing software using conda. Thanks!

**To Reproduce**

**Expected behavior**

**OS / Linux Distribution**
Which Linux distribution are you using?
CentOS Linux 7

```
$ cat /etc/os-release
```

**Installation Method**
Write here how you installed SingularityCE. Eg. RPM, source.
Singularity is installed along with centos 7

**Comment by dtrudg** [comment]
Hello. This project, SingularityCE, is provided by the `singularity-ce` package in EPEL. There is no 3.8.7 version of SingularityCE. The current release is 3.11.4.

You are running a version from the https://github.com/apptainer/singularity/ repository, before it was forked to https://github.com/apptainer/apptainer/ - becoming Apptainer.

Please open the issue with the Apptainer project, or if you can reproduce it with singularity-ce 3.11.4, you are welcome to re-open an issue here.
