### ISSUE TITLE
automatically select argument to `remote add` as current remote

### ISSUE THREAD

**Issue by preminger** [sylabs/singularity#1895]
When adding a remote via `singularity remote add <remote_name> <remote_uri>`, the newly-added remote should be selected as the _current_ remote by default.

A flag (`--notcurrent`) should be added to suppress this behavior if needed.

ETA: The flag should be `--not-current`

Discussion: #1639

**Comment by dtrudg** [comment]
Note that it should be `--not-current` or similar... we have been attempting to move toward consisten `-` for word separation in flags, e.g.

```
$ singularity run --nohttps docker://alpine
Flag --nohttps has been deprecated, use --no-https
```
