### ISSUE TITLE
Make error "config.h: No such file" in Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by VvsKrishna25** [sylabs/singularity#2012]
**Version of Singularity**
What version of Singularity are you using? Run:
SingularityCE 3.10.0

**Describe the bug**
While iam trying to build singularity version 3.10.0. i getting the below error with make command.

make: Entering directory '/home/amd/singularity/builddir-3.10.0'
 GO cmd/starter/c/starter
# command-line-arguments
../cmd/starter/main_linux.go:9:11: fatal error: config.h: No such file or directory
    9 | // #include <config.h>
      |           ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:369: cmd/starter/c/starter] Error 1

**To Reproduce**
git clone --recurse-submodules https://github.com/sylabs/singularity.git
cd singularity
git checkout --recurse-submodules v3.10.0
./mconfig -p /opt/singularity-3.10.0 -b ./builddir-3.10.0
cd $HOME/singularity/builddir-3.10.0
make

**Expected behavior**
Expected to run make and make install sucessfuly to build singularity from source

**OS / Linux Distribution**
Which Linux distribution are you using?
22.04.2 LTS (Jammy Jellyfish)

**Installation Method**
i have been trying to installing from the source.

**Comment by dtrudg** [comment]
Are you able to reproduce following the installation instructions for the current release (3.11.4)?

If so, does the error only occur when you specify a custom builddir - or always?

Another thing to note - if you checkout a different version than you have previously built in the same directory, then you may need to run a `make clean` or `git clean -fdx` to ensure the git tree is consistent for the new version.

**Comment by VvsKrishna25** [comment]
Hi @dtrudg ,  Yes, I'm able to reproduce the same error following installation instruction for the current release (3.11.4) also . 
and this error is reproducible with custom builddir only.

**Comment by dtrudg** [comment]
@VvsKrishna25 - thanks, I'll look into what's happening with the custom build dir and we'll try to ensure it's fixed befored the 4.0.0 release in a couple of weeks.
