### ISSUE TITLE
Seccomp headers required message

### ISSUE THREAD

**Issue by ericcrandall** [sylabs/singularity#2031]
**Version of Singularity**
What version of Singularity are you using? Run:

3.11.3

**Describe the bug**

When trying to install from source (./mconfig) , I get

"seccomp headers are required to build Singularity with seccomp support."

but seccomp is installed:

```
apt list libseccom*
Listing... Done
libseccomp-dev/jammy,now 2.5.3-2ubuntu2 amd64 [installed]
libseccomp2/jammy,now 2.5.3-2ubuntu2 amd64 [installed,automatic]
```

Doing this on Ubuntu 22.04.2

**Comment by dtrudg** [comment]
Hello @ericcrandall  - this is a bit of an odd one, since our CI test runs build on Ubuntu 22.04, and we haven't ever seen this error.

What's the output of:

```
$ pkg-config --print-provides --print-variables libseccomp

$ export seccomp_iflags=`pkg-config --cflags-only-I libseccomp || true`

$ printf "#include <seccomp.h>\nint main() { seccomp_syscall_resolve_name(\"read\"); }" | \
  gcc $seccomp_iflags -x c -o /dev/null - -lseccomp
```

... on this system? These lines are trying to find the seccomp pkg-config, and then compile a trivial test program to make sure the headers are available and usable.

**Comment by ericcrandall** [comment]
Hmmm…. Perhaps an issue with our libsecomp installation then…. Any advice is welcome!

```
$ pkg-config --print-provides --print-variables libseccomp
Ignoring incompatible output option "--print-variables"
libseccomp = 2.5.3
$ export seccomp_iflags=`pkg-config --cflags-only-I libseccomp || true`
$ printf "#include <seccomp.h>\nint main() { seccomp_syscall_resolve_name(\"read\"); }" | \
  gcc $seccomp_iflags -x c -o /dev/null - -lseccomp
<stdin>:1:10: fatal error: seccomp.h: No such file or directory
compilation terminated.
```

**Comment by dtrudg** [comment]
Looks like an issue... yes. Do you set `CFLAGS` or anything in your environment?

Are you inside conda or any other kind of virtual environment?
