### ISSUE TITLE
oci: investigate alternate approach for squashfs FUSE mount fail on SLES12

### ISSUE THREAD

**Issue by dtrudg** [sylabs/singularity#2059]
**Version of Singularity**

main

**Describe the bug**

On SLES 12, almost every OCI related test is failing, due to an issue that presents as:

```
FATAL:   while mounting squashfs layer: failed to mount: exit status 
```

e.g.

```
    === NAME  TestE2E/PAR/SECURITY/ociCapabilities/DefaultUser/OCIUser
        oci.go:148:
            "/usr/bin/singularity exec --oci oci-sif:/tmp/stest.2514525079/oci-sif.sif grep ^Cap...: /proc/self/status" output:
            ERROR:   While removing temporary bundle: failed to delete config.json file: remove /usr/com/singularity/mnt/session/oci-bundle4151792351/config.json: no such file or directory
            FATAL:   while mounting squashfs layer: failed to mount: exit status 1
  
        oci.go:148: got 255 as exit code and was expecting 0: exit status 255
            waiting for command "/usr/bin/singularity exec --oci oci-sif:/tmp/stest.2514525079/oci-sif.sif grep ^Cap...: /proc/self/status"
            github.com/sylabs/singularity/v4/e2e/internal/e2e.TestEnv.RunSingularity.func1
                    github.com/sylabs/singularity/v4/e2e/internal/e2e/singularitycmd.go:673
            testing.tRunner
                    testing/testing.go:1595
            runtime.goexit
                    runtime/asm_amd64.s:1650
```

**Comment by dtrudg** [comment]
@preminger - would you be able to try and replicate this on a SLES12 instance in AWS, and do as much digging into it as you can? There's not an easy way to get access to a dev version of SLES12 for local use.

I'm not going to let this block the RC, as SLES12 is not particularly commonly used, and things are passing on SLES15

**Comment by preminger** [comment]
After implementing #2105, I was able to see that the underlying cause of this failure was that the execution of `squashfuse_ll` was failing with a message that reads: `fusermount: mount failed: Operation not permitted`

Working off of that, I was able to create a replication of the same failure without involving singularity at all. Note the difference between the behavior inside the namespace and outside of it:

```
/tmp/playground> sudo unshare -rm /bin/bash

/tmp/playground # id
uid=0(root) gid=0(root) groups=0(root)
/tmp/playground # mount -t tmpfs tmpfs -o mode=1777,size=64m,nodev ./mntpoint
/tmp/playground # mkdir -p ./mntpoint/ob/rootfs
/tmp/playground # /usr/local/libexec/singularity/bin/squashfuse_ll -o ro,offset=32176 /tmp/stest.4291112640/oci-sif.sif ./mntpoint/ob/rootfs
fusermount: mount failed: Operation not permitted
/tmp/playground # exit

/tmp/playground> sudo mount -t tmpfs tmpfs -o mode=1777,size=64m,nodev ./mntpoint
/tmp/playground> sudo mkdir -p ./mntpoint/ob/rootfs
/tmp/playground> sudo /usr/local/libexec/singularity/bin/squashfuse_ll -o ro,offset=32176 /tmp/stest.4291112640/oci-sif.sif ./mntpoint/ob/rootfs
/tmp/playground> sudo ls ./mntpoint/ob/rootfs
bin  dev  etc  home  lib  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
/tmp/playground>
```

NOTE: The kernel version in this SLES12 environment is 4.12.14-122.147

Finally - for what it's worth - I played around with flags to `unshare` going from the minimal `unshare -rm` you see above, all the way to `unshare -imnuUCr`, with no difference in the relevant behavior inside the namespace.

**Comment by dtrudg** [comment]
I'm going to re-open this one... just in case there is some time to investigate if there's a different approach that can be used... or if there's system-wide FUSE configuration needed on SLES12.

Have taken off the release blocker label though. If we can't support SLES12 for this flow then we won't, and will need to document.

It should be the case that the flow in #2095 offers a solution, regardless.

**Comment by dtrudg** [comment]
Closing - user namespace FUSE is not supported on the kernel that SLES12 ships with. It has not been backported as in other LTS distros with older kernels.

The fall-back to extraction to a directory based bundle, now implemented, is the best we can do.
