### ISSUE TITLE
test / correct build on 32-bit platform

### ISSUE THREAD

**Issue by dtrudg** [sylabs/singularity#2096]
**Type of issue**

cross-platform support

**Description of issue**

Check that the build completes on a 32-bit platform. This is to try and:

* Avoid issues for any distro packaging for 32-bit platforms.
* Ensure SingularityCE 4.0.0 can be built and run on raspberry Pi default OS.

**Comment by preminger** [comment]
Built from 4.0.0-rc.1 sources on Raspberry Pi OS on both `armv7l` and `i686` 32-bit architectures, and ran basic sanity-checks (in both native- and OCI-mode) on each.
