### ISSUE TITLE
Unnecessary fusermount requirement in --oci mode in 4.0.0-rc.1-1

### ISSUE THREAD

**Issue by DrDaveD** [sylabs/singularity#2100]
In singularity-ce 4.0.0-rc.1-1, if I remove /usr/bin/fusermount and /usr/bin/fusermount3 there are errors about missing fusermount:
```
$ singularity exec --oci centos7.oci-sif bash
ERROR:   Couldn't cleanup bundle: 'fuse-overlayfs' must be used for this overlay specification, and this also requires 'fusermount' to be installed: exec: "fusermount": executable file not found in $PATH
FATAL:   'fuse-overlayfs' must be used for this overlay specification, and this also requires 'fusermount' to be installed: exec: "fusermount": executable file not found in $PATH
```
But if I then make /usr/bin/fusermount be an empty executable file it runs OK, so apparently it is not really needed.

This is on CentOS7 installed from https://github.com/sylabs/singularity/releases/download/v4.0.0-rc.1/singularity-ce-4.0.0.rc.1-1.el7.x86_64.rpm.

**Comment by DrDaveD** [comment]
Oh but according to `singularity -d` fusermount3 is being used for unmount.  That shouldn't be necessary.

**Comment by dtrudg** [comment]
See also - https://github.com/containers/storage/commit/82fd61f6701d09648b459e42e74378670bd4361e

**Comment by DrDaveD** [comment]
Thanks for the link, that's good to know.

How can fusermount be invoked safely outside of a namespace?  Might any of the commands that use fusermount be used from a batch job?  If there are then a job shut down with kill -9 would leave a mess.

**Comment by dtrudg** [comment]
Anyway - the fuse[rmount[3]] requirement is probably moot for unpriv SingularityCE or Apptainer.

The RPM of fuse-overlayfs depends on fuse3 / fuse (https://almalinux.pkgs.org/9/almalinux-appstream-x86_64/fuse-overlayfs-1.10-2.el9.x86_64.rpm.html)

The Deb of fuse-overlayfs depends on fuse3 / fuse (https://packages.debian.org/bookworm/fuse-overlayfs)

So it'd be a very unusual system that didn't have it.

**Comment by DrDaveD** [comment]
> With regards to batch jobs in general, I suspect / hope that most sites would be using a cgroup based process tracking (e.g. https://slurm.schedmd.com/cgroups.html#proctrack in Slurm). In that case the scheduler is aware of every process in the job's cgroup and can kill them all.

Right but it's not an issue of killing the process, it's the that the mount point is left behind with `Transport endpoint not connected`.

**Comment by DrDaveD** [comment]
> The RPM of fuse-overlayfs depends on fuse3 / fuse (https://almalinux.pkgs.org/9/almalinux-appstream-x86_64/fuse-overlayfs-1.10-2.el9.x86_64.rpm.html)
... 
> So it'd be a very unusual system that didn't have it.

CentOS7 doesn't have that requirement (https://rpmfind.net/linux/RPM/centos/extras/7.9.2009/x86_64/Packages/fuse-overlayfs-0.7.2-6.el7_8.x86_64.html).  Alma8 does in addition to the alma9 you linked, which I think is unfortunate.
