### ISSUE TITLE
when using --tokenfile option of remote login I still get a prompt to enter password

### ISSUE THREAD

**Issue by myoung3** [sylabs/singularity#211]
**Version of Singularity**
3.7

**Describe the bug**
when using `git remote login` on an oras registry and specifying both username and tokenfile, there is still an interactive prompt asking for a password: 

**To Reproduce**
`singularity remote login --username <username> --tokenfile tokenfile.txt  oras://ghcr.io`
this will prompt with the following:
`Password (or token when username is empty):`

**Expected behavior**
specification of a username and tokenfile shouldn't prompt for a password/token!

**OS / Linux Distribution**
Which Linux distribution are you using?
```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
```

**Installation Method**
don't know. done by IT

**Additional context**
if i don't specify a username i get an error:

```
singularity remote login --tokenfile tokenfile.txt  oras://ghcr.io
FATAL:   while login to oras://ghcr.io: Docker/OCI registry requires a username
```

**Comment by dtrudg** [comment]
The `--tokenfile` option was originally added for providing the auth token for a Sylabs Cloud / Singularity Enterprise login via a file. It looks like when the OCI (docker/oras) login was added under `remote login` the code for that doesn't consider the `--tokenfile` at all. The code needs to at minimum say it's not supported.

The Docker/OCI login does need a username and password. A token alone wouldn't be enough. That bit is correct. `remote login` is unfortunately used for auth against some things that require a username, and some that don't... so it's confusing.

The way that CSP registry services work, they usually provide their own tool to configure docker, i.e. the `az acr login` etc. Under the hood these will set the username expected by the service for a token login. For ACR with a normal individual identity and a token you need to be:

> passing 00000000-0000-0000-0000-000000000000 as the username and using the access token as password

Note that the username is different for other types of identities (e.g. if you create a service principal, for CI or an application, with a long-lived credential).

This is all detailed at: https://docs.microsoft.com/en-us/azure/container-registry/container-registry-authentication?tabs=azure-cli#az-acr-login-with---expose-token

Singularity's `remote login` really needs to all get rewritten for 4.0 as it's a bit of a mess to understand. I'll do my best to add some non-breaking changes to tidy it a little, and make some docs updates for now.

**Comment by dtrudg** [comment]
@myoung3 - #217 gives an explicit error for `--tokenfile` on an OCI registry login to make it clear it is not supported.

The PR also tries to clarify the CLI `--help` docs w.r.t. what a remote endpoint is, how to deal with them vs OCI credentials.

I will create an issue in the userdocs repository for the other portion of documentation improvements there.
