### ISSUE TITLE
Should Zenodo auto-populate releases?

### ISSUE THREAD

**Issue by tri-adam** [sylabs/singularity#2119]
The `README` includes a Zenodo "all-versions" DOI, but when I click on the [link](https://doi.org/10.5281/zenodo.5564905), the most recent version populated is v3.8.3.

My understanding is that Zenodo should auto-populate based on the releases tab, but it doesn't look like that is functioning correctly?

**Comment by dtrudg** [comment]
This has been on-and-off working throughout the history of its use. We still have a web hook in place, but it's not firing. Will have to look into it.
