### ISSUE TITLE
Replace automated docker commands with singularity commands on github packages 

### ISSUE THREAD

**Issue by myoung3** [sylabs/singularity#213]
This may or may not be better solved on github's end, but you may have better success in figuring out the best way to address this.

**Is your feature request related to a problem? Please describe.**

This package contains a .sif image, but github automatically displays docker command which obviously don't work.
https://github.com/kaufman-lab/build_containers/pkgs/container/geospatial_plus
![dockercommands](https://user-images.githubusercontent.com/2517171/128221732-b41984db-174a-4aec-b9bd-d929a9a3368e.png)

At the very least, it would be good if we could turn these off (there is no option to turn these off under package settings), but ideally github would detect the image type and display singularity commands.

**Describe the solution you'd like**
I'm not really sure what the solution here because I don't understand whether this is happening for all images stored on ghcr, or only because some sort of metadata is absent from the sif image and the default is to assume a docker image. Again, this is more github's problem than sylab's, but I'm posting it here since you'll have better luck coordinating a solution with github.

**Comment by dtrudg** [comment]
This isn't something that we are able to really influence. GitHub would need to recognize the null config of an ORAS push and choose not to display this information.

I'm aware that some other projects may try and set some kind of config, but it is the main documented oras approach to push a null config - https://oras.land/cli/1_pushing/
