### ISSUE TITLE
No progress bars in push/pull flows via go-containerregistry

### ISSUE THREAD

**Issue by dtrudg** [sylabs/singularity#2212]
In 4.0, some flows interacting with OCI registries now use go-containerregistry. This does not implement progress bars by default, and therefore these flows do not display download / upload progress bars.

We should ensure that progress bars are wired up to:

* ORAS push/pull - there have never been progress bars for this, even with the prior oras-go code, but there should be.
* Library OCI-SIF push/pull - I believe that lack of progress bars is a regression versus the native library API push/pull.

**Comment by preminger** [comment]
Looked into this a little bit, and here's what I found:

The `go-containerregistry` project appears to have implemented the necessary APIs to facilitate progress bars _only_ in the `v1/tarball` part of the code. See:

- https://github.com/google/go-containerregistry/issues/670#issuecomment-755247843
- https://github.com/google/go-containerregistry/pull/675

Our code in internal/pkg/client/oras/oras.go and internal/pkg/client/ocisif/ocisif.go, however, uses the `v1/layout` part of `go-containerregistry`, for which no such APIs have been implemented at this time.

**Comment by preminger** [comment]
Had a look at the "progress" hooks for `v1/remote` and, unless I'm missing something, they are only implemented for _writing_ images, not for reading them. See: https://github.com/search?q=repo:google/go-containerregistry+progress+path:v1&type=code

Next attempt will be to see if we can somehow hook into the HttpTransport part (`WithTransport` option) with a custom one that's hooked up to our progress bar.

**Comment by preminger** [comment]
> Next attempt will be to see if we can somehow hook into the HttpTransport part (`WithTransport` option) with a custom one that's hooked up to our progress bar.

This is indeed possible, so I have started work implementing this approach: #2252
