### ISSUE TITLE
Add more helpful error message when encounter rpm macro issue when building with YUM agent.

### ISSUE THREAD

**Issue by prod-feng** [sylabs/singularity#2237]
**Is your feature request related to a problem? Please describe.**
When build image using YUM agent, if a rpm macro is not set, it will fail, but only output very brief and useless error message.

**Describe the solution you'd like**
singularity-ce version 4.0.0, yum, CentOS 7, 3.10.0-1160.76.1.el7.x86_64, RPM version 4.11.3

```
singularity  build --fakeroot centos-base.sif base.def
INFO:    Starting build...
FATAL:   While performing build: conveyor failed to get: while checking rpm path: macro is not defined
```

Turned out that it is because %{_db_backend} is not set. After set it, the build worked fine.

It will be nice to add useful error message for users to understand the really issue quickly. I suggest to modify the file a little:

"internal/pkg/build/sources/conveyorPacker_yum.go",

```
        rpmDBBackend, err := rpm.GetMacro("_db_backend")
        if err != nil {
                return err
        }              
```

to something like:

```

        rpmDBBackend, err := rpm.GetMacro("_db_backend")
        if err != nil {
                return err+": _db_backend is not set!"
        }              

```

**Describe alternatives you've considered**

**Additional context**
Please see here https://github.com/prod-feng/Singularity-build-yum-agent

**Comment by dtrudg** [comment]
Noting there is a related fix on Apptainer - https://github.com/apptainer/apptainer/pull/1655

The macro handling changes originated on the SingularityCE side of the fork... I need to go and check whether we should completely ignore as Apptainer does, or if we should handle it differently.

**Comment by dtrudg** [comment]
The change in the apptainer fix seems appropriate, but will implement independently with slightly different code.
