### ISSUE TITLE
Image entrypoint is not honored in OCI mode

### ISSUE THREAD

**Issue by emi80** [sylabs/singularity#2290]
**Version of Singularity**
What version of Singularity are you using? Run:

```
$ singularity --version
singularity-ce version 4.0.1-jammy
```

**Describe the bug**

While testing https://github.com/nextflow-io/nextflow/pull/4440 we found that Singularity OCI mode does not honor the entrypoint defined in the image (e.g. https://github.com/mamba-org/micromamba-docker/blob/main/Dockerfile#L62)

**To Reproduce**
```
❯ singularity exec --oci docker://mambaorg/micromamba:1.5.1 env | grep PATH
INFO:    Using cached OCI-SIF image
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LD_LIBRARY_PATH=/.singularity.d/libs

❯ docker run --rm -ti mambaorg/micromamba:1.5.1 env | grep PATH
PATH=/opt/conda/bin:/opt/conda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

**Expected behavior**
```
❯ singularity exec --oci docker://mambaorg/micromamba:1.5.1 env | grep PATH
INFO:    Using cached OCI-SIF image
PATH=/opt/conda/bin:/opt/conda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LD_LIBRARY_PATH=/.singularity.d/libs
```

**OS / Linux Distribution**
Which Linux distribution are you using?
```
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Installation Method**
SingularityCE has been installed with the released deb package for Ubuntu 22.04.

**Comment by dtrudg** [comment]
Hi @emi80 - I didn't notice on the other issue that you were using `singularity exec`.

This behaviour isn't a bug, or unexpected. Just like `docker exec`,  `singularity exec` won't use an `ENTRYPOINT` or `CMD`. It runs only the command specified.

If you need `CMD` / `ENTRYPOINT` handling then please use `singularity run`.

```
09:58 am $ singularity run --oci docker://mambaorg/micromamba:1.5.1 env | grep PATH
INFO:    Using cached OCI-SIF image
LD_LIBRARY_PATH=/.singularity.d/libs
PATH=/opt/conda/bin:/opt/conda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

**Comment by emi80** [comment]
Thanks Dave! Nextflow uses `exec` by default for Singualrity images. I did not think about that either... 😞 

We'll then deal with this at the level of Nextflow.

Cheers!
