### ISSUE TITLE
add support for cross-arch builds with --oci / buildkit

### ISSUE THREAD

**Issue by preminger** [sylabs/singularity#2307]
Given that `build --oci` uses [buildkit](https://github.com/moby/buildkit) to build OCI-SIF images from Dockerfiles, it should be possible to use buildkit's off-the-shelf support for cross-architecture builds to build images in non-native architectures.

**Comment by dtrudg** [comment]
This is actually working, and is in the changelog.

```
$ singularity build --oci --arch ppc64le ppc64le.oci.sif Dockerfile 
```
