### ISSUE TITLE
Dockerfile Single Quotes Bug

### ISSUE THREAD

**Issue by matthewparkinsondes** [sylabs/singularity#233]
Am receiving an error running a fairly simple Docker image with SingularityCE 3.8.1.

Dockerfile is shown below.
```
FROM busybox:latest
CMD echo 'Test run'
```
`docker build -t vamattparkinson/test .`
`docker push vamattparkinson/test`

The resulting Docker image has been pushed to Docker Hub and is publicly available.

`docker run vamattparkinson/test`
`singularity run docker://vamattparkinson/test`
```
"run\"": executable file not found in $PATH
/.singularity.d/runscript: line 3: run": not found
```
and the following Dockerfile variation
```
FROM busybox:latest
CMD echo 'Test build at DES.'
```
produces this error (after building a Docker image and running with Singularity)
```
"build": executable file not found in $PATH
/.singularity.d/runscript: line 3: build: not found
```
Looks to relate to an issue with Singularity parsing the single quotes in the CMD line from the original Dockerfile.

Is anyone else able to reproduce this bug?

**Comment by dtrudg** [comment]
Hi @matthewparkinsondes @pontus 

Please see https://github.com/sylabs/singularity/pull/252 which should be a fix for this...

```
$ singularity run docker://vamattparkinson/test
INFO:    Using cached SIF image
Test run
```

(Noting this is the same issue as https://github.com/hpcng/singularity/issues/6128 on the hpcng side of the fork)
