### ISSUE TITLE
Any way to use image file in --bind ?

### ISSUE THREAD

**Issue by karlestira** [sylabs/singularity#2412]
**Describe the solution you'd like**
A feature like: 

--bind-img /test.img:/test

test.img is a image file contains a file system, and will be mount at /test in container.

**Comment by dtrudg** [comment]
As this has been closed, I presume you found the answer?

If not, see https://docs.sylabs.io/guides/4.0/user-guide/bind_paths_and_mounts.html#image-mounts

**Comment by karlestira** [comment]
> As this has been closed, I presume you found the answer?
> 
> If not, see https://docs.sylabs.io/guides/4.0/user-guide/bind_paths_and_mounts.html#image-mounts

Very excellent, this is much better then my solution(using fuseiso). Thank you very much!
