### ISSUE TITLE
`singularity run` drops double quotes from arguments

### ISSUE THREAD

**Issue by klmr** [sylabs/singularity#2422]
**Version of Singularity**

SingularityPRO version 3.9-8.2022102612.el8

(Unfortunately I cannot test a newer version, but I also couldn’t find any related issue so I believe this hasn’t been reported yet, although it is similar to #233.)

**Describe the bug**

When passing arguments *containing* double quote characters to `singularity run`, the double quotes are dropped. The same is  not true for single quotes.

**To Reproduce**

Run

```sh
singularity run docker://busybox:latest echo '"hello"' "'world'"
```

Output is

> ```
> hello 'world'                                                                                              │
> ```

**Expected behavior**

Output should be

> ```
> "hello" 'world'
> ```

**OS / Linux Distribution**

```
NAME="Red Hat Enterprise Linux"
VERSION="8.6 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.6 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.6"
```

**Installation Method**

unknown (installation on shared cluster, on which I am a user)

**Additional context**

To my (inexperienced) eyes, this seems suspiciously similar to #233, but that bug is already fixed in the version I am running (and at any rate the PR #252 that fixes it only seems to touch the handling of the `CMD` and `ENTRYPOINT` Dockerfile instructions).

**Comment by dtrudg** [comment]
This behaviour is documented in our user guide - https://docs.sylabs.io/guides/4.0/user-guide/singularity_and_docker.html#argument-handling

The evaluation of shell arguments (which causes the dropped `"`) is not considered a bug as this is historic Singularity behaviour, which has always differed from e.g. Docker. As users of existing containers may depend on this behaviour in some circumstances, it is not possible to change the default.

However, the `--no-eval` flag was added in version 3.10.0, and is included in Docker `--compat` compatibility mode. This does prevent evaluation of the arguments:

```
09:25 am $ singularity run docker://busybox:latest echo '"hello"' "'world'"
INFO:    Using cached SIF image
hello 'world'

dtrudg-sylabs@mini:~
09:25 am $ singularity run --no-eval docker://busybox:latest echo '"hello"' "'world'"
INFO:    Using cached SIF image
"hello" 'world'
```

This is noted in the Changelog for version 3.10.0

> * New action flag --no-eval which:
>     * Prevents shell evaluation of SINGULARITYENV_ / --env / --env-file environment variables as they are injected in the container, to match OCI behavior. Applies to all containers.
>     * Prevents shell evaluation of the values of CMD / ENTRYPOINT and command line arguments for containers run or built directly from an OCI/Docker source. Applies to newly built containers only, use singularity inspect to check version that container was built with.

You will need to upgrade your Singularity installation to allow use of `--no-eval`.

**Comment by klmr** [comment]
Thanks, I’ve forwarded the information to our internal support team.

For reference, for now I am attempting to quote the arguments using the following code inside a shell script that wraps the container (note that using `printf %q` does *not* work, since its output uses single quotes, which *are* forwarded correctly by `singularity run`, leading to double-quoting) — this seems to work, but I am not confident that it is correct in every case:

```sh
#!/bin/bash

quote_arg() {
    local arg=$1
    arg=${arg//\"/\\\"}
    arg=${arg//$/\\$}
    printf %s "$arg"
}

quoted_args=''
for arg; do
    quoted_args="${quoted_args:+$quoted_args }$(quote_arg "$arg")"
done

# `$quoted_args` are intentionally unquoted!
# shellcheck disable=SC2086
singularity run docker://busybox:latest echo $quoted_args
```
