### ISSUE TITLE
%file does not copy files into container.

### ISSUE THREAD

**Issue by Heng-Zhou** [sylabs/singularity#2483]
**Version of Singularity**

```
Host 1: singularity-ce version 4.0.2-jammy
Host 2: singularity-ce version 4.0.2-dirty
```

**Describe the bug**
The [document of %files](https://docs.sylabs.io/guides/4.0/user-guide/definition_files.html#files) says

> The %files section allows you to copy files into the container ...

But it does not work the way the doc describes and I expect -- I specified the source and destination, but the copy did not occur, so I think it is a bug.

Specifically, I wanna build a container on Host 1 where there is a file I wish to copy into the container. Then I will run the container on Host 2 where this file does not exist. My understanding is that if the file can be copied into the container, I should be able to see this file in the container and then use this file when I am running the container on Host 2, even if Host 2 does not actually have this file. I carefully read the doc and try my best to understand it, but the %files scriptlet does not copy the file into the container.

**To Reproduce**
The %files section is 
```
%files
   /home/my_username/.vnc/passwd /hpc/another_username/.vnc/passwd
```
My home directory in Host 1 is `/home/my_username`. The file I want to copy into container is `.vnc/passwd` under my home directory in Host 1. My home directory in Host 2 which is a node in an HPC is `/hpc/another_username`, and the root directory `/` in container corresponds to root directory `/` of the Host 2.

After building on Host 1, copy the container from Host 1 to Host 2.

**Expected behavior**
If I shell into the container on Host 2, the `.vnc/passwd` file should be seen under `/hpc/another_username` directory. But there is no file `/hpc/another_username/.vnc/passwd` in the container.

**OS / Linux Distribution**
```
Host 1:
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

Host 2:
NAME="Red Hat Enterprise Linux"
VERSION="8.8 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.8 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.8
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.8"
BLUEBANQUISE_IMAGE_NAME="login_rhel88"
BLUEBANQUISE_IMAGE_KERNEL="vmlinuz-4.18.0-477.27.1.el8_8.x86_64"
BLUEBANQUISE_IMAGE_DATE="2023-10-19"
```

**Installation Method**
On Host 1, I go to https://github.com/sylabs/singularity/releases, download `singularity-ce_4.0.2-jammy_amd64.deb` and install using `sudo dpkg -i` command.

On Host 2, I don't know for sure because that's out of my control. But `singularity buildcfg` returns:
```
PACKAGE_NAME=singularity-ce
PACKAGE_VERSION=4.0.2-dirty
BUILDDIR=/dev/shm/kel/versions/singularity-4.0.2/go/src/github.com/sylabs/singularity/builddir
... ...

```

**Additional context**
N/A

**Comment by dtrudg** [comment]
Hi - I'm afraid that this isn't a bug.

The `%files` line does copy the file into the container at `/hpc/another_username/.vnc/passwd`.

However, when you run the container on the second system, your home directory at `/hpc/another_username` is being bind mounted into the container. This will hide anything in the container at that path. You will only see the files that are bind mounted in from the host.

You might want to try `--no-mount home,cwd` to prevent this. However, your files from the host home directory will not be available in the container then.

If you need the VNC secret to be present in the container, then I would advise:

* copying it with `%files` to a location that is not inside a home directory path
* running `vnserver` / `Xvnc` with the flag `-rfbauth <path to password file>`

In general, avoid placing anything in a container at a home directory path. This causes numerous issues when sharing containers, or working between systems. We do mention this in the documentation, but it's in the Docker compatibility section:

https://docs.sylabs.io/guides/latest/user-guide/singularity_and_docker.html#best-practices-for-docker-singularityce-compatibility

> Software inside another user’s home directory, e.g. /home/myapp, may be obscured by SingularityCE’s automatic mounts onto /home.

> Install software into system-wide locations in the container, such as under /usr or /opt to avoid these issues.
