### ISSUE TITLE
Unable to find executable with singularity exec --env-file

### ISSUE THREAD

**Issue by ethanluoyc** [sylabs/singularity#2634]
**Version of Singularity**
What version of Singularity are you using? Run:

```
singularity-ce version 3.11.4-focal
```

**Describe the bug**
When I try to execute and executable that was mounted from the host and when I try to use --env-file. Singularity generates weird stat errors.

**To Reproduce**
```sh
#!/bin/sh
WORKDIR="$(mktemp -d)"
# mkdir -p $LXM_WORKDIR
echo >& 2 "DEBUG[$(basename "$0")] Working directory: $WORKDIR"
cleanup() {
  echo >& 2 "DEBUG[$(basename "$0")] Cleaning up $WORKDIR"
  rm -rf "$WORKDIR"
}
trap cleanup EXIT
echo "JOB_ID='1'" > $WORKDIR/.env

cat $WORKDIR/.env
echo '#!/usr/bin/env python3' >> $WORKDIR/main.py
echo 'print(1)' >> $WORKDIR/main.py
chmod u+x $WORKDIR/main.py

# This works
singularity exec --bind=$WORKDIR:/var/task  \
  --containall \
  --pwd=/var/task docker://python:3.10 ./main.py

# this fails
singularity exec --env-file=$WORKDIR/.env --bind=$WORKDIR:/var/task  \
  --containall \
  --pwd=/var/task docker://python:3.10 ./main.py

```

**Expected behavior**
The first singularity exec works fine. However when I add the `--env-file` flag is says
```
FATAL:   stat /tmp/tmp.Ayl5zyF5Ct/main.py: no such file or directory
```

**OS / Linux Distribution**
Which Linux distribution are you using?
```
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Installation Method**
Write here how you installed SingularityCE. Eg. RPM, source.
APT

**Additional context**
Anything else which might be relevant. E.g. if the bug only occurs on a specific filesystem, or kernel version etc.

**Comment by dtrudg** [comment]
> singularity-ce version 3.11.4-focal

SingularityCE 3.11 doesn't receive any bug fixes or support. Please try to replicate the issue with the current version (4.1.1).

I am unable to replicate, suggesting that the issue has likely been fixed already:

```
$ ./2634.sh 
DEBUG[2634.sh] Working directory: /tmp/tmp.qCcgURzqLp
JOB_ID='1'
INFO:    Using cached SIF image
1
INFO:    Using cached SIF image
1
DEBUG[2634.sh] Cleaning up /tmp/tmp.qCcgURzqLp
```
