### ISSUE TITLE
make: *** [singularity] error 1

### ISSUE THREAD

**Issue by yangwukaidi** [sylabs/singularity#2714]
Hi. I tried to install Singularity, but an error occurred when I ran the "make -C builddir" command.

These are my commands to install and compile Singularity:

_git clone --recurse-submodules https://github.com/sylabs/singularity.git
cd singularity
./mconfig
make -C builddir_

It starts to look normal:
_make: go in catalog “/mnt/e63dd5d1-08bb-4c7c-bad5-a98360c8b2fa/wuyang-running/ridge/singularity/builddir”
 GEN GO DEP /mnt/e63dd5d1-08bb-4c7c-bad5-a98360c8b2fa/wuyang-running/ridge/singularity/builddir/singularity-buildkitd.d
go: downloading github.com/moby/buildkit v0.12.5
go: downloading github.com/containerd/containerd v1.7.13
go: downloading github.com/docker/docker v25.0.3+incompatible_
...

But soon there was an error:
...
_../internal/pkg/build/buildkit/auth/authprovider.go:57:2: google.golang.org/grpc@v1.62.0: Get "https://proxy.golang.org/google.golang.org/grpc/@v/v1.62.0.zip": dial tcp 142.251.43.17:443: i/o timeout
../internal/pkg/build/buildkit/client/client.go:52:2: golang.org/x/sync@v0.6.0: Get "https://proxy.golang.org/golang.org/x/sync/@v/v0.6.0.zip": dial tcp 142.251.43.17:443: i/o timeout
../internal/pkg/build/remotebuilder/remotebuilder.go:24:2: github.com/sylabs/scs-build-client@v0.9.4: Get "https://proxy.golang.org/github.com/sylabs/scs-build-client/@v/v0.9.4.zip": dial tcp 142.251.43.17:443: i/o timeout
../internal/pkg/security/selinux/selinux_supported.go:10:8: github.com/opencontainers/selinux@v1.11.0: Get "https://proxy.golang.org/github.com/opencontainers/selinux/@v/v1.11.0.zip": dial tcp 142.251.43.17:443: i/o timeout
../pkg/cmdline/env.go:12:2: github.com/spf13/pflag@v1.0.5: Get "https://proxy.golang.org/github.com/spf13/pflag/@v/v1.0.5.zip": dial tcp 142.251.43.17:443: i/o timeout
make: *** [singularity] error 1
make: Leave directory “/mnt/e63dd5d1-08bb-4c7c-bad5-a98360c8b2fa/wuyang-running/ridge/singularity/builddir”_

I am currently using centos 7. 

How can I solve this error?

**Comment by dtrudg** [comment]
There was a network issue while the `go` command was trying to download dependencies...

```
dial tcp 142.251.43.17:443: i/o timeout
```

This might have been an issue with your network connection, or the Go module proxy service. You should try again, and investigate any network issues. The issue is not a problem specific to SingularityCE.

You may want to download a release tarball, rather than use a git clone, as this includes the dependencies.
