### ISSUE TITLE
 /usr/local/bin/unsquashfs: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory #6139 

### ISSUE THREAD

**Issue by ctroupin** [sylabs/singularity#273]
**Version of Singularity**
What version of Singularity are you using? Run:
```
$ singularity version
singularity-ce version 3.8.2
```

**Describe the bug**
I cannot run the example from the [documentation](https://sylabs.io/guides/3.8/user-guide/build_a_container.html#downloading-an-existing-container-from-the-container-library), i.e. 

`sudo singularity build lolcow.sif library://lolcow`

the output:
```bash
INFO:    Starting build...
INFO:    Using cached image
INFO:    Verifying bootstrap image /root/.singularity/cache/library/sha256.2175ac94c763b1b3e0982cff4d0c9f73e8586d9e226c5311faa43629578f57b8
ERROR:   unpackSIF failed: root filesystem extraction failed: extract command failed: WARNING: Skipping mount /etc/hosts [binds]: /etc/hosts doesn't exist in container
WARNING: Skipping mount /etc/localtime [binds]: /etc/localtime doesn't exist in container
WARNING: Skipping mount proc [kernel]: /proc doesn't exist in container
WARNING: Skipping mount /usr/local/var/singularity/mnt/session/tmp [tmp]: /tmp doesn't exist in container
WARNING: Skipping mount /usr/local/var/singularity/mnt/session/var/tmp [tmp]: /var/tmp doesn't exist in container
WARNING: Skipping mount /usr/local/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
/usr/local/bin/unsquashfs: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
: exit status 127
FATAL:   While performing build: packer failed to pack: root filesystem extraction failed: extract command failed: WARNING: Skipping mount /etc/hosts [binds]: /etc/hosts doesn't exist in container
WARNING: Skipping mount /etc/localtime [binds]: /etc/localtime doesn't exist in container
WARNING: Skipping mount proc [kernel]: /proc doesn't exist in container
WARNING: Skipping mount /usr/local/var/singularity/mnt/session/tmp [tmp]: /tmp doesn't exist in container
WARNING: Skipping mount /usr/local/var/singularity/mnt/session/var/tmp [tmp]: /var/tmp doesn't exist in container
WARNING: Skipping mount /usr/local/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
/usr/local/bin/unsquashfs: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
: exit status 127
```

**To Reproduce**
`sudo singularity build lolcow.sif library://lolcow`

**OS / Linux Distribution**
Which Linux distribution are you using?
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Installation Method**
Installation from source, following this: https://sylabs.io/guides/3.8/user-guide/quick_start.html#download-singularityce-from-a-release

```
$ ./mconfig && \
    make -C builddir && \
    sudo make -C builddir install
```

**Additional context**

I tried:
- [x] `sudo apt-get install zlib1g`; the library was already installed
- [x] `( unset LD_LIBRARY_PATH ; sudo singularity build lolcow.sif library://sylabs-jms/testing/lolcow )`
(following issue https://github.com/hpcng/singularity/issues/5666)
- [x] Changing `LD_LIBRARY_PATH` to use another location for `libz.so.1`.
- [x] Testing different versions of `unsquashfs` (4.5, 4.4)

I also opened an issue here → https://github.com/hpcng/singularity/issues/6139

**Comment by dtrudg** [comment]
Hi @ctroupin - I think I have an idea why this is happening. Our CI runs on Ubuntu 20.04, which is also used by developers, so it's not a universal issue on that distro, but will be related to the LD_LIBRARY_PATH / ld cache, or using a non-distro mksquashfs binary.

To confirm could you:

- Provide the output of `singularity buildcfg` - this shows the fallback path Singularity will use for `mksquashfs` if it's not set in `singularity.conf`.
- Provide the output of running on CE 3.8.2 with the debug flag, i.e. `singularity -d build ....` - there will be debug information about how the mksquashfs is being called.
- Let us know if you have already / try setting `mksquashfs path` in `singularity.conf`

The way external binaries are found is currently being rewritten in #272 for CE. The intention is to make it more consistent across the things we call, and I'm hopeful that what we do there will solve the issue (if my guess is correct).

**Comment by dtrudg** [comment]
How this is currently working...

- `singularity` will run `unsquashfs` inside a 'lightweight' container, in which it binds in `unsquashfs` and its discovered library dependencies. This is for containment due to security issues in squashfs which allow escaping the extraction root otherwise.
- The singularity code will lookup `unsquashfs` on `PATH`, so it's finding the `/usr/local` version in this case
  https://github.com/sylabs/singularity/blob/master/pkg/image/unpacker/squashfs.go#L65
- The libraries are discovered by calling the interpreter against the binary, with an empty environment (so LD_LIBRARY_PATH etc. never comes into play... this was to correct a different and probably opposite issue) https://github.com/sylabs/singularity/blob/master/pkg/image/unpacker/squashfs_singularity.go#L80
- We might be finding a system or other libz from the library cache on the host, and binding it in... but when we then run `unsquashfs` in the container, this is not in the location set at link time for the `/usr/local` version of the `unsquashfs` binary.

@ctroupin - sorry for additional questions... was your `/usr/local` version of `mksquashfs` compiled with an `LD_RUN_PATH` set? 

The work in #272 should indeed provide a way of getting around the problem, by making it possible to force the use of the distro `/usr/bin/unsquashfs`... but it would be interesting if there was a nice way to find and bind the correct dependencies for any `unsquashfs`, without causing a reversion to the bug in https://github.com/hpcng/singularity/issues/5666 - however,  that issue and this one may not be reconcilable simply. We will have to see.

**Comment by ctroupin** [comment]
Hello, 
thanks for the hints, and also good to know that CI is running under the same O.S. as mine.        
Here are the outputs to the different commands:

1.
```
$ singularity buildcfg
PACKAGE_NAME=singularity-ce
PACKAGE_VERSION=3.8.2
BUILDDIR=/home/ctroupin/go/src/github.com/sylabs/singularity/builddir
PREFIX=/usr/local
EXECPREFIX=/usr/local
BINDIR=/usr/local/bin
SBINDIR=/usr/local/sbin
LIBEXECDIR=/usr/local/libexec
DATAROOTDIR=/usr/local/share
DATADIR=/usr/local/share
SYSCONFDIR=/usr/local/etc
SHAREDSTATEDIR=/usr/local/com
LOCALSTATEDIR=/usr/local/var
RUNSTATEDIR=/usr/local/var/run
INCLUDEDIR=/usr/local/include
DOCDIR=/usr/local/share/doc/singularity-ce
INFODIR=/usr/local/share/info
LIBDIR=/usr/local/lib
LOCALEDIR=/usr/local/share/locale
MANDIR=/usr/local/share/man
SINGULARITY_CONFDIR=/usr/local/etc/singularity
SESSIONDIR=/usr/local/var/singularity/mnt/session
PLUGIN_ROOTDIR=/usr/local/libexec/singularity/plugin
SINGULARITY_CONF_FILE=/usr/local/etc/singularity/singularity.conf
SINGULARITY_SUID_INSTALL=1
```

2. 
```
$ sudo singularity -d build lolcow.simg library://sylabs-jms/testing/lolcow
[sudo] password for ctroupin: 
DEBUG   [U=0,P=131082]     persistentPreRun()            Singularity version: 3.8.2
DEBUG   [U=0,P=131082]     persistentPreRun()            Parsing configuration file /usr/local/etc/singularity/singularity.conf
DEBUG   [U=0,P=131082]     handleConfDir()               /root/.singularity already exists. Not creating.
DEBUG   [U=0,P=131082]     getCacheParentDir()           environment variable SINGULARITY_CACHEDIR not set, using default image cache
DEBUG   [U=0,P=131082]     newBundle()                   Created temporary directory "/tmp/bundle-temp-996678902" for the bundle
DEBUG   [U=0,P=131082]     newBundle()                   Created directory "/tmp/build-temp-108228403/rootfs" for the bundle
DEBUG   [U=0,P=131082]     ensureGzipComp()              Ensuring gzip compression for mksquashfs
DEBUG   [U=0,P=131082]     ensureGzipComp()              Gzip compression by default ensured
INFO    [U=0,P=131082]     Full()                        Starting build...
DEBUG   [U=0,P=131082]     Get()                         Getting container from Library
DEBUG   [U=0,P=131082]     Get()                         LibraryURL: https://library.sylabs.io
DEBUG   [U=0,P=131082]     Get()                         LibraryRef: library:sylabs-jms/testing/lolcow:latest
DEBUG   [U=0,P=131082]     apiGet()                      apiGet calling v1/images/sylabs-jms/testing/lolcow:latest?arch=amd64
INFO    [U=0,P=131082]     pull()                        Using cached image
DEBUG   [U=0,P=131082]     Init()                        Image format detection
DEBUG   [U=0,P=131082]     Init()                        Check for sandbox image format
DEBUG   [U=0,P=131082]     Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=0,P=131082]     Init()                        Check for sif image format
DEBUG   [U=0,P=131082]     Init()                        sif image format detected
DEBUG   [U=0,P=131082]     GetLocalPacker()              Packing from SIF
INFO    [U=0,P=131082]     verifySIF()                   Verifying bootstrap image /root/.singularity/cache/library/sha256.5022b5e7c7249c40119a875c1ace0700ced4099e077acc75d0132190254563a4
WARNING [U=0,P=131082]     GetLocalPacker()              integrity: signature not found for object group 1
WARNING [U=0,P=131082]     GetLocalPacker()              Bootstrap image could not be verified, but build will continue.
DEBUG   [U=0,P=131082]     extract()                     Trying unsquashfs options: []
[/lib/x86_64-linux-gnu/libpthread.so.0 /lib/x86_64-linux-gnu/libm.so.6 /usr/local/lib/libz.so.1 /lib/x86_64-linux-gnu/libc.so.6 /lib64/ld-linux-x86-64.so.2]
DEBUG   [U=0,P=131082]     unsquashfsSandboxCmd()        Calling wrapped unsquashfs: singularity [-q exec --no-home --no-nv --no-rocm -C --no-init --writable -B /tmp/build-temp-108228403:/image -B /usr/local/bin/unsquashfs:/usr/local/bin/unsquashfs:ro -B /lib/x86_64-linux-gnu/libpthread.so.0:/lib/x86_64-linux-gnu/libpthread.so.0:ro -B /lib/x86_64-linux-gnu/libm.so.6:/lib/x86_64-linux-gnu/libm.so.6:ro -B /usr/local/lib/libz.so.1:/usr/local/lib/libz.so.1:ro -B /lib/x86_64-linux-gnu/libc.so.6:/lib/x86_64-linux-gnu/libc.so.6:ro -B /lib64/ld-linux-x86-64.so.2:/lib64/ld-linux-x86-64.so.2:ro /tmp/build-temp-108228403/tmp-rootfs-001160801 /usr/local/bin/unsquashfs -f -d /image/rootfs /image/archive-426704407]
ERROR   [U=0,P=131082]     Pack()                        unpackSIF failed: root filesystem extraction failed: extract command failed: WARNING: Skipping mount /etc/hosts [binds]: /etc/hosts doesn't exist in container
WARNING: Skipping mount /etc/localtime [binds]: /etc/localtime doesn't exist in container
WARNING: Skipping mount proc [kernel]: /proc doesn't exist in container
WARNING: Skipping mount /usr/local/var/singularity/mnt/session/tmp [tmp]: /tmp doesn't exist in container
WARNING: Skipping mount /usr/local/var/singularity/mnt/session/var/tmp [tmp]: /var/tmp doesn't exist in container
WARNING: Skipping mount /usr/local/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
/usr/local/bin/unsquashfs: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
: exit status 127
DEBUG   [U=0,P=131082]     cleanUp()                     Cleaning up "/tmp/build-temp-108228403/rootfs" and "/tmp/bundle-temp-996678902"
FATAL   [U=0,P=131082]     runBuildLocal()               While performing build: packer failed to pack: root filesystem extraction failed: extract command failed: WARNING: Skipping mount /etc/hosts [binds]: /etc/hosts doesn't exist in container
WARNING: Skipping mount /etc/localtime [binds]: /etc/localtime doesn't exist in container
WARNING: Skipping mount proc [kernel]: /proc doesn't exist in container
WARNING: Skipping mount /usr/local/var/singularity/mnt/session/tmp [tmp]: /tmp doesn't exist in container
WARNING: Skipping mount /usr/local/var/singularity/mnt/session/var/tmp [tmp]: /var/tmp doesn't exist in container
WARNING: Skipping mount /usr/local/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
/usr/local/bin/unsquashfs: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
: exit status 127
```

3. > mksquashfs path in singularity.conf
From the log it seems I'm using `/usr/local/bin/unsquashfs`, which corresponds to the version I installed from source. I have another version installed before, in `/usr/bin/` (version 4.4 as well). 

Then in `singularity.conf` I tried setting the `mksquashfs path` as `/usr/bin/` but whatever I put there (and after running sudo make install), it ends up using the one in `/usr/local/bin/`.

Finally, to check I removed `/usr/local/bin/unsquashfs` (ok, not very clever), now the message is:
```
INFO:    Starting build...
INFO:    Using cached image
INFO:    Verifying bootstrap image /root/.singularity/cache/library/sha256.5022b5e7c7249c40119a875c1ace0700ced4099e077acc75d0132190254563a4
WARNING: integrity: signature not found for object group 1
WARNING: Bootstrap image could not be verified, but build will continue.
ERROR:   unpackSIF failed: root filesystem extraction failed: extract command failed: WARNING: Skipping mount /etc/hosts [binds]: /etc/hosts doesn't exist in container
WARNING: Skipping mount /etc/localtime [binds]: /etc/localtime doesn't exist in container
WARNING: Skipping mount proc [kernel]: /proc doesn't exist in container
WARNING: Skipping mount /usr/local/var/singularity/mnt/session/tmp [tmp]: /tmp doesn't exist in container
WARNING: Skipping mount /usr/local/var/singularity/mnt/session/var/tmp [tmp]: /var/tmp doesn't exist in container
WARNING: Skipping mount /usr/local/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
/usr/bin/unsquashfs: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
: exit status 127
FATAL:   While performing build: packer failed to pack: root filesystem extraction failed: extract command failed: WARNING: Skipping mount /etc/hosts [binds]: /etc/hosts doesn't exist in container
WARNING: Skipping mount /etc/localtime [binds]: /etc/localtime doesn't exist in container
WARNING: Skipping mount proc [kernel]: /proc doesn't exist in container
WARNING: Skipping mount /usr/local/var/singularity/mnt/session/tmp [tmp]: /tmp doesn't exist in container
WARNING: Skipping mount /usr/local/var/singularity/mnt/session/var/tmp [tmp]: /var/tmp doesn't exist in container
WARNING: Skipping mount /usr/local/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
/usr/bin/unsquashfs: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
: exit status 127
```

4. > was your /usr/local version of mksquashfs compiled with an LD_RUN_PATH set?        

No, it wasn't.

**Comment by ctroupin** [comment]
And here is the list of libraries found by 
```
libs, err := getLibraries(unsquashfs)
```
defined in https://github.com/sylabs/singularity/blob/c49972ebe492039556bb0a59e70c2fc82dd5328d/pkg/image/unpacker/squashfs_singularity.go#L174

```
[/lib/x86_64-linux-gnu/libpthread.so.0 /lib/x86_64-linux-gnu/libm.so.6 /usr/local/lib/libz.so.1 /lib/x86_64-linux-gnu/liblzma.so.5 /lib/x86_64-linux-gnu/liblzo2.so.2 /usr/lib/x86_64-linux-gnu/liblz4.so.1 /usr/lib/x86_64-linux-gnu/libzstd.so.1 /lib/x86_64-linux-gnu/libc.so.6 /lib64/ld-linux-x86-64.so.2]
```
`libz.so.1` is also present in `/lib/x86_64-linux-gnu/` but this is the one from `/usr/local/lib/` that is taken.

**Comment by dtrudg** [comment]
Thanks for the detail @ctroupin - won't be an immediate fix here, but it's enough detail that I should be able to ensure there is a fix via the forthcoming #272 - cheers.

**Comment by dtrudg** [comment]
@ctroupin -  #272 is now in a state where you can try it out... for a workaround.

It will allow `mksquashfs path` and `unsquashfs path` to be set in `singularity.conf`. In this case they would need to be set to the distro `/usr/bin/mksquashfs` and `/usr/bin/unsquashfs` respectively. These should work, with the correct libraries discovered for the lightweight container that `unsquashfs` is run inside.

This is *not* expected to work if you set `unsquashfs path` to your `/usr/local/bin/unsquashfs` - unless it is built with an `LD_RUN_PATH` set that includes all of the absolute locations of libraries it depends on.

Unfortunately being able to find the libraries for a non-distro `unsquashfs` by respecting any `LD_LIBRARY_PATH` is in direct conflict with the fix for https://github.com/hpcng/singularity/issues/5666#issuecomment-718185937 - in which the user needs to run a system `unsquashfs` while in an environment in which LD_LIBRARY_PATH includes overlapping and incompatible libraries.

🤞 this mess will go away eventually, as `squashfs-tools` 4.5 fixes the reason why we need to wrap `unsquashfs` in a container... which results in this need to find it's library dependencies accurately.

**Comment by dtrudg** [comment]
Sorry - I meant to emphasize that if you do export `LD_RUN_PATH` env var when building your custom `unsquashfs` to include the correct zlib location etc. (or use the `-rpath` linker flag), then `/usr/local/bin/unsquashfs` should work also.

**Comment by ctroupin** [comment]
Thanks, I'll try that today and report what I find!

**Comment by ctroupin** [comment]
Good news, I can now have it working, thanks!       
Still I'm not sure I understand why some things fail and other don't.

### This works
1. Setting `LD_RUN_PATH`, for example ``
2. Compile `squashfs-tools` (tested with versions 4.4 and 4.5)
3. In `singularity.conf`, set `unsquashfs path = /usr/local/bin/unsquashfs`
4. Run the command `sudo singularity build lolcow.sif library://lolcow`

```bash
INFO:    Starting build...
INFO:    Using cached image
INFO:    Verifying bootstrap image /root/.singularity/cache/library/sha256.2175ac94c763b1b3e0982cff4d0c9f73e8586d9e226c5311faa43629578f57b8
INFO:    Creating SIF file...
INFO:    Build complete: lolcow.sif
```
__Note:__ in step 1., if I use `export LD_RUN_PATH=/usr/local/lib`, the procedure also works.

### This doesn't work

In `singularity.conf`, set `unsquashfs path = /usr/bin/unsquashfs`.       
I would have expected that to work, probably I did something wrong.

**Comment by dtrudg** [comment]
Thanks for checking this, and am glad this provides a route to a solution for you. The approach with `LD_RUN_PATH` is what I'd recommend to anyone who needs to build their own `squashfs-tools`, to ensure it can always find its correct library dependencies.

I think the remaining confusing behavior here is because your custom zlib is in `/usr/local/lib`. If the attempt to use the distribution provided `/usr/bin/unsquashfs` fails then it suggests that the dynamic linker is giving us the custom zlib out of `/usr/local/lib` in conjunction with the distro `/usr/bin/unsquashfs`. Likely `/usr/local/lib` is listed in `/etc/ld.so.conf.d/*` somewhere. Does running `/usr/bin/unsquashfs` outside of Singularity, completely independently, also fail?

Generally in addition to using `LD_RUN_PATH` I'd suggest that if you are installing your own version of libraries that are also provided by the distribution (such as zlib), you make sure they are definitely not in a 'standard' library search path like `/usr/local/lib`. For example, putting your own `zlib` into `/opt` would ensure it is never in standard search paths, so shouldn't conflict with distributions provided zlib by accident.

**Comment by ctroupin** [comment]
Thanks. I forgot to post the reply.
Yes installing in  `opt` is something I should do.

> Does running /usr/bin/unsquashfs outside of Singularity, completely independently, also fail?

I'm testing now. But it seems I have possibly related issues here, for instance when I run `snap` to install something:
```
snap install SOME_TOOL
error: cannot perform the following tasks:
- Mount snap "SOME_TOOL" (183) (cannot run unsquashfs: 
-----
Filesystem uses xz compression, this is unsupported by this version
Decompressors available:
	gzip
-----)
```
