### ISSUE TITLE
'singularity' runs python game, not SingularityCE

### ISSUE THREAD

**Issue by lizi010922** [sylabs/singularity#2751]
Hi. I tried to install Singularity, but an error occurred when I ran the "singularity --version" command.

The version that I installed is "singularity-ce-4.1.2.tar.gz"

But after I followed all the steps to install singularity, it printed like this:

$ singularity run
Singularity 1.00 (commit:2ebc2f3f2059b96885416167363bde2e27ece106)
Running under Python3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
pygame 2.1.2 (SDL 2.0.20, Python 3.10.12)
Hello from the pygame community. https://www.pygame.org/contribute.html
The error-log configured as /root/.local/share/singularity/log/error.log (lazily created when something is logged)

I downloaded the package from “https://github.com/hpcng/singularity/releases”，but why the result is a pygame.

I'm really confused , please tell me which step is wrong.

**Comment by dtrudg** [comment]
In some distributions, `singularity` is a package that provide a game, and not a container runtime. You appear to have this installed on your system.

You should remove the `singularity` package, if you do not want it, and install `singularity-ce` again.

Also note that the hpcng/singularity project is not the same as this singularity-ce project (sylabs/singularity). If you have a file named singularity-ce then you downloaded it here, not from hpcng/singularity.

**Comment by DOH-ALS6303** [comment]
I am having the exact same issue and have removed the python game but there is no package called "singularity-ce" and despite installing singularity from the source, it won't run commands under singularity.

**Comment by dtrudg** [comment]
> I am having the exact same issue and have removed the python game but there is no package called "singularity-ce" and despite installing singularity from the source, it won't run commands under singularity.

Please use the Q&A section of GitHub Discussions, and provide as much information as possible about how you have tried to install SingularityCE.

It's not possible to help troubleshoot this without knowing what Linux distribution you are using, what version you are installing, exactly which commands you have followed for the installation etc. Thanks.
