### ISSUE TITLE
x509: certificate has expired or is not yet valid when  using singularity search ubuntu

### ISSUE THREAD

**Issue by Ithinky** [sylabs/singularity#2831]
**Version of Singularity**
What version of Singularity are you using? Run:

```
$ singularity --version
```
version is 3.8.6

**Describe the bug**
I download the singularity from conda because of lack of root authority. I wanted to search or pull the ubuntu image, using singularity search ubuntu and singularity pull --arch amd64 library://library/default/ubuntu:20.04, but I countered the error as follows:
![image](https://github.com/sylabs/singularity/assets/92069388/e107b56d-8484-46a6-9f43-3bdcf85f9132)

**To Reproduce**
singularity search ubuntu 
singularity pull --arch amd64 library://library/default/ubuntu:20.04

**Expected behavior**
I expected the image can be found or pulled. 

**OS / Linux Distribution**
Which Linux distribution are you using?
```
$ cat /etc/os-release
```
CentOS-7

**Installation Method**
Write here how you installed SingularityCE. Eg. RPM, source.
conda install singularity

**Additional context**
Anything else which might be relevant. E.g. if the bug only occurs on a specific filesystem, or kernel version etc.

**Comment by dtrudg** [comment]
Am pretty confident there is no issue with SingularityCE here. The certificate for library.sylabs.io is correctly signed by the LetsEncrypt R3...

<img width="275" alt="image" src="https://github.com/sylabs/singularity/assets/4522799/75f5e387-38b8-4be0-b087-308e58c61d0b">

Either:

Your operating system is not up-to-date, and is missing the roots for the LetsEncrypt R3 certificate -or-

Your conda environment is providing an alternative set of certificates that singularity is using, and these are not correct -or-

There is an intercepting proxy in your environment, replacing the certificate.

The following link may be relevant: https://community.letsencrypt.org/t/rhel-centos-7-openssl-client-compatibility-after-new-chain/151969?page=2

We aren't able to directly support the conda packaging here. Also note that version v3.8.6 is outdated.

For further assistance, please first replicate the issue with the current SingularityCE v3.11.2 installed directly (not through conda), and investigate the points above.
