### ISSUE TITLE
Error when installing from Ubuntu package

### ISSUE THREAD

**Issue by dexter2cz** [sylabs/singularity#2970]
**Version of Singularity**
singularity-ce version 4.1.3-jammy

**Describe the bug**
When installing official singularity-ce_4.1.3-jammy_amd64.deb package, there is an error:
AppArmor parser error for /etc/apparmor.d/singularity-ce in profile /etc/apparmor.d/singularity-ce at line 1: Could not open 'abi/4.0': No such file or directory

**To Reproduce**
wget https://github.com/sylabs/singularity/releases/download/v4.1.3/singularity-ce_4.1.3-jammy_amd64.deb
apt install ./singularity-ce_4.1.3-jammy_amd64.deb 

**Expected behavior**
Installing without error :)

**OS / Linux Distribution**
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**Installation Method**
apt install package from github releases

**Additional context**
dpkg -l | grep apparmor
ii  apparmor                         3.0.4-2ubuntu2.3
ii  libapparmor1:amd64               3.0.4-2ubuntu2.3 

uname -a
Linux ubuntu 5.15.0-100-generic #110-Ubuntu SMP Wed Feb 7 13:27:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

ls -la /etc/apparmor.d/abi/
total 20
drwxr-xr-x 2 root root 4096 Mar  9 02:17 .
drwxr-xr-x 8 root root 4096 Jun  5 13:22 ..
-rw-r--r-- 1 root root 1925 Jun  5  2023 3.0
-rw-r--r-- 1 root root 1633 Jun  5  2023 kernel-5.4-outoftree-network
-rw-r--r-- 1 root root 1302 Jun  5  2023 kernel-5.4-vanilla

**Comment by dtrudg** [comment]
Hmmm... yes, we should fix the error, but there should be no ill effect here.

On Ubuntu 22.04 (and 20.04) SingularityCE is unconfined even if the apparmor profile fails to work. It's basically a placeholder except on 24.04.

Will look into this for the next release.
