### ISSUE TITLE
Does not build an .img file on Vagrant 2.4.1 on Mac(Sonoma 14.5 (23F79))

### ISSUE THREAD

**Issue by maksymchapchai-tomtom** [sylabs/singularity#3005]
**Description:**
I cannot execute singularity build file.img file.sif on my Mac with Vargant VM installed.
**Steps to reproduce:**

1. Follow [official documention](https://docs.sylabs.io/guides/3.2/user-guide/installation.html#install-on-windows-or-mac).
2. Installed vagrant-scp plugin to share the resources from host.
3. Previously, I had my own file.sif built up, which perfectly works on Ubuntu 22.04, however, when I execute this command on vargant I receive next error(see Actual result)
4. Update the current system on VM, also upgrade singularity up to 3.2.1-1 version
5. Execute command again
6. Receive the same result

**Expected result:**
file.img to be built

**Actual result:**
Error received: "FATAL:   While performing build: conveyor failed to get: get did not succeed: 500 architecture not specified"

**Comment by dtrudg** [comment]
Singularity 3.2 is very old (2019). The current version is 4.1.3.

Please make sure you follow the documentation for the latest version, and not an old version.

https://sylabs.io/docs/

We no longer provide Vagrant images. The recommendation on a Mac is to use Lima:

https://docs.sylabs.io/guides/latest/admin-guide/installation.html#mac

**Comment by maksymchapchai-tomtom** [comment]
Thanks, will try it out
