### ISSUE TITLE
--fakeroot can create files not belonging to the current user

### ISSUE THREAD

**Issue by sapetnioc** [sylabs/singularity#306]
**Version of Singularity**
What version of Singularity are you using? Run:

```
$ singularity version
```
3.8.3-1

**Describe the bug**

In a brain new writable image using `apt install` create files with uid=900005 and gid=900011. Therefore, the user cannot delete the image directory without first removing these files. But many other files with wrong user are created by other commands of the Singularity compilation process.

**To Reproduce**

```
singularity build --fakeroot --sandbox ubuntu-20.04 docker://ubuntu:20.04
singularity run --fakeroot --writable ubuntu-20.04 bash
apt update -y
DEBIAN_FRONTEND=noninteractive apt install -y build-essential uuid-dev squashfs-tools libseccomp-dev wget pkg-config git libcryptsetup-dev elfutils rpm alien
exit

ls -ld ubuntu-20.04/var/cache/man/zh_CN/cat8
drwxr-xr-x 2 900005 900011 4096 sept.  3 15:48 ubuntu-20.04/var/cache/man/zh_CN/cat8

env LANG=C rm -Rf ubuntu-20.04/
rm: cannot remove 'ubuntu-20.04/var/cache/man/zh_CN/cat8': Permission denied
rm: cannot remove 'ubuntu-20.04/var/cache/man/zh_CN/cat1': Permission denied
rm: cannot remove 'ubuntu-20.04/var/cache/man/zh_CN/cat5': Permission denied
rm: cannot remove 'ubuntu-20.04/var/cache/man/CACHEDIR.TAG': Permission denied
rm: cannot remove 'ubuntu-20.04/var/cache/man/ko/cat1': Permission denied
rm: cannot remove 'ubuntu-20.04/var/cache/man/cat8': Permission denied
rm: cannot remove 'ubuntu-20.04/var/cache/man/cat3': Permission denied
rm: cannot remove 'ubuntu-20.04/var/cache/man/ru/cat8': Permission denied
```

**Expected behavior**

All files belonging to the user since he is not root, he should not have the possiblility to create files for other users (it the example above I suppose it is the "man" account of the container). I have the feeling that there is a security issue here. For instance creating an executable file with suid flag that could be run as someone else outside the container.

**OS / Linux Distribution**
Which Linux distribution are you using?
```
$ cat /etc/os-release
```
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Installation Method**
Write here how you installed SingularityCE. Eg. RPM, source.
I created a *.deb package from the source. I found this bug while trying to put this procedure in a singularity, leaving no trace of the compilation in the host system.But I noticed that I cannot remove temporary directory outside the container.

**Additional context**
Anything else which might be relevant. E.g. if the bug only occurs on a specific filesystem, or kernel version etc.

**Comment by dtrudg** [comment]
Hello. This is not a bug, but is the normal operation of `--fakeroot`, which uses the subuid / subgid mapping feature of the kernel's user namespaces.

To use fakeroot, a user is configured by the system administrator to have access to a range of subuids / subgids. The subuid and subgid ranges are system administrator controlled. The administrator is responsible for ensuring the ranges are uniquely allocated to users. This means there is no security issue - only the user to whom the ranges are allocated can use them.

In `--fakeroot` mode, `root` in the container will map to the user's standard uid outside of the container. Other user accounts in the container map to IDs outside of the container that are in the allocated subuid/subgid ranges. This is how the  `uid=900005 and gid=900011` files appear outside of the container. Your user account has been configured to have subuid/subgids in this range.
 
 Please see the documentation at:

https://sylabs.io/guides/3.8/user-guide/fakeroot.html#fakeroot-feature

https://sylabs.io/guides/3.8/admin-guide/user_namespace.html#fakeroot-feature
 
Note that you can use `--fakeroot` to remove the files that are created in the subuid ranges. I.E. you can do...

 `singularity exec --fakeroot library://ubuntu rm -r my_dir_to_remove`

.. to remove `my_dir_to_remove` which contains files in the subuid/subgid ranges.

If you have further questions on this funcitionality the SingularityCE slack or mailing list would be good places to ask them, as a broad group of users will see the discussion and contribute.

https://sylabs.io/resources/community
