### ISSUE TITLE
Support singularity instance run

### ISSUE THREAD

**Issue by ehfd** [sylabs/singularity#3083]
**Before you request a feature...**

- [x] Have you searched open issues for a duplicate feature request?
- [x] Have you checked the [latest release](https://github.com/sylabs/singularity/releases) and [latest documentation](https://sylabs.io/docs/), to see if it is already implemented?

**Is your feature request related to a problem? Please describe.**

There are situations where your OCI-SIF runtime for a Docker container built from a Dockerfile cannot be used, such as HPC environments.

In this case, `apptainer instance run` is a handy way to use `runscripts` instead of `startscripts` to support `ENTRYPOINT` and `CMD` directives in Dockerfiles with detached containers running in the background.

This is not present in Singularity, not being able to use detached containers running in `ENTRYPOINT` and `CMD`, preventing interoperability.

**Describe the solution you'd like**

Replicate https://github.com/apptainer/apptainer/pull/1401/files / https://github.com/apptainer/apptainer/issues/959

**Describe alternatives you've considered**

`singularity instance start [...] ENTRYPOINT` doesn't even work. Using `tmux`/`screen` with `singularity run` is very ugly.

**Comment by dtrudg** [comment]
This is fair enough. @cyanezstange - would you be able to work on cherry-picking (and adapting) the apptainer changes onto CE?

**Comment by ehfd** [comment]
Thank you!
