### ISSUE TITLE
Pull OCI image with overlay, without requiring --keep-layers

### ISSUE THREAD

**Issue by dtrudg** [sylabs/singularity#3135]
**Is your feature request related to a problem? Please describe.**

When an OCI-SIF contains an overlay, this overlay is present as an ext3 layer. When an image is pushed to a remote repository, with default layer format, the ext3 layer is included in the remote image.

By default, when pulling an OCI image to OCI-SIF, we squash all layers - to leave a single layer in the OCI-SIF. This means we can't pull an image that was pushed with an overlay - we have no code that supports squashing the ext3 layer down.

It's probably not expected that the overlay would be squashed anyway. An overlay is not a 'normal' r/o layer. If we pushed the image with the overlay intact, then we should have the overlay intact when it is pulled. A user can manually perform an `overlay seal` if they don't want to maintain the writable overlay functionality on the pulled image.

**Describe the solution you'd like**

When an OCI image that contains a final ext3 layer (overlay) is pulled, never attempt to squash the overlay. Instead, ensure the overlay is present in the resulting OCI-SIF as a separate ext3 layer. Provide an information message to the user stating that an overlay is present, and noting that they can `overlay seal` it if they wish.

**Comment by wobito** [comment]
wrote a comment in oct-tools, pinging for connection https://github.com/sylabs/oci-tools/issues/70#issuecomment-2236471270
