### ISSUE TITLE
Support for environment variable for path to localimage

### ISSUE THREAD

**Issue by nikkyjain** [sylabs/singularity#316]
When bootstrapping from localimage, it would be modular if user is allowed to specify environment variable. Using hard-coded paths in definition file should be avoided.

Example :

Bootstrap: localimage
From: /grid/tfo/fast_fe_in_scratch/users/vishalj/sif/base.sif

It would be good if user could use environment variable here .. somewhat like this ..
Bootstrap: localimage
From: ${SIF_PATH}/base.sif

**Comment by dtrudg** [comment]
This kind of use case should be covered by the definition file templating support (--build-args), which will be available in a 4.0 release soon.

See: #1738
