### ISSUE TITLE
malformed image path when [singularity push]

### ISSUE THREAD

**Issue by sahuno** [sylabs/singularity#3372]
**Type of issue**
Question
E.g. test problem / technical debt / release tracking

**Description of issue**
malformed image path when `singularity push <image.sif>`

Give a concise, but complete description of the issue here;
i'm unable to push my image to singularity hub after signing. i get the error malformed image path using either of these commands
```
singularity push ONT_tools.sif library://sahuno/collection/ONT_tools.sif:latest
singularity push ONT_tools.sif library://sahuno/collection/ONT_tools:latest
```

Full errors
```
FATAL: Unable to push image to library: bad request: malformed image path: sahuno/collection/ONT_tools.sif
FATAL: Unable to push image to library: bad request: malformed image path: sahuno/collection/ONT_tools
```

singularity version
`4.1.0-rc`

pls see the sylabs page with space remaining
<img width="1244" alt="Screenshot 2024-10-26 at 3 36 58 PM" src="https://github.com/user-attachments/assets/b979adfd-01e6-4ea3-80b6-85c6934ef1c3">

**Comment by vlesich-sylabs** [comment]
@sahuno The issue is caused by using uppercase letters in your repository path. We recommend using only lowercase letters and avoiding special characters.

**Comment by sahuno** [comment]
worked! thanks !!!
