### ISSUE TITLE
documentation link in repo?

### ISSUE THREAD

**Issue by vsoch** [sylabs/singularity#37]
This is a pretty simple suggestion, but I think a direct link to the current docs (on readthedocs) along with the description of the repository would be hugely useful - I always have to google search and do many clicks to find it.

**Comment by dtrudg** [comment]
Hi @vsoch - the docs from sylabs/singularity-userdocs and sylabs/singularity-admindocs aren't on read the docs... at least we aren't putting them there (have you found them somewhere?). The links in the `README.md` on the repo should currently go to the correct sylabs.io URL that will get you to a place with the latest docs for the current stable version.

The latest `master` version of the docs repos are built in CI to a CircleCI artefact, but unfortunately CircleCI doesn't have a nice way to link to that with a static URL. We do need a better way of exposing those, and will look into that.

**Comment by dtrudg** [comment]
This is what the README.md shows now... so we do have links to the guides, and we do mention and link to the repos for the user guide and admin guide...

![image](https://user-images.githubusercontent.com/4522799/118537468-97435a00-b712-11eb-9150-4e75d93312ca.png)

**Comment by vsoch** [comment]
Sorry got the wrong place it's deployed (not read the docs). 

I don't mean the README, I would like to see the user docs linked here:

![image](https://user-images.githubusercontent.com/814322/118538873-f6ea3700-b70b-11eb-9c97-dcf1c50a390d.png)

It's the first place that I look when I arrive at the repo (and my own repos, and other repos) and would be great to have there!

**Comment by dtrudg** [comment]
Ahh okay - let me see if I can do that!

**Comment by dtrudg** [comment]
Can only set one link - unfortunately others can't be added to the description text.

I'll talk to @wobito and we'll get mention of the repositories on the page it links to.

![image](https://user-images.githubusercontent.com/4522799/118539515-1e91cd00-b715-11eb-9013-90b886bfdd57.png)

**Comment by vsoch** [comment]
That looks great, thank you! We can keep this issue open to track that, or if it's underway feel free to close.

**Comment by dtrudg** [comment]
Courtesy of @wobito the linked page now looks like this:
![image](https://user-images.githubusercontent.com/4522799/118544874-7b908180-b71b-11eb-859d-cc9925f4e778.png)
