### ISSUE TITLE
e2e gpu tests not running under intended profiles

### ISSUE THREAD

**Issue by DrDaveD** [sylabs/singularity#416]
In the current master branch, I noticed 3 cases in e2e/gpu/gpu.go that invoke `c.env.RunSingularity` in a loop with a 3rd parameter of `e2e.WithProfile(e2e.UserProfile)`.  The functions are `testNvidiaLegacy`, `testNvCCLI`, and `testRocm`.  I think those should be `e2e.WithProfile(tt.profile)` because the individual tests each have their own profiles listed and they are being ignored.  I haven't checked other source files.

**Comment by dtrudg** [comment]
Thanks @DrDaveD - this appears to be my mistake from over a year ago, when I added these GPU tests.

Will file a PR shortly. As expected (since these combinations have been manually run a lot lately) the corrected tests pass.
