### ISSUE TITLE
Setting tmpdir does not work

### ISSUE THREAD

**Issue by syveqc** [sylabs/singularity#419]
**Type of issue**
Permission issues in /tmp when building a singularity container.  

**Description of issue**
I tried building a singularity container, but it fails with the error
```
While performing build: while creating SIF: while creating container: writing data object for SIF file: copying data object file to SIF file: write /tmp/image-55048263: no space left on device
```
Since I do not have permissions for the /tmp folder I tried setting the `--tmpdir` option as described in the v3.4 docs (https://sylabs.io/guides/3.4/user-guide/cli/singularity_build.html), but this option does not seem to exist in the version I am using (3.8.0-1.el7). I also tried setting the `SINGULARITY_TMPDIR` environment variable, but this does not have any effect on the error. Is there any way to set the tmpdir in my singularity version? 
(Also I am using `--remote` in case this matters)

Thanks in advance!

**Comment by dtrudg** [comment]
> (Also I am using `--remote` in case this matters)

With the remote build that SIF creation error is actually happening on the remote build agent. The settings for tempdir only apply for local builds.

If you are using the cloud.sylabs.io services there is generally ample space on the agents for most images to be built, so this particular build is using a very large amount of space.

What is the definition file you are using?

**Comment by syveqc** [comment]
Oh ok, yes I am using the sylabs cloud! My definition file is
```
Bootstrap: docker
From: carlasim/carla:0.9.12

%post
    apt-get install -y wget                                                                                                                
    wget http://privateurl/DefaultEngine.ini
    mv DefaultEngine.ini /home/carla/CarlaUE4/Config/DefaultEngine.ini
```
(where privateurl is an URL where I hosted the DefaultEngine.ini file)
So basically I just want to replace a config file in the carla (https://carla.org/) docker container. Since I want to build a singularity container from the docker container anyways I thought it was easiest to just build it using a .def file and copying the file to the container, but if there is another method to just put a single file in a container that would work as well!

**Comment by EmmEff** [comment]
@syveqc We have increased the root volume size of the remote build agents in Sylabs Cloud. This should allow this build to proceed without error. Let us know if you have any further issues. Thanks!

**Comment by syveqc** [comment]
Perfect, I can now build it without any errors! Thanks a lot!
