### ISSUE TITLE
Escaped strings being expanded in environment variables causing $LIB LD_PRELOAD isssue

### ISSUE THREAD

**Issue by liamellexus** [sylabs/singularity#43]
**Version of Singularity** 3.7.3

**Describe the bug**
Unable to set ``LD_PRELOAD=/foo/bar/$LIB/baz.so`` in an arbitrary container.

``$LIB`` is not another environment variable in this context, but is intended to be resolved by the linker, ``ld.so``. When set, using ``export SINGULARITYENV_LD_PRELOAD='/foo/bar/$LIB/baz.so'``, ``$LIB`` is treated as environment variable (which is unlikely to be set) and the variable that is set in the container is ``LD_PRELOAD=/foo/bar//baz.so`` rather than the hoped for result. As a result the library is not loaded and an error is output ``ERROR: ld.so: object '/foo/bar//baz.so`' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`

**To Reproduce**
The underlying cause can be reproduced with any environment variable with an escaped string containing ``$``, however the behaviour in many cases could well be desired/by design. I have attached some example code that builds an ``LD_PRELOAD`` library that outputs a string when loaded using the ``$LIB`` variable attached.

[preload_test.tar.gz](https://github.com/sylabs/singularity/files/6493230/preload_test.tar.gz)

It requires a singularity image to test - ``ubuntu.simg`` in the same directory.
If you run ``make singularity_test`` then it should build the library and will run a hello world program using ``SINGULARITYENV_LD_PRELOAD``, which will error before outputting ``Hello world!``. It will then re-run the binary using a script in the container that sets ``LD_PRELOAD`` that works as expected and outputs ``Loaded library successfully`` before the output of the Hello World program.

**Expected behavior**
There should be a way to escape ``$`` characters in environment variables so that they can be set in the container. Alternatively there could be an exception made for ``$LIB`` or ``${LIB}`` in ``LD_PRELOAD``.

**OS / Linux Distribution** Ubuntu 20.04.2 LTS

**Installation Method** Source (from release 3.7.3 on github)

**Additional context**
This used to work in v3.5.3 and I believe the behaviour was changed in v3.6. I mentioned this problem on the Slack channel and @dtrudg asked me to create an issue.

**Comment by dtrudg** [comment]
Thanks for the report @liamellexus - I'm not sure how we will get this passed through yet with the change to an embedded shell interpreter in 3.6, but will look into it.

**Comment by dtrudg** [comment]
If you try and send in an escaped `\$LIB` we appear to be greedily escaping the `\` -> `\\`  and the we end up with a literal `\` and `$LIB` is still resolved.

```
dtrudg@sylabs-fedora:~
02:16 PM $ export SINGULARITYENV_LD_PRELOAD='/foo/bar/\$LIB/baz.so'
dtrudg@sylabs-fedora:~
02:17 PM $ singularity run library://alpine true
INFO:    Using cached image
INFO:    Snippet: 
			if test -v LD_PRELOAD; then
				sylog debug "Overriding LD_PRELOAD environment variable"
			fi
			export LD_PRELOAD="/foo/bar/\\$LIB/baz.so"
```

Fingers crossed it should be relatively simple to allow `\$` by recognizing as an escaped `$` and leaving its `\` unescaped.

**Comment by dtrudg** [comment]
Hi @liamellexus  - in #153 I've explored ways to do this. The one that fits in with how Singularity now processes container environment with an embedded shell interpreter is to make a small fix so that you can get a literal $ in the final container var via:

```
$ export SINGULARITYENV_LD_PRELOAD="/foo/bar/\\\$LIB/baz.so"
$ singularity run library://alpine env | grep PRELOAD
LD_PRELOAD=/foo/bar/$LIB/baz.so
```

or...

```
$ export SINGULARITYENV_LD_PRELOAD='/foo/bar/\$LIB/baz.so'
$ singularity run library://alpine env | grep PRELOAD
LD_PRELOAD=/foo/bar/$LIB/baz.so
```

Does this work for you?

**Comment by liamellexus** [comment]
Yes - that works for us - thank you for checking.
I've built from the latest master and it works well for our use cases.
