### ISSUE TITLE
documentation of singularity definition file sections should reflect order in which they are processed

### ISSUE THREAD

**Issue by mgjf** [sylabs/singularity#460]
**Version of Singularity**
What version of Singularity are you using?
Any version including 3.9.1

**Describe the bug**
The output of `singularity help build` and the [documentation of definition files](https://sylabs.io/guides/3.9/user-guide/definition_files.html#sections) differ in the order in which individual sections of the definition file occur. In both instances, the order is confusing to users because it does not fully reflect the order in which the sections are processed.

**To Reproduce**
Issue `singularity help build`
Browse https://sylabs.io/guides/3.9/user-guide/definition_files.html#sections
Compare with actions during build

**Expected behavior**
The documented order of definition file sections should be consolidated, and it should reflect the order in which the sections are processed or which of the following sections they affect. I suggest
```
%pre
%setup
%files
%post
%environment
%test
%runscript
%startscript
%labels
%help
```
Rationale: the first four sections are processed sequentially during build.
The remaining sections cause the respective scriptlets to be copied to files in the container.
The variables set in %environment are not available during build and only affect container runtime.
%labels and %help are non-functional and should appear at the end

**OS / Linux Distribution**
Any recent Linux version.

**Installation Method**
From https://github.com/sylabs/singularity/releases/download/v3.9.1/singularity-ce-3.9.1.tar.gz

**Additional context**

**Comment by dtrudg** [comment]
This seems mostly reasonable, with the exception that `%labels` is processed and written into metadata during container build, and it's possible to dynamically add labels by manipulations in `%post`, so it should fit in the 'build' portion of the order here.

See e.g. https://sylabs.io/guides/3.9/user-guide/environment_and_metadata.html#dynamic-build-time-labels

**Comment by vsoch** [comment]
This looks like an easy fix! Please assign me @dtrudg I'll open a PR soon where we can discuss details.
