### ISSUE TITLE
Ability to append/prepend to environment variables when invoking container

### ISSUE THREAD

**Issue by robinlh** [sylabs/singularity#490]
**Environment variable handling since Singularity 3.6**:
We’ve designed the [IDIA processMeerKAT pipeline](https://idia-pipelines.github.io/docs/processMeerKAT) to operate on a SLURM cluster as a set of wrapper scripts that call certain scripts within certain SLURM jobs, each launched within a Singularity container. The user first sources a version/branch of the pipeline by sourcing a particular path that corresponds to a particular branch. The effect of this is to add the modules/libraries to the user’s `$PATH` and `$PYTHONPATH`, similar to sourcing a python virtual environment. Within our latest containers, we add to the `$PYTHONPATH` within the `%environment` section of the recipe file, to find certain modules that are added to the main software ([CASA]( https://casa.nrao.edu/)) within the container. When using Singularity < 3.6, this worked seamlessly, but when using Singularity >= 3.6, the `$PYTHONPATH` is completely overwritten, instead of being appended to.

**Proposed functionality**:
Having the ability to prepend or append any environment variable (and not just overwriting it), like is currently done for `$PATH`, would overcome this, as we’d be able to use the following syntax every time:
`export SINGULARITYENV_PREPEND_PYTHONPATH=$PYTHONPATH`

**Our current solution**:
While we could have the initial sourcing of the pipeline force `$SINGULARITYENV_PYTHONPATH` (this is our current solution on one branch), that doesn’t overcome being able to use past (or future) containers in which the `$PYTHONPATH` is set differently, nor other software in which no such sourcing is done.

**Comment by dtrudg** [comment]
Hi @robinlh The environment handling changed in Singularity 3.6 in an attempt to bring an end to a history of continuous small and often conflicting changes in prior versions. The alterations at 3.6 are documented in the user guide:

https://sylabs.io/guides/3.9/user-guide/environment_and_metadata.html

There is a section there noting how you can evaluate variable in container, to append / prepend etc.:

https://sylabs.io/guides/3.9/user-guide/environment_and_metadata.html#evaluating-container-variables

> When setting environment variables with --env etc. you can specify an escaped variable name, e.g. \$PATH to evaluate the value of that variable in the container.
>
> For example, --env PATH="\$PATH:/endpath" would have the same effect as --env APPEND_PATH="/endpath".

So you might use:

```
export SINGULARITYENV_PYTHONPATH="$PYTHONPATH:\$PYTHONPATH"
```

... to prepend the host $PYTHONPATH to the container $PYTHONPATH.

SINGULARITYENV_APPEND_PATH / PREPEND_PATH remain for compatibility, but we are unlikely to add the APPEND/PREPEND for other variables at this point.

**Comment by Jordatious** [comment]
Hi @dtrudg, thanks for your response. I'm one of the authors of the IDIA MeerKAT pipeline, so I'm the one working on this. Your suggestion works basically the same as our current workaround, although slightly better as I believe it's sensitive to the `$PYTHONPATH` set within the recipe file itself, which may change between containers, not just branches of our software. 

The difficulty is that it means the software itself or the user must implement this extra feature, meaning the backward compatibility that Singularity is supposed to have between versions is gone. One alternative method would be to be able to use this kind of syntax within the container recipe itself. Does this same syntax of prepending to the hosts `$PYTHONPATH` work within the `%environment` section? We haven't tested that yet, but I'm hoping so!

**Comment by dtrudg** [comment]
@Jordatious  - The host env vars are available directly in `%environment` so you can....

```
$ cat env.def 
Bootstrap: library
From: alpine

%environment
	export PYTHONPATH="$PYTHONPATH:/a:/b:/c"

%runscript
	echo "PYTHONPATH=$PYTHONPATH"

$ export PYTHONPATH="/hosta:/hostb:/hostc"

$ singularity run env.sif 
PYTHONPATH=/hosta:/hostb:/hostc:/a:/b:/c
```

You don't escape the `$` here... as we want to eval the var directly.... the quote when passing through from the shell is needed so it's not evaluated by the host shell.

**Comment by Jordatious** [comment]
Hi @dtrudg, ok great, thanks for that! I think we can close this now.
