### ISSUE TITLE
Unable to push image to library malformed image path

### ISSUE THREAD

**Issue by JudithR** [sylabs/singularity#509]
Hi, 

I'm trying to build an image using the cloud builder from the web interface. The image builds correctly and the container is published if and only if I do not change the image location: 

![image](https://user-images.githubusercontent.com/7704036/149365799-fa581523-8de4-4049-babd-2e7f3df68b06.png)

It fails if I change the location:

![image](https://user-images.githubusercontent.com/7704036/149365892-961449ee-9c08-4ffd-9f3a-82d8b4323046.png)

I build an image previously with a different location and that worked fine. I tried various versions of the location (without dots, different levels, etc) to no avail.

I can't find any info about what the path for the image location should look like and no other mentions of this issue. 
Suggestions as to what I am doing wrong?

Regards
Judith

[build.log](https://github.com/sylabs/singularity/files/7864172/build.log)

**Comment by dtrudg** [comment]
Hi @JudithR - the location cannot include upper case letters. It needs to be all lower case. This could be reported better, certainly.

**Comment by EmmEff** [comment]
Hello Judith,

Thank you for your feedback. As per the error message, the image path is invalid. In this case, it's due to the uppercase characters. The library reference must be entirely lowercase.

I will submit an issue internally to have the error message be more verbose.

Mike.
