### ISSUE TITLE
deb packets don't contain man pages

### ISSUE THREAD

**Issue by kthun91** [sylabs/singularity#512]
The new deb packets ([deb here](https://github.com/sylabs/singularity/releases/tag/v3.9.3)) don't contain man pages. After installing, the `$ man singularity` command does not work.

It would be nice to add man pages to run-singularity and singularity. 

**Additional context**
`lintian -c singularity-ce_3.9.3-bionic_amd64.deb 
E: singularity-ce: debian-changelog-file-contains-invalid-email-address root@8f0a5c100037
W: singularity-ce: setuid-binary usr/lib/x86_64-linux-gnu/singularity/bin/starter-suid 4755 root/root
W: singularity-ce: binary-without-manpage usr/bin/run-singularity
W: singularity-ce: binary-without-manpage usr/bin/singularity
`

**Comment by dtrudg** [comment]
This isn't really just a deb package issue. The `make install` target needs to be fixed up to do this properly first. Will take a look at it later today, or tomorrow.
