### ISSUE TITLE
I can't pull library://godlovedc/funny/lolcow 401 Unauthorized

### ISSUE THREAD

**Issue by thibaulttabarin** [sylabs/singularity#515]
**Version of Singularity**
What version of Singularity are you using? Run:

```
$ singularity --version
3.5.3
```

**Describe the bug**
After installation anything I pull from library://  sent this error
FATAL:   While pulling library image: could not get image info: request did not succeed: UNAUTHORIZED: authorize header needed to send HEAD to repository: authorize header needed to send HEAD to repository (401 Unauthorized)

**To Reproduce**
follow this to install
https://singularity-tutorial.github.io/02-basic-usage/
then 
singularity pull library://godlovedc/funny/lolcow
and 
FATAL:   While pulling library image: could not get image info: request did not succeed: UNAUTHORIZED: authorize header needed to send HEAD to repository: authorize header needed to send HEAD to repository (401 Unauthorized)

but when I use
singularity pull docker://godlovedc/lolcow
it works

**Expected behavior**
I expect to pull the image lolcow from library://godlovedc/funny/lolcow
**OS / Linux Distribution**
Which Linux distribution are you using?
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Installation Method**
Write here how you installed SingularityCE. Eg. RPM, source.
follow this to install
https://singularity-tutorial.github.io/02-basic-usage/

**Additional context**
Anything else which might be relevant. E.g. if the bug only occurs on a specific filesystem, or kernel version etc.

**Comment by dtrudg** [comment]
Apologies - following an update to the Sylabs cloud services we are still troubleshooting some issues. One of these issues is that pulling public images is not working unless you are logged in to the services.

If you `singularity remote login` with an authentication token you obtain at cloud.sylabs.io the pull should work.

We are working to fix the issue, and providing updates here: https://groups.google.com/g/singularity-ce/c/8XWqbe9Icz0

As this is not a bug with SingularityCE itself, but an issue with the cloud services, I am going to remove the bug marker here.

**Comment by dtrudg** [comment]
Apologies for these issues. The problem should now be resolved.
