### ISSUE TITLE
Opposite of flag to "--force". IE, for headless builds, a flag to die on any error instead of prompting for user input.

### ISSUE THREAD

**Issue by bryan-lunt** [sylabs/singularity#521]
**Is your feature request related to a problem? Please describe.**

I wish to build my images inside a batch job on a cluster. If I start the batch job and tell it to build an image file that already exists, it tries to prompt for user input and then hangs indefinitely.

**Describe the solution you'd like**

I'd like an additional commanline parameter such as "--noninteractive" or "--dieonerror" or whathaveyou.

**Describe alternatives you've considered**

I can wrap my builds in a shell script and make the shell script check for any situation that would cause `singularity build` to hang indefinitely.

**Additional context**

**Comment by dtrudg** [comment]
We may be able to leverage the same detection of non-interactive execution that is used to disable log coloration here. It's definitely a reasonable feature request.
