### ISSUE TITLE
Bootstrap tentos 8 fail

### ISSUE THREAD

**Issue by Lcornet** [sylabs/singularity#542]
### Version of Singularity:

singularity-ce version 3.8.0

### Expected behavior

Build of a container images from mirror url of centos 8.

### Actual behavior

Fail to get the mirror url.

Build target 'OGstranslate.sif' already exists and will be deleted during the build process. Do you want to continue? [N/y] y
INFO:    Starting build...
INFO:    Skipping GPG Key Import
http://mirror.centos.org/centos-8/8/BaseOS/x86_64/os/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: base. Please verify its path and try again
FATAL:   While performing build: conveyor failed to get: while bootstrapping: exit status 1

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

Bootstrap: yum
OSVersion: 8
MirrorURL: http://mirror.centos.org/centos-8/8/BaseOS/x86_64/os/
Include: yum

sudo singularity build OGstranslate.sif OGstranslate.def

A similar error can by obtained when running from docker:

Bootstrap: docker
From: centos:8

INFO:    Starting build...
Getting image source signatures
Copying blob a1d0c7532777 done
Copying config 8c1402b22a done
Writing manifest to image destination
Storing signatures
2022/02/02 13:02:55  info unpack layer: sha256:a1d0c75327776413fa0db9ed3adcdbadedc95a662eb1d360dad82bb913f8a1d1
INFO:    Copying OGstranslate_companion.py to /tmp/build-temp-189355516/rootfs/opt/
INFO:    Copying yaml.part1 to /tmp/build-temp-189355516/rootfs/opt/
INFO:    Running post scriptlet
+ chmod -R 777 /opt
+ chmod -R 777 /root
+ yum install -y git
CentOS Linux 8 - AppStream                                                                       479  B/s |  38  B     00:00
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist

### What OS/distro are you running

VERSION="18.04.6 LTS (Bionic Beaver)"

### How did you install Singularity

From source, but singularity works well it is juste a problem of lentos repo. Could you help me to get a correct MirrorURL:. This centos URL was working until yesterday but not yet.

**Comment by dtrudg** [comment]
This isn't a Singularity issue. The URL is not on the CentOS mirror any more, because CentOS 8 is end of life as of December 31st.

https://forums.centos.org/viewtopic.php?f=54&t=78708

You may want to look into using the vault mirror if you need EOL CentOS 8. E.g.:

https://vault.centos.org/8.5.2111/

Otherwise you'll need to switch to a different EL rebuild, e.g. Alma Linux, Rocky Linux etc.

**Comment by Lcornet** [comment]
Ok, thanks for the link.

Yes all my containers involves CentOS 8.
I tried the vaunt link (multiple) but it always output this error:

**Comment by dtrudg** [comment]
Take a look in the thread I linked: https://forums.centos.org/viewtopic.php?f=54&t=78708#p330704

Note that this means you are using an end of life CentOS 8 with no security updates etc. Ideally you should instead migrate to one of the maintained EL 8 rebuilds.
