### ISSUE TITLE
Install Tutorial Outdated

### ISSUE THREAD

**Issue by trigaten** [sylabs/singularity#561]
[The installation page](https://sylabs.io/guides/3.0/user-guide/installation.html#install-on-windows-or-mac) contains commands like `brew cask install virtualbox`. This generates an error on Mac (`unknown command: cask`) and according to https://github.com/Homebrew/discussions/discussions/902#discussion-3236344 `brew cask install` is outdated.

**Comment by dtrudg** [comment]
The link you have posted is for singularity v3.0 which is very old and not maintained:

https://sylabs.io/guides/3.0/user-guide/installation.html#install-on-windows-or-mac

Please use the latest version of the guide, which you can always find via:

https://sylabs.io/docs/

In the 3.9 admin docs you should see the correct use of `--cask`:

https://sylabs.io/guides/3.9/admin-guide/installation.html#mac

```
$ brew install --cask virtualbox vagrant vagrant-manager
```

**Comment by trigaten** [comment]
> The link you have posted is for singularity v3.0 which is very old and not maintained:
> 
> https://sylabs.io/guides/3.0/user-guide/installation.html#install-on-windows-or-mac
> 
> Please use the latest version of the guide, which you can always find via:
> 
> https://sylabs.io/docs/
> 
> In the 3.9 admin docs you should see the correct use of `--cask`:
> 
> https://sylabs.io/guides/3.9/admin-guide/installation.html#mac
> 
> ```
> $ brew install --cask virtualbox vagrant vagrant-manager
> ```

Gotcha, the link I posted is also the first Google result.
