### ISSUE TITLE
singularity run library://... does not honor active remote

### ISSUE THREAD

**Issue by h3kker** [sylabs/singularity#59]
**Version of Singularity**
What version of Singularity are you using? Run:

```
$ singularity version
singularity-ce version 3.8.0-rc.2
```

**Describe the bug**
When using `singularity run library://entity/collection/container` the container is always looked up in the sylabs cloud, even if a different remote is active in remote.yaml

**To Reproduce**

1. set up a custom remote 
2. singularity remote use custom
3. singularity run library://entity/collection/container (where the container is not present in the sylabs cloud)

**Expected behavior**
Container should be fetched from the active remote. "pull", "search", ... all use the active remote, only run does not.

**Installation Method**
compiled from source with the 3.8.0-rc.2 tag

**fix**
it seems the attached patch can fix this.
[singularity-remote.patch.txt](https://github.com/sylabs/singularity/files/6554816/singularity-remote.patch.txt)

**Comment by dtrudg** [comment]
This was fixed in 3.7.4 in a security advisory yesterday: https://github.com/sylabs/singularity/security/advisories/GHSA-5mv9-q7fq-9394

The released 3.8.0 includes the fix.
