### ISSUE TITLE
singularity search gives 504?

### ISSUE THREAD

**Issue by nileshpatra** [sylabs/singularity#591]
**Version of Singularity**
What version of Singularity are you using? Run:

```
$ singularity --version
```
3.9.5

**Describe the bug**
Not sure if this is just me, but
```
$ singularity search lolcow
FATAL:   Couldn't search library: request did not succeed: http status code: 504
```
The URL for lib search: https://library.sylabs.io
that is mentioned in the [docs](https://sylabs.io/guides/3.2/user-guide/cli/singularity_search.html) as well gives out 404

It seems like something went down? If that's the case, could you please get this fixed?

**Comment by dtrudg** [comment]
Hi @nileshpatra - we track issues related to the Sylabs Cloud Services separately via support@sylabs.io 

This isn't a bug with SingularityCE itself. I'll make sure the issue is tracked in the right place.
