### ISSUE TITLE
Sandbox. Problem shelling into sandbox folder.

### ISSUE THREAD

**Issue by GerardTromp** [sylabs/singularity#592]
**Version**: 3.9.1+129-g4e0b87f5b

**Describe the bug**
`Mounting` sandbox fails. 
Creation of sandbox succeeds. 

**To Reproduce**
`$ singularity build --sandbox target source` 
succeeds and creates the expected Linux hierarchy of files.

The  resulting with the `target` `root` folder contains the folders:
```
bin
boot
dev
environment
etc
home
lib
lib64
media
mnt
opt
proc
root
run
sbin
singularity
srv
sys
tmp
usr
var
```
These folders contain expected files, i.e., not empty.

`$ singularity shell --writable target/` 
does not change the directory. Issuing it with the `sudo` command lands one in `/root` rather than in a `chroot`-ed sandbox.

**Expected behavior**
`$ singularity shell --writable target/`  is expected to land one in a `chroot`-ed environment (shorthand for whatever singularity should be doing) where one can develop the container.

*From the documentation*:
**The resulting directory operates just like a container in a SIF file.** To make changes within the container, use the `--writable` flag when you invoke your container. It’s a good idea to do this as root to ensure you have permission to access the files and directories that you want to change

**OS / Linux Distribution**
*for the container*
`minideb:buster`

```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

*Host OS*
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Installation Method**
SingularityCE compiled from `github pull`.

**Additional context**

**Comment by dtrudg** [comment]
I don't think there is a bug here.

Singularity works a bit differently to Docker by default. When you shell into the sandbox you will be in the sandbox as the chroot, but the `$HOME` directory of the calling user is mounted in. If you run with `sudo` then `$HOME` is `/root`, it'll be bound in from the host and that's where you will enter the container.

If you want to avoid the bind mounts, look at the `--contain` or `--containall` options. There's also `--compat` as a shorthand to turn on additional options to get closer to Docker behaviour.

References for this: 

* https://sylabs.io/guides/3.9/user-guide/bind_paths_and_mounts.html#system-defined-bind-paths
* https://sylabs.io/guides/3.9/user-guide/singularity_and_docker.html#default-mounts-home

```
# On my host `/etc/redhat-release` is showing my host is Fedora.
09:31 AM $ cat /etc/redhat-release 
Fedora release 35 (Thirty Five)

# I build the sandbox
09:32 AM $ sudo singularity build -s target docker://ubuntu
[sudo] password for dtrudg: 
INFO:    Starting build...
Getting image source signatures
Copying blob 08c01a0ec47e done  
Copying config 4aa048d302 done  
Writing manifest to image destination
Storing signatures
2022/02/24 09:33:28  info unpack layer: sha256:08c01a0ec47e82ebe2bec112f373d160983a6d1e9e66627f66a3322bc403221b
INFO:    Creating sandbox directory...
INFO:    Build complete: target

# I shell into the sandbox writable
09:33 AM $ sudo singularity shell --writable target/
WARNING: Skipping mount /etc/localtime [binds]: /etc/localtime doesn't exist in container
WARNING: Skipping mount /data [binds]: /data doesn't exist in container

# I'm in `/root` which is bound in from my host... so I can see `/root` files from the host
Singularity> ls
anaconda-ks.cfg  bundle-crun  bundle-runc  bundle-sing  go

# However I *am* in the chroot of the sandbox. I'm in an Ubuntu rootfs, not my host's Fedora
Singularity> cat /etc/redhat-release
cat: /etc/redhat-release: No such file or directory

Singularity> cat /etc/debian_version 
bullseye/sid
```

**Comment by GerardTromp** [comment]
Thanks.
For some reason earlier it still showed me the host /etc (os-releaase).  When I tried to shell in. 
Reinstalled singularity and now it works.
