### ISSUE TITLE
Installation issue in Macbook Pro M1 MacOS BigSur

### ISSUE THREAD

**Issue by JoyceVelos** [sylabs/singularity#66]
Hi,

I am trying to install Singularity on a Macbook Pro M1 MacOS BigSur 11.4 but every time I run the script below, I get into an error.
"export VM=sylabs/singularity-3.5-ubuntu-bionic64 && \
    vagrant init $VM && \
    vagrant up && \
    vagrant ssh"

The error message is: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "d3126691-9ee2-4e61-a838-c0d784eba7c0", "--type", "headless"]

Stderr: VBoxManage: error: The virtual machine 'vm-singularity_default_1622454996768_88432' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

I found a lot of suggestions to uninstall and reinstall, which I already did, but is not working. The "Allow" message that suppose to pop up in the system preference is not showing, too.

Could you please help me? Thank you!

Best regards,
Joyce

**Comment by dtrudg** [comment]
@JoyceVelos - the vagrant boxes are currently only created for VirtualBox on x86_64 architectures (Intel based Macs).

VirtualBox does not support M1 macs, as it focuses on Intel/AMD virtual machines, while M1 Macs use a different ARM processor: https://forums.virtualbox.org/viewtopic.php?f=8&t=100875

As far as I am aware, the only consumer targeted VM software supporting M1 at present is Parallels. You may be able to manually install a Linux VM in Parallels, and then install Singularity inside of that.

**Comment by tri-adam** [comment]
@JoyceVelos I feel your pain! As an M1 Macbook Air owner, virtualization is one of the niggles.

Most Vagrant setups use VirtualBox, and to date it doesn't look like there is a path forward there (yet). There's some extra context in https://github.com/hashicorp/vagrant/issues/12105.

We'll have to wait and see what the best path forward is here in the tech we rely on. Until there's a combination of Vagrant and hypervisor support for M1 Macs, I'd echo @dtrudg 's suggestion of taking a look at Parallels or [UTM](https://mac.getutm.app/).

**Comment by JoyceVelos** [comment]
@tri-adam @dtrudg Thank you for your responses. I will try those suggestions. But yeah, I hope there would be developments for this. :)

**Comment by lwachowiak** [comment]
For anyone trying and stumbling upon this thread: I tried using parallels, but the problem is that you cannot install go in the VM, which, however, is a prerequisite for Singularity. So, sadly, it's also a dead end.
