### ISSUE TITLE
Environment variables are not (always?) passed during `singularity exec`

### ISSUE THREAD

**Issue by rklasen** [sylabs/singularity#667]
**Version of Singularity**
What version of Singularity are you using? Run:

```
$ singularity --version
singularity-ce version 3.9.1
```

**Describe the bug**
Environment variables are passed to the container when it's run interactively, but not when run with `singularity exec python testEnv.py`. I can give a concise example:

I have a singularity image that's based on a docker image. In the docker image, there is an env variable set:

```
I have no name!@382eaaff1b1f:~$ echo $LMDFIT_BUILD_PATH/
/mnt/work/LuminosityFit/build/
```
On the system I'm running this image, this variable is set to something else:

```
roklasen@login23:~$ echo $LMDFIT_BUILD_PATH
/home/roklasen/LuminosityFit/build
```
Which is what I want. I noticed Singularity passes these environment variables to the container automatically, which is okay (I want this here too):

```
roklasen@login23:~$ singularity run lmdfit-mini.sif
INFO:    Converting SIF file to temporary sandbox...
Singularity> echo $LMDFIT_BUILD_PATH/
/home/roklasen/LuminosityFit/build/
Singularity>
```
So far so good. Now, I want to read that environment variable with python. I have this very basic python script:

```python
#!/usr/bin/env python
import os
lmd_build_path = os.environ["LMDFIT_BUILD_PATH"]
print(f'lmd build path: {lmd_build_path}')
print(f'AND: {os.system("echo $LMDFIT_BUILD_PATH")}')
```

When I enter the container manually and execute this script, the variable is set correctly:

```
roklasen@login23:~$ singularity run lmdfit-mini.sif
INFO:    Converting SIF file to temporary sandbox...
Singularity> python testEnv.py
lmd build path: /home/roklasen/LuminosityFit/build
/home/roklasen/LuminosityFit/build
AND: 0
Singularity> exit
```

But when I run this script via singularity directly, the variable is NOT set to the current one, but instead the very old one from the first docker container, which I thought was overridden:

```
roklasen@login23:~$ singularity run lmdfit-mini.sif python testEnv.py
INFO:    Converting SIF file to temporary sandbox...
lmd build path: /mnt/work/LuminosityFit/build
/mnt/work/LuminosityFit/build
AND: 0
INFO:    Cleaning up image...
```

**Expected behavior**

So it seems if I run `singularity exec python testEnv.py`, the environment variables are NOT correctly passed to the container.

**OS / Linux Distribution*

Which Linux distribution are you using?

The host system is

```
$ cat /etc/os-release
roklasen@login23:~$ cat /etc/os-release
NAME="AlmaLinux"
VERSION="8.5 (Arctic Sphynx)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.5 (Arctic Sphynx)"
```

The guest system is the Debian 10 docker image with python3 installed.

**Installation Method**
Write here how you installed SingularityCE. Eg. RPM, source.

It is provided to me on a cluster system by the HPC team, I don't know how they installed it.

**Additional context**

I can build some minimal docker image and singularity image to reproduce this, if that's required. But I don't think this issue is from my image or python. Maybe I'm missing how python handles environment variables?

**Comment by dtrudg** [comment]
> singularity-ce version 3.9.1

Please could you double check with the current release of SingularityCE (3.9.7)? There have been some fixes to environment variable handling / overrides within the 3.9.x series of releases.

Also, there is a bit of confusion in the example you give. You show...

> roklasen@login23:~$ singularity run lmdfit-mini.sif python testEnv.py

But the title of this issue is about `singularity exec`. Please could you double check exec vs run etc. in the example. Thanks!

**Comment by rklasen** [comment]
Hi, thank you for the quick reply! You're right, I mixed up `run` and `exec`, sorry about that. `singularity exec` is what I give to the SLURM job manager, but I just checked both again in the 3.9.1 installation:

```
roklasen@login23:~$ singularity run lmdfit-mini.sif python testEnv.py
INFO:    Converting SIF file to temporary sandbox...
lmd build path: /mnt/work/LuminosityFit/build
/mnt/work/LuminosityFit/build
AND: 0
INFO:    Cleaning up image...
roklasen@login23:~$ singularity exec lmdfit-mini.sif python testEnv.py
INFO:    Converting SIF file to temporary sandbox...
lmd build path: /mnt/work/LuminosityFit/build
/mnt/work/LuminosityFit/build
AND: 0
INFO:    Cleaning up image...
```

So that's not it. On the cluster system I can't try another version unfortunately, but I can on my workstation:

```
$ singularity --version
singularity-ce version 3.9.7-focal
```

Running the same tests (the host path is different here, but the singularity image still contains the old path):

```
$ echo $LMDFIT_BUILD_PATH
/media/CacheDrive2TB/Arbeit/LuminosityFit/build
```

Running singularity interactively:

```
$ singularity run lmdfit-mini.sif
bash: powerline-shell: command not found
Singularity> echo $LMDFIT_BUILD_PATH
/media/CacheDrive2TB/Arbeit/LuminosityFit/build
Singularity> python testEnv.py
lmd build path: /media/CacheDrive2TB/Arbeit/LuminosityFit/build
/media/CacheDrive2TB/Arbeit/LuminosityFit/build
AND: 0
Singularity>
```

And with `run` and `exec`:

```
$ singularity run lmdfit-mini.sif python testEnv.py
lmd build path: /media/CacheDrive2TB/Arbeit/LuminosityFit/build
/media/CacheDrive2TB/Arbeit/LuminosityFit/build
AND: 0
$ singularity exec lmdfit-mini.sif python testEnv.py
lmd build path: /media/CacheDrive2TB/Arbeit/LuminosityFit/build
/media/CacheDrive2TB/Arbeit/LuminosityFit/build
AND: 0
```

So it seems the issue is indeed fixed in the current version! I'll have to ask the cluster admins to upgrade singularity.

Is there something I can try in the meantime, like explicitly passing (not setting inside the container) env variables? And is there any way to inspect a singularity image and see what variables are set inside it?

**Comment by dtrudg** [comment]
Glad to know the fixes in the 3.9 series apply. With regard to the workaround, though... I don't want to speculate too much on what works on 3.9.1 without knowing exactly the chain through which the image was built. E.g. what's in the original Dockerfile, what Singularity Definition file was used to derive from the Docker image etc.

The one thing you can definitely try is setting `SINGULARITYENV_LMDFIT_BUILD_PATH` or using `--env LMDFIT_BUILD_PATH=xxx` - these should override everything.... but I'm not 100% confident on 3.9.1.

**Comment by rklasen** [comment]
So I've prepared a minimum working example. Singularity is still:

```
singularity --version
singularity-ce version 3.9.7-focal
```

From this Dockerfile:

```dockerfile
FROM debian:buster
ENV TZ=Europe/Berlin
ENV DEBIAN_FRONTEND=noninteractive
ENV TESTENV=thisIsAtest
```

I'm building an image (workaround with a local registry, I don't know any other way without using Docker Hub):

```bash
docker run -d -p 5000:5000 --restart=always --name registry registry:2
docker build -t localhost:5000/test .
docker push localhost:5000/test
```

I test to see if the env variable is set:

```bash
docker run -it localhost:5000/test /bin/bash
root@168e2da17616:/# echo $TESTENV
thisIsAtest
root@168e2da17616:/#
```

It is. I build a Singularity image from that. I have this `recipe.txt`:

```
Bootstrap: docker
From: test:latest
Registry: localhost:5000
```

With it, I build the actual image:

```
sudo SINGULARITY_NOHTTPS=true singularity build test.sif recipe.txt
[sudo] password for roman:
INFO:    Starting build...
Getting image source signatures
Copying blob 1230f17f526c skipped: already exists
Copying config 63032e420c done
Writing manifest to image destination
Storing signatures
2022/03/28 17:01:39  info unpack layer: sha256:1230f17f526cb07307d41462355b10488b994e8bdafe0d8f275a405fa3b33831
INFO:    Creating SIF file...
INFO:    Build complete: test.sif
```

And the variable is set as well:

```
singularity run test.sif
bash: powerline-shell: command not found
Singularity> echo $TESTENV
thisIsAtest
Singularity>
```

Now, I replace the env variable:

```
export TESTENV=newAndShiny
singularity run test.sif echo $TESTENV
newAndShiny
```

And that works as well. Same with `exec` instead of `run`:

```
singularity exec test.sif echo $TESTENV
newAndShiny
```

**But:** if I go manually into the container, the variable is **not** replaced:

```
singularity run test.sif
Singularity> echo $TESTENV
thisIsAtest
Singularity>
```

So not only is it more or less the reverse of what I described earlier, there also seem to be some timing issues. I've run this example in the same terminal in that exact sequence just now, to be extra sure. When I was running tests earlier, the variable got replaced by singularity *after several tries*, but without any other change. I simply ran the exact same commands a few minutes apart, and at the third time, it just worked as expected. I've tried to replicate that just now, but it wouldn't work.

Really weird.

**Comment by rklasen** [comment]
Oh I forgot: your workaround with manually setting the variable at time of execution does work:

```
ingularity run --env TESTENV=thirdTimeIsTheCharm test.sif
bash: powerline-shell: command not found
Singularity> echo $TESTENV
thirdTimeIsTheCharm
Singularity>
```

It seems only the implicit passing of env variables doesn't work.

**Comment by dtrudg** [comment]
Ahh, gotcha - thanks for the simplified example, which makes it easier to see what is going on. What you are observing is actually everything working as expected.

The first bit of oddness here from running on the host versus entering the container is due to where the $ var is interpreted.

When you run...

```
export TESTENV=newAndShiny
singularity run test.sif echo $TESTENV
newAndShiny
```

What actually happens is that your *host* shell substitutes `$TESTENV -> newAndShiny` _before_ passing it to singularity as `singularity run test.sif echo newAndShiny`.

When you run....

```
singularity run test.sif
Singularity> echo $TESTENV
thisIsAtest
```

... now you are actually seeing the value of `$TESTENV` in the container. You need to escape the `$` to `\$` on your host command line if you want to directly `run` or `exec` and see the value in the container:

```
# without escaping, value comes from host shell (this var doesn't exist on the host)
10:21 AM $ singularity run library://alpine echo VAR - $SINGULARITY_CONTAINER
INFO:    Using cached image
VAR - 
# with escaping, value comes from container
10:21 AM $ singularity run library://alpine echo VAR - \$SINGULARITY_CONTAINER
INFO:    Using cached image
VAR - /home/dtrudg/.singularity/cache/library/sha256.77dea042db93316b7ecc65fc39f7e19e7c209e01c38a0a87418d4be753fb9d37
```





The reason it is `thisIsAtest` instead of `newAndShiny` is because of the precedence of the env variables, as given in the guide...

https://sylabs.io/guides/latest/user-guide/environment_and_metadata.html#environment-from-a-base-image

..and..

https://sylabs.io/guides/latest/user-guide/environment_and_metadata.html#environment-variable-precedence

> You can override the inherited environment with SINGULARITYENV_ vars, or the --env / --env-file flags (see below), but Dockerfile ENV vars will not be overridden by host environment variables of the same name.

The reason we do this is to be closer to Docker... which won't import host environment variables into the container... you have to manually override them.

So, what you've noticed in the later comment with `--env` working is what you have to do (use `--env` / `--env-file` / `SINGULARITYENV_` env vars).

Sorry it took me a bit of time to get here. I was thrown a bit as we _have_ made some fixes in the 3.9 series.

**Comment by rklasen** [comment]
I see, and now that you mention it. it's pretty obvious the shell expansion happened on the hist :man_facepalming:

Alright, so if I'm understanding the reference you linked right, other than $PATH and $SINGULARITY_APPNAME, no variables should be copied? Because I just tried again with the older singularity version, and back then the variable was certainly copied sometimes (but not always and that's what confused me), but this was actually not intended?

```
roklasen@login23:~$ echo $LMDFIT_BUILD_PATH
/home/roklasen/LuminosityFit/build
roklasen@login23:~$ singularity run lmdfit-mini.sif echo \$LMDFIT_BUILD_PATH
INFO:    Converting SIF file to temporary sandbox...
/mnt/work/LuminosityFit/build
INFO:    Cleaning up image...
roklasen@login23:~$ singularity run lmdfit-mini.sif
INFO:    Converting SIF file to temporary sandbox...
Singularity> echo $LMDFIT_BUILD_PATH/
/home/roklasen/LuminosityFit/build/
Singularity> exit
INFO:    Cleaning up image...
roklasen@login23:~$
``` 

Because I can confirm, on the current singularity version, it's *not* copied anymore:

```
$ echo $LMDFIT_BUILD_PATH
/home/roklasen/LuminosityFit/build
$ singularity run lmdfit-mini.sif echo \$LMDFIT_BUILD_PATH
/mnt/work/LuminosityFit/build
$ singularity run lmdfit-mini.sif
Singularity> echo $LMDFIT_BUILD_PATH
/mnt/work/LuminosityFit/build
Singularity> exit
```

**Comment by dtrudg** [comment]
> Alright, so if I'm understanding the reference you linked right, other than $PATH and $SINGULARITY_APPNAME, no variables should be copied? Because I just tried again with the older singularity version, and back then the variable was certainly copied sometimes (but not always and that's what confused me), but this was actually not intended?

Right - the behavior described in the guide and seen in 3.9.7 is correct. The env var is only copied in from the host if it hasn't been set by means that are further up the list of bullet points in the precedence link. If your container did not set `TESTENV` then the host value *would* enter the container.

Unfortunately we had some regressions through to v3.9.5 with how our embedded shell interpreter dependency that processes the environment was working. There are some changelog entries, but perhaps we should have called out a bit more in the release notification emails. Apologies for the inconvenience / confusion.

Note that `PATH` isn't copied in directly from the host... the section...

```
> If PATH is not defined set the SingularityCE default PATH or
> If PATH is defined, add any missing path parts from SingularityCE defaults
```

... is referring to it being set from the bullet points _above_ (i.e. inherited from the image).

The value of `PATH` you observe in the container is often confusing though, as if you enter a container that invokes a shell that sources your .profile / .bashrc it's often going to be adding `PATH` components from those, which can give the impression that the host variable was imported as-is.

**Comment by dtrudg** [comment]
An explainer for the `PATH` comment above...

```
# My PATH on the host, which is very long...
$ echo $PATH
/opt/go/bin:/home/dtrudg/bin:/home/dtrudg/.local/bin:/home/dtrudg/.dotfiles/bin:/opt/go/bin:/home/dtrudg/bin:/home/dtrudg/.local/bin:/home/dtrudg/.dotfiles/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/dtrudg/go/bin:/home/dtrudg/.npm-packages/bin:/home/dtrudg/go/bin:/home/dtrudg/.npm-packages/bin

# My PATH in the container is *not* taken from the host, but does add some things from my dot files that were sourced
$ singularity run ubuntu_latest.sif 
Singularity> echo $PATH
/home/dtrudg/bin:/home/dtrudg/.local/bin:/home/dtrudg/.dotfiles/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/dtrudg/go/bin:/home/dtrudg/.npm-packages/bin

# This is really the bare value of PATH in the container, independent of my dot files sourced by shell.
$ singularity exec ubuntu_latest.sif /bin/sh -c "echo \$PATH"
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

**Comment by rklasen** [comment]
Okay, now I know what to look out for. I think the cleanest option is indeed to remove all default env vars and set them manually.

Thanks for your help!
