### ISSUE TITLE
【QE HPC App】error while loading shared libraries: libgfortran.so.5

### ISSUE THREAD

**Issue by Qiyu8** [sylabs/singularity#668]
**Version of Singularity**
3.9.6

**Describe the bug**
The sif file is successfully generated, and The mpi command inside the container can run normally, But when I running in the host machine, An error occurred:
```
pw.x: error while loading shared libraries: libgfortran.so.5: cannot open shared object file: No such file or directory
FATAL:   container creation failed: mount /proc/self/fd/3->/usr/local/var/singularity/mnt/session/rootfs error: while mounting image /proc/self/fd/3: failed to find loop device: unexpected EOF
```

**To Reproduce**
1. generate sif file using the following recipe:
```
BootStrap: docker
From: openeuler/openeuler

%post
# Install the necessary development environment
yum install -y environment-modules git dmidecode pciutils wget vim
# Install base gcc
yum install -y gcc gcc-c++ gcc-gfortran glibc-devel make libgfortran
# install network package
yum install tcsh tcl lsof tk -y
source /etc/profile || true
git config --global http.sslVerify false
git clone https://gitee.com/iotwins/hpcrunner
cd hpcrunner
git checkout fix-case
source ./init.sh
./jarvis -i
cp ./templates/qe/6.4/data.qe.container.config .
wget --no-check-certificate https://github.com/QEF/q-e/archive/refs/tags/qe-6.4.1.tar.gz
tar -xzvf qe-6.4.1.tar.gz
# Modify the path
./jarvis -use data.qe.container.config
./jarvis -d
./jarvis -dp
./jarvis -b
./jarvis -r
rm -rf downloads tmp
```

2.Running outside the container:
`mpirun --allow-run-as-root -x  OMP_NUM_THREADS=1 -np 96 singularity exec --bind /usr --bind /sys --bind /etc openeuler-kgcc9-openmpi4-qe6.4-2.sif /hpcrunner/q-e-qe-6.4.1/bin/pw.x -input /hpcrunner/workloads/QE/qe-test/test_3.in`

**Expected behavior**
The QE app can run successfully!

**OS / Linux Distribution**
openEuler 20.03

**Installation Method**
source.

**Additional context**
Anything else which might be relevant. E.g. if the bug only occurs on a specific filesystem, or kernel version etc.

**Comment by dtrudg** [comment]
Almost certainly this is the issue - `--bind /usr`

Binding all of `/usr` from the host in to the container will replace all the basic libraries in the container with the versions from the host. Unless the host is an *identical* linux distro / version and has *all* the libraries the container needs under `/usr` then this will cause major problems. The programs in the container are expecting the container versions of basic libraries under `/usr`, not what you are supplying from the host.

Binding `/etc` should generally not be done either. Binding `/sys` is unnecessary as SingularityCE will do this anyway.

If you need to bind e.g. Infiniband or MPI libraries in from the host to the container you must do this specifically. Bind only the libraries that are required. Do not bind the whole of `/usr` etc.

Take a look through the guide here: https://sylabs.io/guides/3.9/user-guide/mpi.html and please drop in to the community Slack or mailing list, as this is a usage question that will get more attention there, not a bug with SingularityCE itself.

**Comment by Qiyu8** [comment]
@dtrudg Thanks for your explaintion, I tried not binding all of `/usr /sys/ /etc`, and the `failed to find loop device` information showed again, I guess this is because the environment not set inside the container, a separate issue is opened.

**Comment by dtrudg** [comment]
Okay - let's continue in #672.
