### ISSUE TITLE
Load `/etc/profile` or source `~/.bashrc` during `singularity exec`

### ISSUE THREAD

**Issue by rklasen** [sylabs/singularity#669]
*Note*: We encourage questions about usage of SingularityCE to be made via the Google Group or Slack channels. Other users frequent these communities, and may already have the answer to your question!

See: https://sylabs.io/resources/community for links.

Note: I'd love to join the Slack Channel, the page https://sylabs.io/resources/community results in a 404.

**Type of issue**

I would like to source my `~/.bashrc` during `singularity exec`. It gets done when I enter the singularity container manually with `singularity run`, but I've found no option to have that done during `singularity exec`. The reason is that the `.bashrc` sources another script which sets some needed environment variables. I would love to just set these variables outside the container and have singularity pass them into the container, but the script checks if it's accompanying software was compiled on the same system as it is currently being run in. Since the software is compiled inside the container, and the guest os is different from the host os, the script fails.

So ideally I'd like to simply instruct `singularity exec` to either run in a regular `bash -l` shell or have the script sourced manually.

**Description of issue**
-

**Comment by dtrudg** [comment]
Sorry, we'll fix that link! Should be https://sylabs.io/singularity#community

Singularity exec runs a binary directly, there is no shell invoked, by design, so it will not source the bashrc / profile etc. In order to source / manipulate the environment you will need to do so in the `%environment` section of the definition file used to build the container.

**Comment by rklasen** [comment]
Thanks for your help! I don't suppose there is a way to force a shell? I actually need to source another bash script that updates these environment variables, but it won't run if it was compiled on a different system (i.e. inside the container) than is is run (outside the container). Is updating the environment variables by hand the only way?

**Comment by dtrudg** [comment]
There's no way with a flag / option to force what you pass to `exec` to be run in a shell. However, you can exec a shell and then use `-c` to ask the shell to run your program. E.g. 

```
$ singularity exec ubuntu_latest.sif /bin/bash -l -c 'date'
Fri Mar 25 09:10:14 CDT 2022
```

If you want to always source environment without this, you will need to build the container with the required setup in the `%environment` section of the definition file, I'm afraid. That would really be the best practice for this kind of requirement.

**Comment by rklasen** [comment]
That's a great idea, I did it just like that,
