### ISSUE TITLE
openeuler / qe container - confusing errors

### ISSUE THREAD

**Issue by Qiyu8** [sylabs/singularity#672]
**Version of Singularity**
3.9.6

**Describe the bug**
The sif file is successfully generated, and The mpi command inside the container can run normally, But when I running in the host machine, An error occurred:
```
pw.x: error while loading shared libraries: libgfortran.so.5: cannot open shared object file: No such file or directory
FATAL:   container creation failed: mount /proc/self/fd/3->/usr/local/var/singularity/mnt/session/rootfs error: while mounting image /proc/self/fd/3: failed to find loop device: unexpected EOF
```

**To Reproduce**
1. generate sif file using the following recipe:
```
BootStrap: docker
From: openeuler/openeuler

%post
# Install the necessary development environment
yum install -y environment-modules git dmidecode pciutils wget vim
# Install base gcc
yum install -y gcc gcc-c++ gcc-gfortran glibc-devel make libgfortran
# install network package
yum install tcsh tcl lsof tk -y
source /etc/profile || true
git config --global http.sslVerify false
git clone https://gitee.com/iotwins/hpcrunner
cd hpcrunner
git checkout fix-case
source ./init.sh
./jarvis -i
cp ./templates/qe/6.4/data.qe.container.config .
wget --no-check-certificate https://github.com/QEF/q-e/archive/refs/tags/qe-6.4.1.tar.gz
tar -xzvf qe-6.4.1.tar.gz
# Modify the path
./jarvis -use data.qe.container.config
./jarvis -d
./jarvis -dp
./jarvis -b
./jarvis -r
rm -rf downloads tmp
```

2.Running outside the container:
`mpirun --allow-run-as-root -x  OMP_NUM_THREADS=1 -np 96 singularity exec openeuler-kgcc9-openmpi4-qe6.4-2.sif /hpcrunner/q-e-qe-6.4.1/bin/pw.x -input /hpcrunner/workloads/QE/qe-test/test_3.in`

**Expected behavior**
The QE app can run successfully!

**OS / Linux Distribution**
openEuler 20.03

**Installation Method**
source.

**Additional context**
There is a env.sh file generated in /hpcrunner during the final step of @post, which set the running environment of QE, How can I make this env.sh work before mpirun?

**Comment by Qiyu8** [comment]
After adding %environment section, The QE application running successfully! 😄 but another question araised, HPC apps always running under specified case directory, how can I enter that directory before running mpirun outside the container?

**Comment by dtrudg** [comment]
This is still quite confusing, as I'm not exactly sure what is still being used from the host system? The loop device error is likely to be misleading...

Please can you post:

* The full definition file *with* the environment section
* The full command you are using to run the container with singularity

For these warnings...

```
UID: readonly variable
"bc": executable file not found in $PATH
```

`/etc/profile` shouldn't be trying to change the UID var... that's quite strange.
`bc` probably isn't in the container image? I'm not clear why a profile script would be trying to use `bc`?

**Comment by Qiyu8** [comment]
The successful def file is:
```
BootStrap: docker
From: openeuler/openeuler

%environment
    source /etc/profile || true
    cd /hpcrunner
    source env.sh

%post
    # Install the necessary development environment
    yum install -y environment-modules git dmidecode pciutils wget vim
    # Install base gcc
    yum install -y gcc gcc-c++ gcc-gfortran glibc-devel make libgfortran
    # install network package
    yum install tcsh tcl lsof tk -y
    source /etc/profile || true
    git config --global http.sslVerify false
    git clone https://gitee.com/openeuler/hpcrunner
    cd hpcrunner
    source ./init.sh
    ./jarvis -i
    cp ./templates/qe/6.4/data.qe.container.config .
    wget --no-check-certificate https://github.com/QEF/q-e/archive/refs/tags/qe-6.4.1.tar.gz
    tar -xzvf qe-6.4.1.tar.gz
    # Modify the case path
    sed -i 's/pseudopotentials\.d/\/hpcrunner\/workloads\/QE\/qe-test\/pseudopotentials\.d/g' ./workloads/QE/qe-test/test_3.in
    # Switch config
    ./jarvis -use data.qe.container.config
    # download dependency
    ./jarvis -d
    # install dependency
    ./jarvis -dp
    # build hpc
    ./jarvis -b
    # run hpc
    ./jarvis -r
    # clean tmp directory
    rm -rf downloads tmp
```
The env.sh file is:
```
module purge
module use ./software/modulefiles
module load kgcc9
module load openmpi4/4.1.2
```
currently I can't upload the built container and I'm working on it.

**Comment by dtrudg** [comment]
Gotcha, thanks. I'll try to take a look today or tomorrow, as though the environment stuff is somewhat expected, the loop device error is very odd. Will get back to you soon.

**Comment by Qiyu8** [comment]
After the first successful running ,The container can not run successfully again, The error shows below:
```
UID: readonly variable
"bc": executable file not found in $PATH
FATAL:   is a directory
Signal 15 (TERM) caught by ps (3.3.16).
/usr/bin/ps:ps/display.c:70: please report this bug
```

**Comment by Qiyu8** [comment]
@dtrudg HPC apps always running under specified case directory, how can I enter that directory before running mpirun?
before:
`mpirun --allow-run-as-root -x OMP_NUM_THREADS=1 -np 96 singularity exec openeuler-kgcc9-openmpi4-qe6.4-2.sif /hpcrunner/q-e-qe-6.4.1/bin/pw.x -input /hpcrunner/workloads/QE/qe-test/test_3.in`
after(how to enter directory `/hpcrunner/workloads/QE/qe-test/`):
`mpirun --allow-run-as-root -x OMP_NUM_THREADS=1 -np 96 singularity exec openeuler-kgcc9-openmpi4-qe6.4-2.sif /hpcrunner/q-e-qe-6.4.1/bin/pw.x -input test_3.in`

**Comment by Qiyu8** [comment]
Thanks a lot, The case directory problem is solved.

**Comment by dtrudg** [comment]
I've spent some time trying to reproduce the loop device EOF error, and have been unable to cause it to happen on my bare metal machine or a VM. If you'd like to look into that further, please could you let me know more about the host system, filesystem the container is on etc.

With regard to the issues when `/etc/profile` is sourced, I see the same bc and UID issues - the bc error is expected as it doesn't appear to be in the container if I shell into it. The UID read-only is expected as `/etc/profile` attempts to set UID but it is a system reserved environment variable that bash will not allow you to set.... you can't set UID in a standard terminal session either.

These are really application issues rather than Singularity bugs. The openeuler Docker file only ADDs a rootfs tarball, so I can't easily see what it is doing. I would suggest trying to find an openeuler community to ask further questions about these issues, as they are outside of my knowledge of that project.

**Comment by Qiyu8** [comment]
Thank you for your great efforts. I will ask further questions in openeuler community, feel free to close.
