### ISSUE TITLE
conmon build should handle missing seccomp headers nicely

### ISSUE THREAD

**Issue by vsoch** [sylabs/singularity#673]
**Version of Singularity**

Current master

**Describe the bug**

Hello! So I tried installing this from source (outside of a container) for the first time, and noticed that ./mconfig didn't detect that I was missing libseccomp, e.g., I hit this:

```
src/seccomp_notify.c:9:10: fatal error: seccomp.h: No such file or directory
    9 | #include <seccomp.h>
      |          ^~~~~~~~~~~
compilation terminated.
```
It looks like the mconfig file does have a flag with `--without-seccomp` (is that used for anything) and if not it assumes I have the dependency! Not sure if this is a bug, but wanted to open an issue in case yes! It's definitely easy enough to install it, but perhaps we should get a heads up about it (and indeed I know it's in the docs but you can assume I don't read things :laughing: )

**Comment by dtrudg** [comment]
Ahh right... this looks like it's from the conmon third party source added recently.

SingularityCE ./mconfig will need to infer warn and infer `--without-conmon` if we don't have seccomp dev stuff available.

I'll look into it. Thanks!
