### ISSUE TITLE
unversioned obsoletes warning in rpmbuild

### ISSUE THREAD

**Issue by dtrudg** [sylabs/singularity#714]
**Version of Singularity**

master / 3.9.8

**Describe the bug**

On Fedora 35, the following is observed during an rpmbuild.

```
warning: line 57: It's not recommended to have unversioned Obsoletes: Obsoletes: singularity-ce-runtime
```

Contrary to a report on the Google Group, this is not failing the build for me - it completes, with the above just being a warning.

**Comment by adriansev** [comment]
Hi @dtrudg! just for reference the full log is this: https://codimd.web.cern.ch/s/6T1wMgWlK
