### ISSUE TITLE
Include Apptainer copyright messages

### ISSUE THREAD

**Issue by DrDaveD** [sylabs/singularity#758]
Include the Apptainer copyright message in COPYRIGHT.md and in files where you have imported code from Apptainer, as required by the Apptainer copyright.

**Comment by dtrudg** [comment]
My apologies - I went too fast here in a rebase around a test failure and dropped the messages I'd added. Addressing in #759

**Comment by dtrudg** [comment]
Apologies for this mistake. Thank you for noting it.
