### ISSUE TITLE
Support for Dockerfile USER (--oci mode)

### ISSUE THREAD

**Issue by dtrudg** [sylabs/singularity#77]
**Is your feature request related to a problem? Please describe.**
Some Docker containers were built with a Dockerfile containing a `USER` directive. The application was installed under the assumption that at runtime the specified user is active in the container. This is not the case with Singularity, so these containers may fail with permissions or application configuration errors.

**Describe the solution you'd like**
~~SingularityCE has a ‘fakeroot engine’ that is able to configure a container run so that subuid/subgid configuration is used. This type of functionality opens the possibility of carrying through USER specifications from Docker containers, so that their payload can run as the expected username.~~

Support for Dockerfile USER should be enabled by the ability to execute images through runc as a low-level engine, through 3.11 and 4.0.

**Comment by fnikolai** [comment]
@dtrudg 

I see that your PR implements this functionality for the `--oci` mode.  

Is it possible to run the container as USER in the non-oci mode?

Thanks and happy holidays!

**Comment by dtrudg** [comment]
@fnikolai  - PR #1208 is work in progress on supporting this. Note that `--oci` mode *does not* require root privilege. It does require that the system is configured to allow unprivileged user namespaces, and subid/subgid mapping.

`--oci` is different to the `oci` command.

`singularity run/shell/exec --oci mycontainer` is a new feature for 3.11 that will run OCI containers, using an OCI runtime... and the familiar Singularity CLI. It will be similar to using `singularity run/shell/exec --compat`.

`singularity oci` is a different, and little-used feature, where the subcommands implement the low level oci runtime command line interface. This is root-only at this point.
