### ISSUE TITLE
Reworking the remote Command

### ISSUE THREAD

**Issue by dtrudg** [sylabs/singularity#78]
**Is your feature request related to a problem? Please describe.**
The remote command configures access to Sylabs cloud services, alternative keyservers, and OCI registries. It is complex as there is overlap between these targets, a concept of priorities and global/exclusive keyservers etc. This is likely a good area for a comprehensive rework.

**Describe the solution you'd like**
Comprehensive review of the verbs and command structure. Does it make sense for OCI and Sylabs Cloud/Enterprise configs to be mixed, or does it lead to more confusion. Etc.

**Describe alternatives you've considered**
Documentation improvements may lessen confusion, allow this to be deferred.

- [x] #1893 
- [x] #1894 
- [x] #1895 
- [x] #1896

**Comment by dtrudg** [comment]
@preminger - as a relative newcomer, it'd be great if you would be able to consider the design of the `singularity remote` command.

At present, it is massively overloaded in a way that is confusing. It handles...

* Configuring, logging in to, switching between remote endpoints, where a remote endpoint is a Singularity Cloud Services URI, or a Singularity Enterprise install. Each remote endpoint offers a range of services (library/builder/keystore).
* Logging into / out of OCI registries, to pull private `docker://` or `oras://` containers.
* Configuring separate standalone PGP keyserver, which are not part of a remote endpoint.
* Concepts of 'global' and 'exclusive' or 'ordered' endpoints / keyservers. Where the administrator can influence which is used. 

We need to take a really hard look at:

- What do we think `remote` should / shouldn't do? Is there any functionality that should be moved to another command, or removed entirely?
- What's confusing about the active / global / exclusive stuff? Is it really necessary? Can it be presented better?

It'd be fantastic if you could...

- Absorb the current documentation.
- Try out the functionality it describes.
- Note what's confusing / doesn't work.
- Share any thoughts on how you think 'endpoints', keyservers, OCI logins could be presented.

**Comment by preminger** [comment]
Closing - see https://github.com/sylabs/singularity/discussions/1639#discussioncomment-6512057 for details.
