### ISSUE TITLE
Updates for instance stats

### ISSUE THREAD

**Issue by vsoch** [sylabs/singularity#785]
The first PR #784 is a base, and we will need to tweak and improve it! Currently this includes:

- [ ] Calculate % CPU 
- [ ] Interactive monitoring with a loop that updates every n seconds, showing stats for more all instances

**Comment by dtrudg** [comment]
- [ ] Always start instances in a cgroup, where possible, to enable monitoring.

**Comment by vsoch** [comment]
@dtrudg I could work on this more if you want to spec out some details! Or something else, whatever is your preference.

**Comment by dtrudg** [comment]
@vsoch - apologies I've had some other urgent stuff to attend to the end of this week. I will get around to it next week.

**Comment by dtrudg** [comment]
I have replaced the step "Interactive monitoring with a loop that updates every n seconds, showing stats for more all instances" with a full issue here:

https://github.com/sylabs/singularity/issues/892

**Comment by dtrudg** [comment]
I have replaced the step "Calculate % CPU" with a full issue here:

https://github.com/sylabs/singularity/issues/893

Closing this issue as it is now covered by the more detailed separate issues mentioned above.
