### ISSUE TITLE
Confusing 'overlay image format not recognized' error when file is not readable (perms)

### ISSUE THREAD

**Issue by chaseschuette** [sylabs/singularity#786]
**Version of Singularity**
What version of Singularity are you using? Run:

```
$ singularity --version
```
singularity-ce version 3.9.9

**Describe the bug**
FATAL:   while loading overlay images: failed to open overlay image /apps/containers/dev_shm.img: image format not recognized

**To Reproduce**
Steps to reproduce the behavior: While there is significant complexity. Due to the nature of a multi-node environment with a job scheduler. I'm not able to easily reduce the complexity while still being able to execute the job. I separated the arguments below for readability.

I created an image as follows: singularity overlay create --size 1024 dev_shm.img

I have a python script that submits an openPBS job that launches a singularity container. Below is the singulairty command.

singularity --debug 

exec 
--env MOD2_FEATURE_DIRECTORY=chase,IGNORE_GROUND_TRUTH_CHANGES_AFTER_THIS_DATE=Fri May 6 21:33:57 2022_GMT

--bind /mnt/pathfinder/contexts/chase/2022.05.06.Fri.21.34.56_job_3334/rerecord_2/home:/home,/mnt/pathfinder/contexts/chase,/mnt/pathfinder/logs,/mnt/pathfinder/logs/output/,/mnt/lustre/customers/:/mnt/pathfinder/lustre/customers 

--overlay /apps/containers/dev_shm.img 
/apps/containers/pathfinder14.squashfs 

/usr/bin/python /mnt/pathfinder/contexts/chase/software/util/scripts/playback/rerecord.py --task MOD2Play --instance MOD2Play --bookmarkInstanceName MOD2SynBk --output stdout --amendmentSubDir mod2_amendment_chase /mnt/pathfinder/logs/Feature_Development_Data/CatLidarRetraining/MOD2RetrainingLogsFromNorm/Kearl/2018.01/2018.01.11/22.48.47_Obstacle_Detection_r1.1.3_797F_CMD_Configuration_1Obstacle_Empty_2130_2018.01.11_15.49.20/noDetune/MOD2SynBk/MOD2SynBkIndex00000.hlog --expire 3

**Expected behavior**
I need to mount 

**OS / Linux Distribution**
Which Linux distribution are you using?
```
$ cat /etc/os-release
```
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Installation Method**
Write here how you installed SingularityCE. Eg. RPM, source.
Built from source and module loaded with Lmod

**Additional context**
Anything else which might be relevant. E.g. if the bug only occurs on a specific filesystem, or kernel version etc.
Here's the verbose output

*************************************************
FATAL:   while loading overlay images: failed to open overlay image /apps/containers/dev_shm.img: image format not recognized
DEBUG   [U=2089,P=8287]    persistentPreRun()            Singularity version: 3.9.9
DEBUG   [U=2089,P=8287]    persistentPreRun()            Parsing configuration file /apps/singularity/3.9.9/etc/singularity/singularity.conf
DEBUG   [U=2089,P=8287]    handleConfDir()               /home/ahs/schuec1/.singularity already exists. Not creating.
DEBUG   [U=2089,P=8287]    execStarter()                 Saving umask 0077 for propagation into container
DEBUG   [U=2089,P=8287]    execStarter()                 Checking for encrypted system partition
DEBUG   [U=2089,P=8287]    Init()                        Image format detection
DEBUG   [U=2089,P=8287]    Init()                        Check for sandbox image format
DEBUG   [U=2089,P=8287]    Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=2089,P=8287]    Init()                        Check for sif image format
DEBUG   [U=2089,P=8287]    Init()                        sif format initializer returned: SIF magic not found
DEBUG   [U=2089,P=8287]    Init()                        Check for squashfs image format
DEBUG   [U=2089,P=8287]    Init()                        squashfs image format detected
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding PBS_ENVIRONMENT environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding PBS_O_LANG environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding _ModuleTable002_ environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding CAT_DIR environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding OLDPWD environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding PBS_O_HOME environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding PBS_JOBID environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding ENVIRONMENT environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding PBS_JOBNAME environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding NCPUS environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding PBS_O_PATH environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding LMOD_DEFAULT_MODULEPATH environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding S_COLORS environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding AHS_RUNNING_ON_SINGLE_PC environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding PBS_O_WORKDIR environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding USER environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding PBS_NODEFILE environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding PBS_TASKNUM environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding PWD environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding LMOD_COLORIZE environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding LMOD_VERSION environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding PBS_ARRAY_INDEX environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding PBS_MOMPORT environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding LMOD_SETTARG_CMD environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding BASH_ENV environment variable
VERBOSE [U=2089,P=8287]    SetContainerEnv()             Forwarding SINGULARITYENV_LD_LIBRARY_PATH as LD_LIBRARY_PATH environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding PBS_JOBCOOKIE environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding PBS_O_SHELL environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding TMPDIR environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding LMOD_sys environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding _ModuleTable001_ environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding LOADEDMODULES environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding PBS_O_QUEUE environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding LMOD_arch environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding CAT_CONFIG_DIR environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding SHELL environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding PBS_ARRAY_ID environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding _ModuleTable_Sz_ environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding SHLVL environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding PBS_O_HOST environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding PBS_O_SYSTEM environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding MANPATH environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding LMOD_PREPEND_BLOCK environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding PBS_O_LOGNAME environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding PBS_NODENUM environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding MODULEPATH environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding PBS_JOBDIR environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding LOGNAME environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding MODULEPATH_ROOT environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding _LMFILES_ environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding PBS_QUEUE environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding MODULESHOME environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding LMOD_PKG environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding LMOD_CMD environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding PBS_O_MAIL environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding OMP_NUM_THREADS environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding LMOD_FULL_SETTARG_SUPPORT environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding LMOD_DIR environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding BASH_FUNC_module%% environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding BASH_FUNC_ml%% environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding _ environment variable
DEBUG   [U=2089,P=8287]    SetContainerEnv()             Forwarding USER_PATH environment variable
VERBOSE [U=2089,P=8287]    SetContainerEnv()             Forwarding SINGULARITYENV_MOD2_FEATURE_DIRECTORY as MOD2_FEATURE_DIRECTORY environment variable
VERBOSE [U=2089,P=8287]    SetContainerEnv()             Forwarding SINGULARITYENV_IGNORE_GROUND_TRUTH_CHANGES_AFTER_THIS_DATE as IGNORE_GROUND_TRUTH_CHANGES_AFTER_THIS_DATE environment variable
VERBOSE [U=2089,P=8287]    SetContainerEnv()             Setting HOME=/home/ahs/schuec1
VERBOSE [U=2089,P=8287]    SetContainerEnv()             Setting PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DEBUG   [U=2089,P=8287]    init()                        Use starter binary /apps/singularity/3.9.9/libexec/singularity/bin/starter-suid
DEBUG   [U=2089,P=8287]    Exec()                        Setting GOGC=off for starter
VERBOSE [U=0,P=8287]       print()                       Set messagelevel to: 5
VERBOSE [U=0,P=8287]       init()                        Starter initialization
DEBUG   [U=0,P=8287]       load_overlay_module()         Trying to load overlay kernel module
DEBUG   [U=0,P=8287]       load_overlay_module()         Overlay seems supported by the kernel
VERBOSE [U=0,P=8287]       is_suid()                     Check if we are running as setuid
VERBOSE [U=0,P=8287]       priv_drop()                   Drop root privileges
DEBUG   [U=2089,P=8287]    read_engine_config()          Read engine configuration
DEBUG   [U=2089,P=8287]    cleanenv()                    Clearing env var LOAD_OVERLAY_MODULE=1
DEBUG   [U=2089,P=8287]    cleanenv()                    Keeping env var SINGULARITY_MESSAGELEVEL=95
DEBUG   [U=2089,P=8287]    cleanenv()                    Clearing env var ENGINE_CONFIG1={"engineName":"singularity","containerID":"","engineConfig":{"jsonConfig":{"overlayImage":["/apps/containers/dev_shm.img"],"bindpath":[{"source":"/mnt/pathfinder/contexts/chase/2022.05.06.Fri.21.34.56_job_3334/rerecord_2/home","destination":"/home","options":null},{"source":"/mnt/pathfinder/contexts/chase","destination":"/mnt/pathfinder/contexts/chase","options":null},{"source":"/mnt/pathfinder/logs","destination":"/mnt/pathfinder/logs","options":null},{"sourc(TRUNCATED...)DEBUG   [U=2089,P=8287]    cleanenv()                    Clearing env var ENGINE_CONFIG_CHUNKS=1
DEBUG   [U=2089,P=8287]    cleanenv()                    Keeping env var GOGC=off
DEBUG   [U=2089,P=8287]    init()                        Wait completion of stage1
VERBOSE [U=2089,P=8314]    priv_drop()                   Drop root privileges permanently
DEBUG   [U=2089,P=8314]    set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=2089,P=8314]    init()                        Spawn stage 1
DEBUG   [U=2089,P=8314]    startup()                     singularity runtime engine selected
VERBOSE [U=2089,P=8314]    startup()                     Execute stage 1
DEBUG   [U=2089,P=8314]    StageOne()                    Entering stage 1
DEBUG   [U=2089,P=8314]    prepareAutofs()               Found "/proc/sys/fs/binfmt_misc" as autofs mount point
DEBUG   [U=2089,P=8314]    prepareAutofs()               Could not keep file descriptor for user bind path /mnt/pathfinder/contexts/chase/2022.05.06.Fri.21.34.56_job_3334/rerecord_2/home: no mount point
DEBUG   [U=2089,P=8314]    prepareAutofs()               Could not keep file descriptor for user bind path /mnt/pathfinder/contexts/chase: no mount point
DEBUG   [U=2089,P=8314]    prepareAutofs()               Could not keep file descriptor for user bind path /mnt/pathfinder/logs: no mount point
DEBUG   [U=2089,P=8314]    prepareAutofs()               Could not keep file descriptor for user bind path /mnt/pathfinder/logs/output/: no mount point
DEBUG   [U=2089,P=8314]    prepareAutofs()               Could not keep file descriptor for user bind path /mnt/lustre/customers/: no mount point
DEBUG   [U=2089,P=8314]    prepareAutofs()               Could not keep file descriptor for bind path /etc/localtime: no mount point
DEBUG   [U=2089,P=8314]    prepareAutofs()               Could not keep file descriptor for bind path /etc/hosts: no mount point
DEBUG   [U=2089,P=8314]    prepareAutofs()               Could not keep file descriptor for home directory /home/ahs/schuec1: no mount point
DEBUG   [U=2089,P=8314]    prepareAutofs()               Could not keep file descriptor for current working directory /mnt/pathfinder/contexts/chase/software/bin: no mount point
DEBUG   [U=2089,P=8314]    Init()                        Image format detection
DEBUG   [U=2089,P=8314]    Init()                        Check for sandbox image format
DEBUG   [U=2089,P=8314]    Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=2089,P=8314]    Init()                        Check for sif image format
DEBUG   [U=2089,P=8314]    Init()                        sif format initializer returned: SIF magic not found
DEBUG   [U=2089,P=8314]    Init()                        Check for squashfs image format
DEBUG   [U=2089,P=8314]    Init()                        squashfs image format detected
DEBUG   [U=2089,P=8314]    setSessionLayer()             Overlay seems supported and allowed by kernel
DEBUG   [U=2089,P=8314]    setSessionLayer()             Attempting to use overlayfs (enable overlay = try)
DEBUG   [U=2089,P=8314]    Init()                        Image format detection
DEBUG   [U=2089,P=8314]    Init()                        Check for sandbox image format
DEBUG   [U=2089,P=8314]    Init()                        Check for sif image format
DEBUG   [U=2089,P=8314]    Init()                        Opening /apps/containers/dev_shm.img in read-only mode: no write permissions
DEBUG   [U=2089,P=8314]    Init()                        Check for squashfs image format
DEBUG   [U=2089,P=8314]    Init()                        Check for ext3 image format
DEBUG   [U=2089,P=8314]    Init()                        Opening /apps/containers/dev_shm.img in read-only mode: no write permissions
FATAL   [U=2089,P=8314]    StageOne()                    while loading overlay images: failed to open overlay image /apps/containers/dev_shm.img: image format not recognized
VERBOSE [U=2089,P=8287]    wait_child()                  stage 1 exited with status 255

**Comment by dtrudg** [comment]
Please try...

```
singularity pull library://ubuntu:latest

singularity --debug exec --overlay /apps/containers/dev_shm.img ubuntu_latest.sif /bin/true
```

Also what does..

```
file  /apps/containers/dev_shm.img
```

Show?

The overlay image doesn't have write permissions - which is odd given it was created by you also. Did you run the overlay create as a different user, or is there a r/o filesystem involved here?

```
Opening /apps/containers/dev_shm.img in read-only mode: no write permissions
```

**Comment by chaseschuette** [comment]
I pulled the latest ubuntu and ran that singularity command in and out of a PBS job script

[in_PBS.txt](https://github.com/sylabs/singularity/files/8647884/in_PBS.txt)
[out_PBS.txt](https://github.com/sylabs/singularity/files/8647885/out_PBS.txt)

The image was created with root. It's a shared file space /apps/containers across all nodes.
![image](https://user-images.githubusercontent.com/15070206/167317171-bcc2a363-d890-4a07-9448-bfaa0519f8d6.png)

**Comment by dtrudg** [comment]
You are running singularity as user 2089, but that user has no permission to access the dev_shm.img file.

The screenshot shows that only root has permissions (rw) to access the file. No other user will be able to use it.

If you are running singularity not as the root user then it's expected that this won't work. It is a bug, however, that the error message is not more specific.

**Comment by chaseschuette** [comment]
I updated the permissions of dev_shm.img to:

-rwxrwxrwx 1 root           pathfinder 1073741824 May  4 10:18 dev_shm.img

All users are included in the pathfinder group. I'm now getting this error.

singularity --debug exec --overlay /apps/containers/dev_shm.img ubuntu_latest.sif /bin/true
singularity: symbol lookup error: singularity: undefined symbol: seccomp_notify_free

**Comment by dtrudg** [comment]
>singularity: symbol lookup error: singularity: undefined symbol: seccomp_notify_free

Singularity has been deployed on a system with a version of libseccomp which is older than the machine it was built on. You can either:

- Update libseccomp on the system it is deployed on
- Compile singularity on a machine with a matching older version of libseccomp
- Build singularity without libseccomp support (--without-seccomp flag for mconfig)

libseccomp has been updated in most long-term-supported distributions, to a version with additional symbols, for security reasons. Therefore we'd advise updating libseccomp.

**Comment by dtrudg** [comment]
NB - the fact the other error went away shows the original case was a read permission error, and we just need to check for that and output a sensible error message. I'll take care of that asap.

**Comment by chaseschuette** [comment]
[debug.txt](https://github.com/sylabs/singularity/files/8655040/debug.txt)

I cleared out and rebuilt 3.9.9 from source with --without-seccomp option. Above is the output from outside of a PBS job

**Comment by chaseschuette** [comment]
However, inside of a PBS job I get this output.
[process-output.txt](https://github.com/sylabs/singularity/files/8655052/process-output.txt)

**Comment by dtrudg** [comment]
> However, inside of a PBS job I get this output. [process-output.txt](https://github.com/sylabs/singularity/files/8655052/process-output.txt)
> 
> Looks like I have a I/O conflict

This error is returned if an attempt to lock the file returns the EAGAIN or EACCES error codes. It would generally indicate another process is using the overlay. Only one process can access a writable ext3 filesystem at a time. It is possible, however,  that a filesystem might unexpectedly return one of these codes for another error... it depends what the filesystem is underneath.

PR #788 will fix the original misleading error related to the image file not having correct permissions. The remaining issue isn't really something that SingularityCE can address.
