### ISSUE TITLE
Singularity not honoring DOCKER_HOST env var when building from local image

### ISSUE THREAD

**Issue by rkcroc** [sylabs/singularity#805]
**Version of Singularity**
What version of Singularity are you using? Run:
singularity-ce version 3.9.9

**Describe the bug**
Attempting to build a SIF from locally cached Docker image fails unexpectedly, claiming incorrectly that Docker isn't running.

My `docker.sock` is in a non-standard place, allowing me to run from multiple WSL2 instances. This is handled by setting the DOCKER_HOST env var in each instance. 

**To Reproduce**
```
singularity build pfoam-of7.sif docker-daemon://pfoam:of7
INFO:    Starting build...
FATAL:   While performing build: conveyor failed to get: loading image from docker engine: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
env | grep DOCKER
DOCKER_HOST=unix:///mnt/wsl/docker/docker.sock
docker images
REPOSITORY    TAG       IMAGE ID       CREATED        SIZE
pfoam         of7       cbd4a9a2bbcf   2 hours ago    3.97GB
```

**Expected behavior**
Build the SIF.

If I create a symlink at /var/run/docker.sock to the actual sock file, it works. This shouldn't be necessary. IMO.

**OS / Linux Distribution**
Ubuntu 20.04.4 LTS (via WSL2)

**Installation Method**
Source

**Additional context**
None

**Comment by dtrudg** [comment]
containers/image is exposing support to enable implementing this since https://github.com/containers/image/pull/328/files#diff-82dcbdf0c5e08c6efa6f74c22e3ac6b9b1efd5f4bff27b8bdf68d8286c40b961R23

We can add the handling into our code.

**Comment by muffato** [comment]
Thank you very much ! 🙏🏼
