### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by xhzy940301** [sylabs/singularity#806]
*Note*: We encourage questions about usage of SingularityCE to be made via the Google Group or Slack channels. Other users frequent these communities, and may already have the answer to your question!

See: https://sylabs.io/singularity#community for links.

**Type of issue**
E.g. install problem

I try to install singularity-3.8.4 without as a non-root user. I followed the following steps to install it:
./mconfig --without-setuid --prefix=/home/singularity &&
make -C ./builddir &&
make -C ./builddir install
When I run the last step, it reports the following error:
![image](https://user-images.githubusercontent.com/57342415/168521793-efd6e93e-3c8b-4bb5-8adf-0e61faee291d.png)

**Comment by tri-adam** [comment]
Hello @xhzy940301, it looks like you do not have privilege to create the installation directory that you have specified (`/home/singularity`). You will need to specify a location that you can access, such as one in `$HOME`, for example:

```
$ ./mconfig --without-suid --prefix="${HOME}/singularity"
...
$ make -C ./builddir
...
$ make -C ./builddir install
make: Entering directory '/home/adam/src/singularity/builddir'
 INSTALL /home/adam/singularity/bin/singularity
...
```

Hope that helps!

**Comment by xhzy940301** [comment]
> Hello @xhzy940301, it looks like you do not have privilege to create the installation directory that you have specified (`/home/singularity`). You will need to specify a location that you can access, such as one in `$HOME`, for example:
> 
> ```
> $ ./mconfig --without-suid --prefix="${HOME}/singularity"
> ...
> $ make -C ./builddir
> ...
> $ make -C ./builddir install
> make: Entering directory '/home/adam/src/singularity/builddir'
>  INSTALL /home/adam/singularity/bin/singularity
> ...
> ```
> 
> Hope that helps!

Hello @tri-adam ，Thank you very much, that helps! And I installed it successfully as you suggested.

Best wishes
