### ISSUE TITLE
Monitor / include progress on CDI based nvidia container setup

### ISSUE THREAD

**Issue by dtrudg** [sylabs/singularity#813]
The nvidia-container-toolkit mediated setup of GPU containers for CUDA and other work will be transitioning toware an approach that leverages the CDI (container device interface) standard.

https://github.com/container-orchestrated-devices/container-device-interface

Monitor this work and consider adoption.

**Comment by dtrudg** [comment]
Continuing to monitor this. No action is necessary for 3.11 at this time.

**Comment by elezar** [comment]
@dtrudg with the NVIDIA Container Toolkit `v1.12.0` release we have included tooling to generate CDI specifications. We are also updating our documentation to recommend this as the way to access NVIDIA devices when using Podman which offers CDI support as of `v4.1.0`.

What is required to get CDI as the recommended way to inject NVIDIA devices when using OCI mode?

**Comment by dtrudg** [comment]
Hi @elezar - thanks for noting this issue and getting in touch!

We had postponed work on CDI until such time as there was tooling generating a CDI specification, as your v1.12.0 does. Consequently, there's nothing in SingularityCE at present that is handling CDI specifications... but as the issue notes, it is a roadmap item for the 4.0 release.

To integrate CDI support in SingularityCE's `--oci` mode shouldn't be too difficult. We have launcher code that constructs an OCI runtime config for the container that is executed. I don't believe it'll be all that much different from implementation in podman.

Per out-of-band comms by email, it'd be great to have a chat about this, and we can sort out when the work will be able to take place. Thanks!

**Comment by ArangoGutierrez** [comment]
++

**Comment by dtrudg** [comment]
Going to close this in favor of #1394 and #1395 ... now we are moving forward with CDI in OCI mode, and wish to consider it somewhat separately for the singularity native runtime.

Thanks for your input @elezar et al.
