### ISSUE TITLE
fail-to-set-ambient-capability in build post on CentOS7 with old centosplus kernel

### ISSUE THREAD

**Issue by DrOllyGomez** [sylabs/singularity#844]
**Version of Singularity**
What version of Singularity are you using? 

singularity-ce version 3.10.0-1.el7

**Describe the bug**

Regardless of whether I use the yum bootstrap agent or the debootstrap agent,
whilst 
-I am able to install base systems eg CentOS7, Ubuntu16, Ubuntu20
-I am unable to install any further software at the %post scriptlet stage

Running as root, I make the call to singularity build with a def file, (using either of the two agents named above),
and I get output like this:

-many I:configuring things etc-
I: Configuring libapt-pkg6.0:amd64...
I: Configuring apt...
I: Configuring libc-bin...
I: Base system installed successfully.
INFO:    Running post scriptlet
ERROR  : Failed to set ambient capability: Invalid argument
FATAL:   While performing build: while running engine: exit status 1

I reiterate that I can make .sif images successfully with base systems, I can shell into them and look around them.

**To Reproduce**

This minimal def file creates the error....
Bootstrap: debootstrap
OSVersion: focal
MirrorURL: http://mirror.bytemark.co.uk/ubuntu/
%post
  apt-get update && apt-get install -y wget

The same file without the %post section label and scriptlet do not produce the error,
and produce a working sif container.

**Expected behavior**

A .sif will be created, that I can shell into, and use the wget program

**OS / Linux Distribution**
Which Linux distribution are you using?

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Installation Method**
Write here how you installed SingularityCE. Eg. RPM, source.

I used:

wget https://github.com/sylabs/singularity/releases/download/v3.10.0/singularity-ce-3.10.0-1.el7.x86_64.rpm

then

yum install ./singularity-ce-3.10.0-1.el7.x86_64.rpm

I will attached a text file that contains the output to the console of the install process

**Additional context**
1.I read in...
https://sylabs.io/guides/latest/user-guide/appendix.html#debootstrap-build-agent
.. that on a Centos system, to use the debootstrap agent, its necessary to install deboostrap on the build system with:
sudo yum update && sudo yum install epel-release && sudo yum install debootstrap.noarch
...so I have done that, FWIW.
I reiterate that the problem seems to be generic, it happens with the yum agent also.

2.FWIW I have seen a comment:
W: Cannot check Release signature; keyring file not available /usr/share/keyring                                                                                                                s/ubuntu-archive-keyring.gpg

Many thanks in advance for a fix, any help, comments, and any requests on how to diagnose the problem further.
[install.txt](https://github.com/sylabs/singularity/files/8839949/install.txt)

**Comment by DrOllyGomez** [comment]
Hiya. Thanks for the reply.

$uname -a
3.10.0-327.36.3.el7.centos.plus.x86_64 #1 SMP Tue Oct 25 03:09:35 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

attaching output of debug build...
[debugout.txt](https://github.com/sylabs/singularity/files/8846346/debugout.txt)

**Comment by dtrudg** [comment]
> 3.10.0-327.36.3.el7.centos.plus.x86_64 https://github.com/sylabs/singularity/pull/1 SMP Tue Oct 25 03:09:35 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

This is an extremely old (Oct 2016) kernel build, and not one we would be testing against. Note also that it is a centos plus kernel, where centos plus states...

> These packages are not part of the upstream distribution and extend CentOS's functionality at the expense of upstream compatibility.

Are you able to verify against the current CentOS 7 stock kernel, which is:

`kernel-3.10.0-1160.66.1.el7.x86_64`

**Comment by DrOllyGomez** [comment]
ok, understood the point about the kernel. I will see if I can change, but not sure when.
>Are you able to verify against the current CentOS 7 stock kernel, 
as above, probably, but maybe not soon. Probably best to close this ticket?
Thanks for your comments.

**Comment by dtrudg** [comment]
Let's keep the ticket open - if I have an hour to try and replicate this week, I will take a look.

**Comment by dtrudg** [comment]
Attempting a reproducer on a RHEL7 install that isn't quite current, but has a Nov 2021 kernel...

```
06:02 PM $ singularity --version
singularity-ce version 3.10.0-1.el7

06:02 PM $ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.9 (Maipo)

06:02 PM $ uname -a
Linux dev-rhel7 3.10.0-1160.49.1.el7.x86_64 #1 SMP Tue Nov 9 16:09:48 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

```
06:04 PM $ cat debootstrap.def 
Bootstrap: debootstrap
OSVersion: focal
MirrorURL: http://mirror.bytemark.co.uk/ubuntu/

%post
   apt-get update && apt-get install -y wget
```

```
$ sudo singularity build debootstrap.sif debootstrap.def 
INFO:    Starting build...
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/ubuntu-archive-keyring.gpg
...
I: Base system installed successfully.
INFO:    Running post scriptlet
+ apt-get update
...
done.
INFO:    Creating SIF file...
INFO:    Build complete: debootstrap.sif
```

As seen above, it completes without issue.

Without having had any other reports, I believe this is going to be due to the very old centosplus kernel, and I'm afraid putting in a workaround for a kernel that is outdated and subject to security issues isn't something we're likely to do.

**Comment by DrOllyGomez** [comment]
Understood. Many thanks for demo and info.
Best.
Mike
________________________________
