### ISSUE TITLE
mconfig can't find go

### ISSUE THREAD

**Issue by aroffringa** [sylabs/singularity#853]
**Version of Singularity**
problem occurs with versions 3.9.5, 3.9.9, 3.10.0  (from git).

**Describe the bug**
Running mconfig results in a rather unhelpful:
```
 checking: host Go compiler (at least version 1.17)... not found!
```
while go is installed according to the instructions in `INSTALL`, and `go version` reports `go version go1.17.6 linux/amd64`. I have no idea how to debug this.

**To Reproduce**
Follow steps of INSTALL.md on a Debian (testing) system.

**Expected behavior**
mconfig finds go.

**OS / Linux Distribution**
Which Linux distribution are you using?
```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux bookworm/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Installation Method**
From git

**Comment by dtrudg** [comment]
This is very odd. I'm not able to reproduce it here. I've just copied/pasted from the `INSTALL.md` on a clean Debian bookworm/sid environment and.... 

```
root@29323f458e14:/singularity# ./mconfig -v
Configuring for project `singularity-ce' with languages: C, Golang
=> running pre-basechecks project specific checks ...
=> running base system checks ...
 checking: host C compiler... cc
 checking: host C++ compiler... c++
 checking: host Go compiler (at least version 1.17)... /usr/local/go/bin/go
```

Any output from `env | grep GO` / `which go` / `go env` .... might be useful.

Also - if you installed a different version of Go over an existing one, that can cause issues. The existing version must be completely removed first.

**Comment by aroffringa** [comment]
I initially followed https://github.com/sylabs/singularity/blob/v3.9.9/INSTALL.md . Now I followed the INSTALL.md in master, which as far as I can see is only different in how it checks out singularity (using `--recurse-submodules`), and it works now. Are the submodules the issue?

I didn't have a `/usr/local/go` dir before, so that wasn't the issue. `which go` reported `/usr/local/go/bin/go` and `env|grep GO` reported `GOPATH=/home/anoko/go` (which is also correct), so all seemed to be correct. So all in all a bit confusing; solved for me but the error seems a bit random. Thanks for the help though!

**Comment by dtrudg** [comment]
> I initially followed https://github.com/sylabs/singularity/blob/v3.9.9/INSTALL.md . Now I followed the INSTALL.md in master, which as far as I can see is only different in how it checks out singularity (using `--recurse-submodules`), and it works now. Are the submodules the issue?

The submodules are only required for 3.10 and above - there aren't any submodules to clone for 3.9.x, so shouldn't be an issue.

> I didn't have a `/usr/local/go` dir before, so that wasn't the issue. `which go` reported `/usr/local/go/bin/go` and `env|grep GO` reported `GOPATH=/home/anoko/go` (which is also correct), so all seemed to be correct. So all in all a bit confusing; solved for me but the error seems a bit random. Thanks for the help though!

This is odd - I'm not sure where that could have become fixed like that. If you experience anything again, please let us know. Thanks.

**Comment by arovai** [comment]
I run into a similar issue, attempting to install singularity v3.10.3.
Used to have an older version of go, but has been removed in the process of installing the newer version, following what's in INSTALL.md, in particular the last line:
```
sudo tar -C /usr/local -xzf /tmp/go${VERSION}.${OS}-${ARCH}.tar.gz
```
Now:
```
go version
```
returns 1.19.2; as a cross check I did `cat /usr/local/go/VERSION` and got the same.
```
./mconfig
```
in the singularity clone returns
```
(...)
checking: host Go compiler (at least version 1.17)... not found!
```
More checks:
```
go env GOPATH
```
return `/home/arovai/go`
and 
```
which go
```
gives
```
/usr/local/go/bin/go
```

**Comment by dtrudg** [comment]
@arovai - did you explicitly remove the old version of go, or just untar the new version over the old?

When updating go you must completely remove the directory containing the old version, as untarring a new version will leave pieces of the old version in place, where files have moved / been renamed. This can cause problems when compiling programs even if the `go` binary itself seems to work.

**Comment by arovai** [comment]
Worked, thanks.

**Comment by dtrudg** [comment]
I'm going to mark this issue closed, with the advice to remove a prior go version copletely fixing one of the observed issues.

If you hit the problem and you have done this, please feel free to re-open. Thanks.

**Comment by skakswkdhgkfl** [comment]
checking: host Go compiler (at least version 1.20)... not found!
mconfig: could not complete configuration

can anyone pls get me out of this?

**Comment by audjoselo** [comment]
> Worked, thanks.

Hi, excuse me, maybe could you tell me how made it work. Thanks in advance.

**Comment by dtrudg** [comment]
The problem is usually as described above:

> did you explicitly remove the old version of go, or just untar the new version over the old?

> When updating go you must completely remove the directory containing the old version, as untarring a new version will leave pieces of the old version in place, where files have moved / been renamed. This can cause problems when compiling programs even if the go binary itself seems to work.

**Comment by audjoselo** [comment]
> The problem is usually as described above:
> 
> > did you explicitly remove the old version of go, or just untar the new version over the old?
> 
> > When updating go you must completely remove the directory containing the old version, as untarring a new version will leave pieces of the old version in place, where files have moved / been renamed. This can cause problems when compiling programs even if the go binary itself seems to work.

Thank you for your answer. Actually, I performed a clean installation so I didn't understand what happened. Finally I decided to install it from the Snap Store using the following codes. The first one is for the installation of Go and the second one to correct some packages. 

sudo snap install go --classic
sudo apt-get install libfuse-dev libfuse3-dev

However, the installation of singularity is still not achievable

**Comment by audjoselo** [comment]
> sudo snap install go --classic
> sudo apt-get install libfuse-dev libfuse3-dev

Try these:

sudo snap install go --classic
sudo apt-get install libfuse-dev libfuse3-dev

**Comment by dtrudg** [comment]
> > The problem is usually as described above:
> > > did you explicitly remove the old version of go, or just untar the new version over the old?
> > 
> > 
> > > When updating go you must completely remove the directory containing the old version, as untarring a new version will leave pieces of the old version in place, where files have moved / been renamed. This can cause problems when compiling programs even if the go binary itself seems to work.
> 
> Thank you for your answer. Actually, I performed a clean installation so I didn't understand what happened. Finally I decided to install it from the Snap Store using the following codes. The first one is for the installation of Go and the second one to correct some packages.
> 
> sudo snap install go --classic sudo apt-get install libfuse-dev libfuse3-dev
> 
> However, the installation of singularity is still not achievable

Please open a new issue - this one is closed and is specific to a problem where someone had installed a new go over the top of an old one.

You'll need to provide full details of exactly how you tried to install go, and the full output of `mconfig`.

**Comment by stevekm** [comment]
I had this issue and the culprit was that my .bashrc in Ubuntu 24.04 included some parts at the top that exited without setting the environment when run in a non-interactive shell. Because I was running it from inside an Ansible playbook. The solution looked like this

```yaml
  - name: Configure & Compile Singularity source code
    shell: |
      sudo -iu {{ ansible_user_id }} bash -c '
      cd ~/singularity-ce-{{ singularity_version }};
      ./mconfig;
      make -C ./builddir;
      sudo make -C ./builddir install;
      '
    args:
      creates: /usr/local/bin/singularity
    register: compile_singularity

```

**Comment by blik616287** [comment]
What the fuck is this garbage?
