### ISSUE TITLE
.deb pre-release versions must use ~ not - for pre-release separator

### ISSUE THREAD

**Issue by gdevenyi** [sylabs/singularity#862]
I had this version installed:
`ii  singularity-ce                                3.10.0-rc.2-jammy                           `

and then tried to install:
`singularity-ce_3.10.0-jammy_amd64.deb`

But `gdebi -n singularity-ce_3.10.0-jammy_amd64.deb` reports:
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
This package is uninstallable
A later version is already installed
```

See https://unix.stackexchange.com/questions/97289/debian-package-naming-convention for more details on naming

**Comment by dtrudg** [comment]
This needs to be setup so the `-rc` (correct for rpm) is modified to `~rc` for Debian packaging... here...

https://github.com/sylabs/singularity/blob/c5dc33d68b10228b583bade8d91add3da9d576ff/debian/rules#L40

**Comment by dtrudg** [comment]
Not immediately critical, but should be a blocker for 3.11 RCs closer to November.
