### ISSUE TITLE
Runscript is being timed out after 1m0s

### ISSUE THREAD

**Issue by P-Sood** [sylabs/singularity#877]
### What happened:
I am trying to run a python file in a singularity container. I am able to run it using the code
```
singularity exec pixplot.sif python3.6 pixplot/utils/process_images.py datasets/oslomini/images/*
```
I am trying to remove the python 3.6 part and make the command
```
singularity run pixplot.sif datasets/oslomini/images/*
```
I have modified the bash file, to look like this:
```bash
#!/bin/sh
OCI_ENTRYPOINT=""

OCI_CMD='"bash"'

CMDLINE_ARGS=""

# prepare command line arguments for evaluation

for arg in "$@"; do

    CMDLINE_ARGS="${CMDLINE_ARGS} \"$arg\""

done



# ENTRYPOINT only - run entrypoint plus args

if [ -z "$OCI_CMD" ] && [ -n "$OCI_ENTRYPOINT" ]; then

    if [ $# -gt 0 ]; then

        SINGULARITY_OCI_RUN="${OCI_ENTRYPOINT} ${CMDLINE_ARGS}"

    else

        SINGULARITY_OCI_RUN="${OCI_ENTRYPOINT}"

    fi

fi



# CMD only - run CMD or override with args

if [ -n "$OCI_CMD" ] && [ -z "$OCI_ENTRYPOINT" ]; then

    if [ $# -gt 0 ]; then

        SINGULARITY_OCI_RUN= python3.6 pixplot/utils/process_images.py ${CMDLINE_ARGS}

    else

        SINGULARITY_OCI_RUN="${OCI_CMD}"

    fi

fi



# ENTRYPOINT and CMD - run ENTRYPOINT with CMD as default args

# override with user provided args

if [ $# -gt 0 ]; then

    SINGULARITY_OCI_RUN="${OCI_ENTRYPOINT} ${CMDLINE_ARGS}"

else

    SINGULARITY_OCI_RUN="${OCI_ENTRYPOINT} ${OCI_CMD}"

fi



# Evaluate shell expressions first and set arguments accordingly,

# then execute final command as first container process

eval "set ${SINGULARITY_OCI_RUN}"

exec "$@"
```
Now the run command works, however it keeps timing out in the middle and never finishes its task. I just want to make this as easy as possible for people in my lab. Any advice on how to bypass this timeout issue on a run command?

###**Version of Singularity:**
What version of Singularity are you using? Run: 3.8.4
```
$ singularity --version
3.8.4
```
###**Expected behavior**
I expected my code to fully run the script, and not be timed out

###**Actual behavior**
```
FATAL:   command "python3.6 pixplot/utils/process_images.py datasets/oslomini/images/* was killed after 1m0s timeout
It timed out in the middle
```

###**Steps to reproduce this behavior**

Have a command set up in bash script that takes more then a minute I assume

###**What OS/distro are you running**
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

###**How did you install Singularity**
I cloned it in

**Comment by dtrudg** [comment]
What is the source of the pixplot container? We need to know exactly what the container is to be able to advise on this.

Also you say that you modified the bash script? I think you have changed the run script - but we need confirmation of exactly which file you have changed in the container.

**Comment by P-Sood** [comment]
1)
```bash
# Specify base image
FROM ubuntu:20.04

# Specify author \ maintainer
MAINTAINER Pranav Sood <prsood@sfu.ca>

##
# Install Python
##

# Add repository that contains Python 3.6
RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update

# Install Python 3.6
RUN apt-get install -y build-essential \
  python3.6 \
  python3.6-dev \
  python3-pip \
  python3.6-venv

# Update pip
RUN python3.6 -m pip install pip --upgrade
RUN python3.6 -m pip install wheel

##
# Install ImageMagick
##

RUN apt-get install -y imagemagick

##
# Copy source files
##

ENV APP_PATH="pixplot"
RUN mkdir "$APP_PATH"
ADD . "$APP_PATH"

##
# Install PixPlot dependencies
##

RUN cd "$APP_PATH" && \
  python3.6 -m pip install -r "pixplot/utils/requirements.txt"

```

After that I used the commands below:

```bash
sudo docker build -t pixplot .
sudo singularity build pixplot.sif docker-daemon:pixplot:latest
```

I was able to create a singularity file from a docker container



2)
I used the commands below to create a sandbox and then modify the bash script above in the OP.
```bash
sudo singularity build --sandbox orig_sandbox pixplot.sif
sudo singularity shell --writable orig_sandbox
sudo vi orig_sandbox/singularity 
```

**Comment by dtrudg** [comment]
Here is the issue:

```
 SINGULARITY_OCI_RUN= python3.6 pixplot/utils/process_images.py ${CMDLINE_ARGS}
 ```
 
 You have a space between the `=` and the `python3.6`. That instructs the shell to run `python3.6`, with `SINGULARITY_OCI_RUN` set to nothing.
 
 When you are setting a value for a variable in a shell script, the value must be directly after the `=` sign, with no space. If the value includes spaces you should also wrap it with quotes.
 
```
SINGULARITY_OCI_RUN="python3.6 pixplot/utils/process_images.py ${CMDLINE_ARGS}"
```

Generally I would advise not editing the complex generic OCI/Docker runscript by hand, but instead building from a definition file that replaces it with a simplified form, including only you want to do. E.g.

```
Bootstrap: docker-daemon
From: pixplot:latest

%runscript
     <insert what you want to run here>
```

If you need additional help, please refer to the Google Group, or Slack Channel. As this is not a bug in Singularity, but a matter of how a container is created & used. Thanks!

**Comment by P-Sood** [comment]
Thanks @dtrudg !
