### ISSUE TITLE
Instance stats interactive monitoring

### ISSUE THREAD

**Issue by dtrudg** [sylabs/singularity#892]
**Is your feature request related to a problem? Please describe.**

The `instance stats` command shows a point-in-time snapshot of instance resource usage. Often we really want to monitor how resource use is changing.

**Describe the solution you'd like**

Running the `instance stats` command should default to an interactive mode, where the resource usage is displayed, updated every second, until the user exits wtih Ctrl+c.

There should be a `--no-stream ` flag (compatible with the docker/podman CLI) to disable this interactive mode. With `--no-stream` the behavior should be as it is now - show the point-in-time usage, and exit.

**Additional context**

This is CLI level functionality to be implemented in `cmd/internal/cli/instance_stats_linux.go`.

**Comment by vsoch** [comment]
oooh ooh assign mee! <3
