### ISSUE TITLE
ERROR while Compiling Singularity

### ISSUE THREAD

**Issue by jiangzhangze** [sylabs/singularity#911]
**Version of Singularity**
What version of Singularity are you using? Run:
Compiling Singularity
```
$ singularity --version
```

**Describe the bug**
When configuring, building, and installing Singularity using the following commands:
`./mconfig
cd ./builddir
make
sudo make install`
error：
` GO singularity
    [+] GO_TAGS "containers_image_openpgp sylog oci_engine singularity_engine fakeroot_engine apparmor selinux seccomp"
# github.com/sylabs/singularity/internal/pkg/plugin
../internal/pkg/plugin/meta.go:26:21: undefined: buildcfg.PLUGIN_ROOTDIR
../internal/pkg/plugin/create.go:98:32: undefined: buildcfg.SOURCEDIR
../internal/pkg/plugin/create.go:100:105: undefined: buildcfg.SOURCEDIR
../internal/pkg/plugin/create.go:106:32: undefined: buildcfg.SOURCEDIR
../internal/pkg/plugin/module.go:151:42: undefined: buildcfg.SOURCEDIR
# github.com/sylabs/singularity/internal/pkg/util/bin
../internal/pkg/util/bin/bin.go:37:23: undefined: buildcfg.SINGULARITY_CONF_FILE
../internal/pkg/util/bin/bin.go:53:14: undefined: buildcfg.CRYPTSETUP_PATH
../internal/pkg/util/bin/bin.go:70:15: undefined: buildcfg.CRYPTSETUP_PATH
../internal/pkg/util/bin/bin.go:74:19: undefined: buildcfg.CRYPTSETUP_PATH
# github.com/sylabs/singularity/internal/pkg/util/starter
../internal/pkg/util/starter/starter.go:59:36: undefined: buildcfg.LIBEXECDIR
../internal/pkg/util/starter/starter.go:62:35: undefined: buildcfg.LIBEXECDIR
../internal/pkg/util/starter/starter.go:118:34: undefined: buildcfg.LIBEXECDIR
# github.com/sylabs/singularity/internal/pkg/util/fs/squashfs
../internal/pkg/util/fs/squashfs/squashfs.go:25:26: undefined: buildcfg.SINGULARITY_CONF_FILE
make: *** [Makefile:172: singularity] Error 2`
**To Reproduce**
After completing the `./mconfig` command, run the command `make` in the folder builddir
**Expected behavior**

**OS / Linux Distribution**
Which Linux distribution are you using?
```
$ cat /etc/os-release
```

**Installation Method**
Write here how you installed SingularityCE. Eg. RPM, source.
https://github.com/apptainer/singularity/blob/master/INSTALL.md
**Additional context**
Anything else which might be relevant. E.g. if the bug only occurs on a specific filesystem, or kernel version etc.

**Comment by dtrudg** [comment]
Hi @jiangzhangze 

If you are following https://github.com/apptainer/singularity/blob/master/INSTALL.md as indicated then that is for the repository at https://github.com/apptainer/singularity - this is SingularityCE, which is a different (forked) project.

Please open an issue with apptainer, if you are attempting to install apptainer.

If you have the problem whilst installing SingularityCE with the guide at https://github.com/sylabs/singularity/blob/main/INSTALL.md then let us know your operating system information, and the version of Go you have and we can help out.

**Comment by dtrudg** [comment]
@jiangzhangze - okay, thanks. The buildcfg variables should be set via `./mconfig` and the initial parts of the `make`.

Please could you:

1) remove any existing builddir e.g. `rm -rf builddir`

2) Provide full output of:

```
./mconfig
make -C builddir install
```

Please place the output inside a code block so it is formatted neatly. Thank you.

**Comment by dtrudg** [comment]
Also, note that if you are installing a release, we provided pre-build packages for Ubuntu 20.04 (focal) if these would be useful:

See the downloads section of the release page: https://github.com/sylabs/singularity/releases/tag/v3.10.1

**Comment by BlackSquirrel34** [comment]
Having the same issue. similar environment, ubuntu 20.04 (see below)
full output of make:
```
$  make -C builddir
make: Entering directory '/home/{...}/singularity-ce-4.0.1/builddir'
make: *** No targets specified and no makefile found.  Stop.
make: Leaving directory '/home/{...}/singularity-ce-4.0.1/builddir'
```

How to reproduce:
After installing go and downloading and extracting SingularityCE, commands as suggested here,
https://docs.sylabs.io/guides/latest/user-guide/quick_start.htm
in section "Compile the SingularityCE source code": 
I go into the singularity folder (e.g.cd singularity-ce-4.0.1). Then first run ./mconfig. Then I try to go on with "make -C builddir" in order to complete installation.
But make command fails. (see above.)


Go version:
I installed go using those commands, just a moment before:
```
$ sudo apt install golang-1.20-go
$ sudo update-alternatives --install /usr/local/bin/go go /usr/lib/go-1.20/bin/go 1
```
running a hello-world.go worked as expected.

System information:
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
(Note: I am running this system ss a virtual machine with virt-manager)

Full output of ./mconfig:
```
Configuring for project `singularity-ce' with languages: C, Golang
=> running pre-basechecks project specific checks ...
=> running base system checks ...
 checking: host C compiler... cc
 checking: host C++ compiler... c++
 checking: host Go compiler (at least version 1.20)... /usr/local/bin/go
 checking: host C compiler option -Wall... yes
 checking: host C compiler option -Werror... yes
 checking: host C compiler option -Wfatal-errors... yes
 checking: host C compiler option -Wno-unknown-warning-option... yes
 checking: host C compiler option -Wstrict-prototypes... yes
 checking: host C compiler option -Wpointer-arith... yes
 checking: host C compiler option -Wbad-function-cast... yes
 checking: host C compiler option -Woverlength-strings... yes
 checking: host C compiler option -Wframe-larger-than=2047... yes
 checking: host C compiler option -Wno-sign-compare... yes
 checking: host C compiler option -Wclobbered... yes
 checking: host C compiler option -Wempty-body... yes
 checking: host C compiler option -Wmissing-parameter-type... yes
 checking: host C compiler option -Wtype-limits... yes
 checking: host C compiler option -Wunused-parameter... yes
 checking: host C compiler option -Wunused-but-set-parameter... yes
 checking: host C compiler option -Wno-discarded-qualifiers... yes
 checking: host C compiler option -Wno-incompatible-pointer-types... yes
 checking: host C compiler option -pipe... yes
 checking: host C compiler option -fmessage-length=0... yes
 checking: host C compiler option -fPIC... yes
 checking: host `ar' path... ar
 checking: host `ld' path... ld
 checking: host `ranlib' path... ranlib
 checking: host `objcopy' path... objcopy
 checking: target C compiler... cc
 checking: target C++ compiler... c++
 checking: target `ar' path... ar
 checking: target `ld' path... ld
 checking: target `ranlib' path... ranlib
 checking: target `objcopy' path... objcopy
 checking: host compiles static binaries... yes
 checking: target compiles static binaries... yes
 checking: host os type... unix
 checking: host architecture... x86_64
 checking: target architecture... x86_64
 checking: host architecture word size... 64
 checking: target architecture word size... 64
 checking: project version... 4.0.1
 checking: project short version... 4.0.1
=> running post-basechecks project specific checks ...
 checking: namespace: CLONE_NEWPID... yes
 checking: namespace: CLONE_FS... yes
 checking: namespace: CLONE_NEWNS... yes
 checking: namespace: CLONE_NEWUSER... yes
 checking: namespace: CLONE_NEWIPC... yes
 checking: namespace: CLONE_NEWNET... yes
 checking: namespace: CLONE_NEWUTS... yes
 checking: namespace: CLONE_NEWCGROUP... yes
 checking: feature: NO_NEW_PRIVS... yes
 checking: feature: MS_SLAVE... yes
 checking: feature: MS_REC... yes
 checking: feature: MS_PRIVATE... yes
 checking: user capabilities... yes
 checking: header linux/securebits.h... yes
 checking: header linux/capability.h... yes
 checking: libseccomp+headers... no

seccomp headers are required to build Singularity with seccomp support.
To disable seccomp support run mconfig using '--without-seccomp'.
```

**Comment by preminger** [comment]
Based on the `mconfig` output you pasted, it looks like your system doesn't have `libseccomp` and its development headers installed. Did you try to run `./mconfig --without-seccomp` as it suggests?
