### ISSUE TITLE
Delete private key using CLI

### ISSUE THREAD

**Issue by effenkeith** [sylabs/singularity#928]
It is currently possible to remove the public key from the local Singularity keyring. Can this feature be added to remove the private keyring as well? 

Deleting the files associated with the keyring seems like a brute-force method and does not take into consideration management of multiple keys.

 ~/.singularity/sypgp/pgp-secret 
 ~/.singularity/sypgp/pgp-public

There is a placeholder for this type of effort, to make the design and implementation more user friendly and expressive.
https://github.com/sylabs/singularity/issues/79

**Comment by dtrudg** [comment]
Singularity stores PGP keypairs in  `.singularity/sypgp/pgp-public` and `.singularity/sypgp/pgp-private`.

I can currently list my public keys, using...

```
$ singularity key list
Public key listing (/home/dtrudg-sylabs/.singularity/sypgp/pgp-public):

0) U: Test (No) <test@example.com>
   C: 2023-03-06 12:17:58 +0000 GMT
   F: 04FF8528BE44EF2441BAA1CA04F3403206B40AA9
   L: 4096
   --------
```

And I can remove one using...

```
$ singularity key remove 04FF8528BE44EF2441BAA1CA04F3403206B40AA9
```

I can currently list my private keys, using...

```
$ singularity key list --secret
Private key listing (/home/dtrudg-sylabs/.singularity/sypgp/pgp-secret):

0) U: Test (No) <test@example.com>
   C: 2023-03-06 12:17:58 +0000 GMT
   F: 04FF8528BE44EF2441BAA1CA04F3403206B40AA9
   L: 4096
   --------
```

But I _cannot_ remove them, as there is no `--secret` option for `remove`.

We should add `--secret` to the `remove` subcommand for keys. We should also add `--private` as a synonym of `--secret`... as it's arguably more common to talk about public / private, than it is to use 'secret' (despite e.g. GPG using secret in commands).

Technically `private` keys are stored in the `secret` keyring... so you can argue either is correct.. but it'd be nice to allow both.
