### ISSUE TITLE
Problems with binding user mounts

### ISSUE THREAD

**Issue by aakashhemadri** [sylabs/singularity#94]
I am having a technical issue

I have a collection of docker images built into sandbox directories
I use this as a source and for my instance creation.
I then bind some arbitrary empty host folder to the container image. The container path has pre-existing files/folders created as a part of the image during build.
The host folder overwrites the container path, essentially mounting an empty folder unlike the expected union the docker runtime performs, causing the `runscript` to fail as scripts in these destination directories are used.

Not sure if I am doing something wrong here or am missing something.

Also can't seem to find documentation on what to do when volumes need to be shared across instances.

Any help is appreciated :)

**Comment by dtrudg** [comment]
> I then bind some arbitrary empty host folder to the container image. The container path has pre-existing files/folders created as a part of the image during build.

This is normal behavior for Singularity. A straight bind mount is used - the directory bound-in will obscure whatever is already present at that location in the container.

> Also can't seem to find documentation on what to do when volumes need to be shared across instances.

Singularity differs from Docker in that it does not have a concept of volumes. The filesystem is a combination of the container content, and direct binds from the host into the container. To share files between instances you would need a directory on the host that is bound into all of the instances.

**Comment by aakashhemadri** [comment]
Thanks for the clarification @dtrudg
