### ISSUE TITLE
include WSL2 in the installations docus

### ISSUE THREAD

**Issue by effenkeith** [sylabs/singularity#944]
**Is your feature request related to a problem? Please describe.**
Include Windows WSL2 in the installation documentation
(https://docs.sylabs.io/guides/3.10/admin-guide/installation.html#installation-on-windows-or-mac)

**Describe the solution you'd like**
installation example of SingularityCE from the CUDA blogpost
https://sylabs.io/2022/03/wsl2-gpu/

**Describe alternatives you've considered**
using the Blogpost as the installation option

**Comment by dtrudg** [comment]
@effenkeith Please file this against the admin documentation project, which is a separate GitHub reposiroty - https://github.com/sylabs/singularity-admindocs
