### ISSUE TITLE
Attempting to push an image to sylabs returns fatal error decoding entity: invalid OjbectId in JSON: "username"

### ISSUE THREAD

**Issue by patbohn** [sylabs/singularity#945]
**Version of Singularity**
What version of Singularity are you using? Run:

```
$ singularity --version
singularity version 3.0.3-1
```

**Describe the bug**
Running on Windows in a vagrant VM, after building a singularity image file from a definition, attempting to push it to the sylabs server returns an unexpected error decoding the library URI. An access token had been generated and added to "~/.singularity/sylabs-token". 

```
vagrant@vagrant:~$ singularity push RNAFramework.sif library://patbohn/rna/rnaframework:v1
FATAL:   error decoding entity: invalid ObjectId in JSON: "patbohn"
```

**To Reproduce**
1. Install singularity on Windows 10 via vagrant as described here: https://docs.sylabs.io/guides/3.0/user-guide/installation.html#install-on-windows-or-mac 
2. Build image from a definition file
3. Create an account on sylab via github, generate an access token and add it to the local ~/.singularity/sylabs-token file
4. run 'singularity push container.sif library://username/project/container:tag'

**Expected behavior**
The image should be uploaded to the public sylabs container library. 

**OS / Linux Distribution**
Which Linux distribution are you using?
```
$ cat /etc/os-release

NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Installation Method**
Via Vagrant, as described here: 
https://docs.sylabs.io/guides/3.0/user-guide/installation.html#install-on-windows-or-mac

**Comment by EmmEff** [comment]
Hello and thank you for the feedback.

Could you please reattempt the operation using the latest version of Singularity (3.10.2) and let us know if it recurs? The version you are attempting to use is obsolete and no longer supported.

Manual for the current version is here: https://docs.sylabs.io/guides/3.10/admin-guide/installation.html#installation-on-windows-or-mac

**Comment by patbohn** [comment]
Hi, I can confirm that updating to a newer version of SingularityCE (as far as I'm aware the newest vagrantbox version was 3.9 at the time of trying) fixed my issue. Thank you for the fast advice! 

On a side note: I actually did not notice that I was on such an old version of the docs - google brought me to them; it may help having a link to the current version of Singularity(CE) on top of the docs, or a note that one is looking at docs of an old version. 

Thank you again!
